@extends('layouts.app')

@section('content')
<div class="page_content">
    <div class="main_container">
        <div class="page" title="Page 1">
<div class="section">
<div class="layoutArea">
<div class="column">
<p class="p1"><span class="s1"><strong>Polityka Prywatności </strong></span></p>
<p class="p2"><span class="s1"><strong>I Postanowienia ogólne </strong></span></p>
<ol class="ol1">
<li class="li3"><span class="s3">Wyrazom pisanym wielk</span><span class="s4">ą</span><span class="s3"> liter</span><span class="s4">ą</span><span class="s3">, a niezdefiniowanym poni</span><span class="s4">ż</span><span class="s3">ej nadano znaczenie jak w Regulaminie Serwisu dost</span><span class="s4">ę</span><span class="s3">pnym pod adresem: www.getnord.com. </span></li>
<li class="li3"><span class="s3">Niniejszy dokument określa zasady przetwarzania i ochrony danych osobowych Klientów Serwisu dost</span><span class="s4">ę</span><span class="s3">pnego pod adresem www.getnord.com. (Polityka Prywatności). </span></li>
<li class="li3"><span class="s3">Administratorem danych osobowych (Dane Osobowe) Klientów – osób fizycznych - i u</span><span class="s4">ż</span><span class="s3">ytkowników (osoby, których dane dotycz</span><span class="s4">ą</span><span class="s3">) Serwisu jest „Redlainas” UAB z siedzib</span><span class="s4">ą</span><span class="s3"> w Kownie, przy ul. Verslo 6, Kumopiai, 54311 Litwa, e-mail: support@getnord.com, numer VAT LT100001855118. </span></li>
<li class="li3"><span class="s3">Dane Osobowe, o których mowa w Polityce Prywatności to informacje o zidentyfikowanej lub mo</span><span class="s4">ż</span><span class="s3">liwej do zidentyfikowania osobie fizycznej, której dane dotycz</span><span class="s4">ą</span><span class="s3">, tj. takiej, któr</span><span class="s4">ą</span><span class="s3"> mo</span><span class="s4">ż</span><span class="s3">na bezpośrednio lub pośrednio zidentyfikować, w szczególności na podstawie cechy takiej jak: imi</span><span class="s4">ę</span><span class="s3"> i nazwisko, numer identyfikacyjny, dane o lokalizacji, identyfikator internetowy lub jednej b</span><span class="s4">ą</span><span class="s3">dź kilku cech określaj</span><span class="s4">ą</span><span class="s3">cych fizyczn</span><span class="s4">ą</span><span class="s3">, fizjologiczn</span><span class="s4">ą</span><span class="s3">, genetyczn</span><span class="s4">ą</span><span class="s3">, psychiczn</span><span class="s4">ą</span><span class="s3">, ekonomiczn</span><span class="s4">ą</span><span class="s3">, kulturow</span><span class="s4">ą</span><span class="s3"> lub społeczn</span><span class="s4">ą</span><span class="s3"> to</span><span class="s4">ż</span><span class="s3">samość osoby fizycznej. </span></li>
<li class="li3"><span class="s3">Usługodawca przetwarza Dane Osobowe, osób których dotycz</span><span class="s4">ą</span><span class="s3"> zgodnie z obowi</span><span class="s4">ą</span><span class="s3">zuj</span><span class="s4">ą</span><span class="s3">cymi przepisami, w szczególności prawa polskiego oraz Rozporz</span><span class="s4">ą</span><span class="s3">dzenia Parlamentu Europejskiego i Rady (UE) 2016/679 z 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w zwi</span><span class="s4">ą</span><span class="s3">zku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (ogólne rozporz</span><span class="s4">ą</span><span class="s3">dzenie o ochronie danych, RODO). </span></li>
<li class="li3"><span class="s3">Przetwarzanie, w rozumieniu Polityki Prywatności oznacza operacj</span><span class="s4">ę</span><span class="s3"> lub zestaw operacji wykonywanych na Danych Osobowych lub zestawach Danych Osobowych w sposób zautomatyzowany lub niezautomatyzowany, tak</span><span class="s4">ą</span><span class="s3"> jak zbieranie, utrwalanie, organizowanie, porz</span><span class="s4">ą</span><span class="s3">dkowanie, przechowywanie, adaptowanie lub modyfikowanie, pobieranie, przegl</span><span class="s4">ą</span><span class="s3">danie. </span></li>
</ol>
<p class="p2"><span class="s1"><strong>II Zakres i cel zbieranych danych </strong></span></p>
<ol class="ol1">
<li class="li3"><span class="s3">Dane Osobowe przetwarzane s</span><span class="s4">ą</span><span class="s3"> przez Administratora w Serwisie w celu umo</span><span class="s4">ż</span><span class="s3">liwienia korzystania z funkcjonalności Serwisu, w tym automatycznie podczas korzystania z Serwisu, tj. w celu: </span></li>
<ol class="ol1">
<li class="li3"><span class="s3">Rejestracji w Serwisie; </span></li>
<li class="li3"><span class="s3">zawierania umów za pośrednictwem lub dost</span><span class="s4">ę</span><span class="s3">pnych w Serwisie, w szczególności składania i realizacji Zamówienia, zawarcia i realizacji Umowy Kredytu i </span></li>
</ol>
</ol>
<p class="p4"><span class="s1">umowy Ubezpieczenia; </span></p>
<ol class="ol1">
<ol class="ol1">
<li class="li3"><span class="s3">sprawnego prowadzenia i funkcjonowania Serwisu, w tym Sklepu Internetowego oraz zapewniania bezpieczeństwa korzystania z nich, w tym dla </span></li>
</ol>
</ol>
<p class="p4"><span class="s1">ujawniania nadu</span><span class="s5">ż</span><span class="s1">yć i dokonywania analiz; </span></p>
<ol class="ol1">
<ol class="ol1">
<li class="li3"><span class="s3">wypełniania zobowi</span><span class="s4">ą</span><span class="s3">zań Usługodawcy, w szczególności reklamacyjnych dotycz</span><span class="s4">ą</span><span class="s3">cych zawartych w Serwisie lub za pośrednictwem Serwisu umów oraz </span></li>
</ol>
</ol>
<p class="p4"><span class="s1">funkcjonowania Serwisu; </span></p>
<ol class="ol1">
<ol class="ol1">
<li class="li3"><span class="s3">przygotowania i przedstawiania dopasowanych do zainteresowań i potrzeb osób, których Dane Osobowe dotycz</span><span class="s4">ą</span><span class="s3"> reklam oraz ofert i otrzymywania </span></li>
</ol>
</ol>
<p class="p4"><span class="s1">informacji handlowej, w szczególności przesyłania przez Usługodawc</span><span class="s5">ę</span><span class="s1"> na wskazany przez Klienta adres poczty elektronicznej zamówionego Newslettera; </span></p>
<ol class="ol1">
<ol class="ol1">
<li class="li3"><span class="s3">w celu publikacji Treści. </span></li>
</ol>
<li class="li3"><span class="s3">W celu: </span></li>
<ol class="ol1">
<li class="li3"><span class="s3">Rejestracji w Serwisie – przetwarzane s</span><span class="s4">ą</span><span class="s3"> nast</span><span class="s4">ę</span><span class="s3">puj</span><span class="s4">ą</span><span class="s3">ce Dane Osobowe - imi</span><span class="s4">ę</span><span class="s3"> i nazwisko, adres e-mail, Hasło, adres IP, pliki cookies; </span></li>
<li class="li3"><span class="s3">zawierania umów za pośrednictwem lub dost</span><span class="s4">ę</span><span class="s3">pnych w Serwisie, w szczególności składania i realizacji Zamówienia, zawarcia i realizacji Umowy Kredytu i </span></li>
</ol>
</ol>
<p class="p4"><span class="s1">umowy Ubezpieczenia – przetwarzane s</span><span class="s5">ą</span><span class="s1"> nast</span><span class="s5">ę</span><span class="s1">puj</span><span class="s5">ą</span><span class="s1">ce Dane Osobowe - imi</span><span class="s5">ę</span><span class="s1"> i nazwisko, adres (ulica, numer domu, miejscowość wraz z kodem pocztowym), numer telefonu kontaktowego, nr zamówienia, adres IP, pliki cookies lub inne dane podane przez Usługodawc</span><span class="s5">ę</span><span class="s1"> w Serwisie lub w trakcie kontaktu z Klientem; </span></p>
<ol class="ol1">
<ol class="ol1">
<li class="li3"><span class="s3">sprawnego prowadzenia i funkcjonowania Serwisu, w tym Sklepu Internetowego oraz zapewniania bezpieczeństwa korzystania z nich, w tym dla ujawniania nadu</span><span class="s4">ż</span><span class="s3">yć, tworzenia raportów i analiz, w tym statystyk ogl</span><span class="s4">ą</span><span class="s3">dalności podstron Serwisu – przetwarzane s</span><span class="s4">ą</span><span class="s3"> nast</span><span class="s4">ę</span><span class="s3">puj</span><span class="s4">ą</span><span class="s3">ce Dane Osobowe – wymienione w pkt 8 b; </span></li>
<li class="li3"><span class="s3">wypełniania zobowi</span><span class="s4">ą</span><span class="s3">zań Usługodawcy, w szczególności reklamacyjnych dotycz</span><span class="s4">ą</span><span class="s3">cych zawartych w Serwisie lub za pośrednictwem Serwisu umów oraz funkcjonowania Serwisu – przetwarzane s</span><span class="s4">ą</span><span class="s3"> nast</span><span class="s4">ę</span><span class="s3">puj</span><span class="s4">ą</span><span class="s3">ce Dane Osobowe – imi</span><span class="s4">ę</span><span class="s3">, nazwisko, e-mail, telefon, adres (ulica, numer domu, miejscowość wraz z kodem pocztowym), adres IP, pliki cookies, nr rachunku bankowego; </span></li>
<li class="li3"><span class="s3">przygotowania i przedstawiania dopasowanych do zainteresowań i potrzeb osób, których Dane Osobowe dotycz</span><span class="s4">ą</span><span class="s3"> reklam oraz ofert i otrzymywania informacji handlowej, w szczególności przesyłania przez Usługodawc</span><span class="s4">ę</span><span class="s3"> na wskazany przez Klienta adres poczty elektronicznej zamówionego Newslettera – przetwarzane s</span><span class="s4">ą</span><span class="s3"> nast</span><span class="s4">ę</span><span class="s3">puj</span><span class="s4">ą</span><span class="s3">ce Dane Osobowe: imi</span><span class="s4">ę</span><span class="s3">, nazwisko, PESEL, płeć, data urodzenia, stan cywilny, e-mail, telefon, adres (ulica, numer domu, miejscowość wraz z kodem pocztowym),, rodzaj dochodu, zarobki netto, liczba osób w domostwie, data zawarcia umowy ratalnej, liczba rat kredytu, adres IP, pliki cookies, numer Zamówienia; </span></li>
<li class="li3"><span class="s3">w celu publikacji Treści – przetwarzane s</span><span class="s4">ą</span><span class="s3"> nast</span><span class="s4">ę</span><span class="s3">puj</span><span class="s4">ą</span><span class="s3">ce Dane Osobowe: imi</span><span class="s4">ę</span><span class="s3">, nazwisko, e-mail, nick, adres IP, pliki cookies. </span></li>
</ol>
</ol>
<p class="p2"><span class="s1"><strong>III Podstawa prawna przetwarzania Danych Osobowych </strong></span></p>
<p class="p1"><span class="s1">9. Podstaw</span><span class="s5">ą</span><span class="s1"> prawn</span><span class="s5">ą</span><span class="s1"> przetwarzania Danych Osobowych s</span><span class="s5">ą</span><span class="s1">: </span></p>
<ol class="ol1">
<li class="li3"><span class="s3">zgoda osoby, której Dane Osobowe dotycz</span><span class="s4">ą</span><span class="s3"> na ich przetwarzanie; </span></li>
<li class="li3"><span class="s3">niezb</span><span class="s4">ę</span><span class="s3">dność do wykonania umów zawieranych w Serwisie lub za pośrednictwem Serwisu, lub do podj</span><span class="s4">ę</span><span class="s3">cia działań wnioskowanych przez osob</span><span class="s4">ę</span><span class="s3">, której </span></li>
</ol>
<p class="p5"><span class="s1">Dane Osobowe dotycz</span><span class="s5">ą</span><span class="s1"> przed zawarciem umowy; </span></p>
<ol class="ol1">
<li class="li3"><span class="s3">niezb</span><span class="s4">ę</span><span class="s3">dność do wypełnienia obowi</span><span class="s4">ą</span><span class="s3">zku prawnego ci</span><span class="s4">ążą</span><span class="s3">cego na Usługodawcy; </span></li>
<li class="li3"><span class="s3">prawnie uzasadnione interesy realizowane przez Usługodawc</span><span class="s4">ę</span><span class="s3"> lub przez stron</span><span class="s4">ę</span><span class="s3"> trzeci</span><span class="s4">ą</span><span class="s3">, którymi s</span><span class="s4">ą</span><span class="s3"> operatorzy płatności elektronicznych lub inne </span></li>
</ol>
<p class="p5"><span class="s1">realizowane w zwi</span><span class="s5">ą</span><span class="s1">zku z funkcjonalności</span><span class="s5">ą</span><span class="s1"> Serwisu, przy czym ta podstawa przetwarzania Danych Osobowych nie dotyczy dzieci. </span></p>
<p class="p2"><span class="s1">W przypadku, o którym mowa w pkt. 9 a) Dane Osobowe dotycz</span><span class="s5">ą</span><span class="s1">ce dzieci s</span><span class="s5">ą</span><span class="s1"> przetwarzane wył</span><span class="s5">ą</span><span class="s1">cznie jeśli dziecko ukończyło 16 lat. </span></p>
<p class="p2"><span class="s1"><strong>IV Okres przetwarzania Danych Osobowych </strong></span></p>
<p class="p1"><span class="s1">10. Dane Osobowe zbierane w Serwisie b</span><span class="s5">ę</span><span class="s1">d</span><span class="s5">ą</span><span class="s1"> przechowywane w celach rozliczeniowych maksymalnie przez okres wynosz</span><span class="s5">ą</span><span class="s1">cy 5 lat, licz</span><span class="s5">ą</span><span class="s1">c od końca roku kalendarzowego, w którym upłyn</span><span class="s5">ą</span><span class="s1">ł termin płatności podatku zwi</span><span class="s5">ą</span><span class="s1">zany z umow</span><span class="s5">ą</span><span class="s1"> zawart</span><span class="s5">ą</span><span class="s1"> w Serwisie lub za pośrednictwem Serwisu. W pozostałym zakresie uzasadnionym celami przetwarzania Dane Osobowe b</span><span class="s5">ę</span><span class="s1">d</span><span class="s5">ą</span><span class="s1"> przechowywane tak długo, jak istnieć b</span><span class="s5">ę</span><span class="s1">dzie podstawa prawna ich przetwarzania, chyba, </span><span class="s5">ż</span><span class="s1">e obowi</span><span class="s5">ą</span><span class="s1">zuj</span><span class="s5">ą</span><span class="s1">ce przepisy prawa wymagałyby dłu</span><span class="s5">ż</span><span class="s1">szego okresu ich przechowywania, np. dla wykorzystania w post</span><span class="s5">ę</span><span class="s1">powaniach dotycz</span><span class="s5">ą</span><span class="s1">cych funkcjonowania Serwisu. Z końcem okresu przechowywania dane osobowe zostan</span><span class="s5">ą</span><span class="s1"> usuni</span><span class="s5">ę</span><span class="s1">te lub zanonimizowane </span></p>
<p class="p2"><span class="s1"><strong>V Dobrowolność podania Danych Osobowych </strong></span></p>
<p class="p1"><span class="s1">11. Podanie Danych Osobowych w Serwisie jest dobrowolne, ale konieczne dla realizowania jednego lub wi</span><span class="s5">ę</span><span class="s1">kszej ilości celów przetwarzania Danych Osobowych zdefiniowanych w pkt. 7 powy</span><span class="s5">ż</span><span class="s1">ej, których Usługodawca nie b</span><span class="s5">ę</span><span class="s1">dzie mógł zrealizować w przypadku niepodania Danych Osobowych w Serwisie, odpowiednio dla jednego z celów lub wi</span><span class="s5">ę</span><span class="s1">kszej ich ilości, zdefiniowanych w pkt. 7 powy</span><span class="s5">ż</span><span class="s1">ej. </span></p>
<p class="p2"><span class="s1"><strong>VI Profilowanie Danych Osobowych </strong></span></p>
<p class="p1"><span class="s1">12. Dane Osobowe b</span><span class="s5">ę</span><span class="s1">d</span><span class="s5">ą</span><span class="s1"> przetwarzane w sposób zautomatyzowany, w tym profilowane do czego wykorzystywane s</span><span class="s5">ą</span><span class="s1"> informacje o zakupach, działaniach w kanałach sprzeda</span><span class="s5">ż</span><span class="s1">y Usługodawcy (IP komputera, pliki cookie, preferowane sposoby zakupu), dane socjodemograficznych (np. płeć, wiek, dochody, miejsce zamieszkania) ), w celu dostosowania informacji marketingowych do indywidualnych preferencji. </span></p>
<p class="p2"><span class="s1"><strong>VII Cookies </strong></span></p>
<ol class="ol1">
<li class="li3"><span class="s3">Usługodawca informuje, </span><span class="s4">ż</span><span class="s3">e podczas korzystania z Serwisu Dane Osobowe zbierane s</span><span class="s4">ą</span><span class="s3"> równie</span><span class="s4">ż</span><span class="s3"> automatycznie w logach systemowych Serwisu, przez pliki Cookies oraz przez system Web Beacon. </span></li>
<li class="li3"><span class="s3">Usługodawca informuje, </span><span class="s4">ż</span><span class="s3">e od momentu poł</span><span class="s4">ą</span><span class="s3">czenia si</span><span class="s4">ę</span><span class="s3"> Klienta z Serwisem, w logach systemowych Serwisu pojawia si</span><span class="s4">ę</span><span class="s3"> informacja o numerze (w tym IP) i rodzaju urz</span><span class="s4">ą</span><span class="s3">dzenia końcowego Klienta, z którego Klient ł</span><span class="s4">ą</span><span class="s3">czy si</span><span class="s4">ę</span><span class="s3"> z Serwisem. Usługodawca informuje, </span><span class="s4">ż</span><span class="s3">e zgodnie z prawem przetwarza równie</span><span class="s4">ż</span><span class="s3"> dane dotycz</span><span class="s4">ą</span><span class="s3">ce numeru (w tym IP) i rodzaju urz</span><span class="s4">ą</span><span class="s3">dzenia końcowego Klienta, a tak</span><span class="s4">ż</span><span class="s3">e czasu poł</span><span class="s4">ą</span><span class="s3">czenia Klienta ze Serwisem oraz inne dane eksploatacyjne dotycz</span><span class="s4">ą</span><span class="s3">ce aktywności Klienta w Serwisie. Opisane dane przetwarzane s</span><span class="s4">ą</span><span class="s3"> w celach technicznych dla dostosowania Serwisu do potrzeb Klientów oraz do zbierania ogólnych informacji statystycznych dotycz</span><span class="s4">ą</span><span class="s3">cych funkcjonowania Serwisu. </span></li>
<li class="li3"><span class="s3">Usługodawca wykorzystuje pliki typu Cookies w celu gromadzenia informacji zwi</span><span class="s4">ą</span><span class="s3">zanych z korzystaniem z Serwisu przez Klienta. Pliki typu Cookies to dane informatyczne, w szczególności niewielkie pliki tekstowe, zapisywane i przechowywane na urz</span><span class="s4">ą</span><span class="s3">dzeniach za pośrednictwem których Klient, korzysta z Serwisu, które umo</span><span class="s4">ż</span><span class="s3">liwiaj</span><span class="s4">ą</span><span class="s3">: </span></li>
</ol>
<p class="p5"><span class="s1">a. utrzymanie sesji Klienta (po zalogowaniu), dzi</span><span class="s5">ę</span><span class="s1">ki której Klient nie musi na ka</span><span class="s5">ż</span><span class="s1">dej podstronie Serwisu ponownie wpisywać Loginu i Hasła, b. dostosowanie i optymalizacj</span><span class="s5">ę</span><span class="s1"> Serwisu do potrzeb Klientów,<br /> c. personalizacj</span><span class="s5">ę</span><span class="s1"> przekazów marketingowych,<br /> d. zapewnienie bezpieczeństwa i niezawodności działania Serwisu. </span></p>
<ol class="ol1">
<li class="li3"><span class="s3">W Serwisie wykorzystywane s</span><span class="s4">ą</span><span class="s3"> Cookies sesyjne, ulegaj</span><span class="s4">ą</span><span class="s3">ce skasowaniu po zamkni</span><span class="s4">ę</span><span class="s3">ciu okna przegl</span><span class="s4">ą</span><span class="s3">darki internetowej, jak i Cookies trwałe, zapisywane na określony czas w urz</span><span class="s4">ą</span><span class="s3">dzeniach, za pośrednictwem których Klient korzysta ze Serwisu. </span></li>
<li class="li3"><span class="s3">Klient, mo</span><span class="s4">ż</span><span class="s3">e samodzielnie i w ka</span><span class="s4">ż</span><span class="s3">dym czasie zmienić ustawienia dotycz</span><span class="s4">ą</span><span class="s3">ce plików Cookies, określaj</span><span class="s4">ą</span><span class="s3">c warunki ich przechowywania i uzyskiwania dost</span><span class="s4">ę</span><span class="s3">pu przez pliki Cookies do Urz</span><span class="s4">ą</span><span class="s3">dzenia Klienta. Zmiany ustawień, o których mowa w zdaniu poprzednim, Klient mo</span><span class="s4">ż</span><span class="s3">e dokonać za pomoc</span><span class="s4">ą</span><span class="s3"> ustawień przegl</span><span class="s4">ą</span><span class="s3">darki internetowej lub za pomoc</span><span class="s4">ą</span><span class="s3"> konfiguracji usługi. Ustawienia te mog</span><span class="s4">ą</span><span class="s3"> zostać zmienione w szczególności w taki sposób, aby blokować automatyczn</span><span class="s4">ą</span><span class="s3"> obsług</span><span class="s4">ę</span><span class="s3"> plików Cookies w ustawieniach przegl</span><span class="s4">ą</span><span class="s3">darki internetowej b</span><span class="s4">ą</span><span class="s3">dź informować o ka</span><span class="s4">ż</span><span class="s3">dorazowym zamieszczeniu Cookies na Urz</span><span class="s4">ą</span><span class="s3">dzeniu Klienta. Szczegółowe informacje o mo</span><span class="s4">ż</span><span class="s3">liwości i sposobach obsługi plików Cookies dost</span><span class="s4">ę</span><span class="s3">pne s</span><span class="s4">ą</span><span class="s3"> w ustawieniach oprogramowania (przegl</span><span class="s4">ą</span><span class="s3">darki internetowej) Klienta. </span></li>
<li class="li3"><span class="s3">Klient mo</span><span class="s4">ż</span><span class="s3">e w ka</span><span class="s4">ż</span><span class="s3">dej chwili usun</span><span class="s4">ą</span><span class="s3">ć pliki Cookies korzystaj</span><span class="s4">ą</span><span class="s3">c z dost</span><span class="s4">ę</span><span class="s3">pnych funkcji w przegl</span><span class="s4">ą</span><span class="s3">darce internetowej, której u</span><span class="s4">ż</span><span class="s3">ywa. </span></li>
<li class="li3"><span class="s3">Ograniczenie stosowania plików Cookies, mo</span><span class="s4">ż</span><span class="s3">e wpłyn</span><span class="s4">ą</span><span class="s3">ć na niektóre funkcjonalności dost</span><span class="s4">ę</span><span class="s3">pne w Serwisie. </span></li>
<li class="li3"><span class="s3">W Serwisie wykorzystywane s</span><span class="s4">ą</span><span class="s3"> równie</span><span class="s4">ż</span><span class="s3"> Cookies zamieszczane przez partnerów Usługodawcy, umo</span><span class="s4">ż</span><span class="s3">liwiaj</span><span class="s4">ą</span><span class="s3">ce personalizacj</span><span class="s4">ę</span><span class="s3"> działalności reklamowej i rozliczanie </span></li>
</ol>
<p class="p5"><span class="s1">jej efektów. Polityka Prywatności nie reguluje sposobu wykorzystywania plików Cookies przez podmioty trzecie. Wi</span><span class="s5">ę</span><span class="s1">cej informacji o nich mo</span><span class="s5">ż</span><span class="s1">e być dost</span><span class="s5">ę</span><span class="s1">pnych na </span></p>
<p class="p5"><span class="s1">poszczególnych stronach partnerów Usługodawcy. </span></p>
<ol class="ol1">
<li class="li3"><span class="s3">Niektóre podstrony Serwisu oraz inne środki komunikacji z Klientami mog</span><span class="s4">ą</span><span class="s3"> zawierać tzw. „web beacons” (tzw. elektroniczne obrazki, zwane równie</span><span class="s4">ż</span><span class="s3"> jako puste </span></li>
</ol>
<p class="p5"><span class="s1">gify). Web Beacons pozwalaj</span><span class="s5">ą</span><span class="s1"> na otrzymanie informacji takich jak np. adres IP (Internet Protocol) komputera, na który załadowana została strona, na której Web Beacon został zamieszczony, numer URL strony, czas załadowania strony, rodzaj przegl</span><span class="s5">ą</span><span class="s1">darki, jak równie</span><span class="s5">ż</span><span class="s1"> informacje zawarte w Cookies, w celu oceny efektywności reklam. </span></p>
<p class="p2"><span class="s1"><strong>VIII Prawa i obowiązki Usługodawcy </strong></span></p>
<ol class="ol1">
<li class="li3"><span class="s3">Usługodawca zastrzega sobie prawo ujawnienia wybranych Danych Osobowych właściwym organom władzy b</span><span class="s4">ą</span><span class="s3">dź osobom trzecim, które zgłosz</span><span class="s4">ą</span> <span class="s4">żą</span><span class="s3">danie udzielenia takich informacji, w oparciu o odpowiedni</span><span class="s4">ą</span><span class="s3"> podstaw</span><span class="s4">ę</span><span class="s3"> prawn</span><span class="s4">ą</span><span class="s3">, zgodnie z przepisami obowi</span><span class="s4">ą</span><span class="s3">zuj</span><span class="s4">ą</span><span class="s3">cego prawa. </span></li>
<li class="li3"><span class="s3">Usługodawca oświadcza, </span><span class="s4">ż</span><span class="s3">e powierza przetwarzanie Danych Osobowych, na podstawie pisemnej umowy zawartej zgodnie z obowi</span><span class="s4">ą</span><span class="s3">zuj</span><span class="s4">ą</span><span class="s3">cymi przepisami podmiotom świadcz</span><span class="s4">ą</span><span class="s3">cym na rzecz Usługodawcy usługi hostingu, administracji, utrzymywania oraz zarz</span><span class="s4">ą</span><span class="s3">dzania Serwisem, jak równie</span><span class="s4">ż</span><span class="s3"> usługi w zakresie optymalizacji przekazu oraz zarz</span><span class="s4">ą</span><span class="s3">dzania kampaniami promocyjnymi. </span></li>
<li class="li3"><span class="s3">Usługodawca oświadcza, </span><span class="s4">ż</span><span class="s3">e powierza przetwarzanie Danych Osobowych Klienta podmiotom świadcz</span><span class="s4">ą</span><span class="s3">cym na rzecz Usługodawcy lub bezpośrednio Klienta usługi w zakresie niezb</span><span class="s4">ę</span><span class="s3">dnym do korzystania z Serwisu, w tym realizacji umów, w szczególności Zamówienia, rozpatrzenia reklamacji oraz korzystania z usług finansowych dost</span><span class="s4">ę</span><span class="s3">pnych w Sklepie Internetowym, na podstawie pisemnej umowy zawartej zgodnie z obowi</span><span class="s4">ą</span><span class="s3">zuj</span><span class="s4">ą</span><span class="s3">cymi przepisami. Dane Osobowe Klientów mog</span><span class="s4">ą</span><span class="s3"> zostać powierzone w szczególności dostawcom Produktów, Bankom, Ubezpieczycielom, instytucjom finansowym i ubezpieczeniowym. </span></li>
</ol>
<p class="p2"><span class="s1"><strong>IX Przetwarzanie Danych Osobowych przez Przetwarzających </strong></span></p>
<ol class="ol1">
<li class="li3"><span class="s3">Przetwarzaj</span><span class="s4">ą</span><span class="s3">cy w rozumieniu Polityki Prywatności to podmioty, o których mowa w pkt. 23 i pkt. 24, które na zlecenie Usługodawcy przetwarzaj</span><span class="s4">ą</span><span class="s3"> Dane Osobowe. </span></li>
<li class="li3"><span class="s3">Przetwarzaj</span><span class="s4">ą</span><span class="s3">cy jest upowa</span><span class="s4">ż</span><span class="s3">niony i ma prawo do przetwarzania Danych Osobowych wył</span><span class="s4">ą</span><span class="s3">cznie w celach i w zakresie określonych w Polityce Prywatności. </span></li>
<li class="li3"><span class="s3">Dane Osobowe mog</span><span class="s4">ą</span><span class="s3"> być przetwarzane wył</span><span class="s4">ą</span><span class="s3">cznie na terenie Polski, Państwa Członkowskiego Unii Europejskiej (UE) albo na terenie sygnatariusza Porozumienia </span></li>
</ol>
<p class="p5"><span class="s1">Europejskiego Obszaru Gospodarczego (EOG). </span></p>
<ol class="ol1">
<li class="li3"><span class="s3">Przetwarzaj</span><span class="s4">ą</span><span class="s3">cy przetwarza powierzone Dane Osobowe zgodnie z obowi</span><span class="s4">ą</span><span class="s3">zuj</span><span class="s4">ą</span><span class="s3">cymi przepisami prawa, w szczególności Przetwarzaj</span><span class="s4">ą</span><span class="s3">cy: </span></li>
<ol class="ol1">
<li class="li3"><span class="s3">stosuje wymagane prawem środki techniczne i organizacyjne, w szczególności w zakresie bezpieczeństwa przetwarzania Danych Osobowych. </span></li>
<li class="li3"><span class="s3">stosuje środki zapewniaj</span><span class="s4">ą</span><span class="s3">ce: i) zdolność do ci</span><span class="s4">ą</span><span class="s3">głego zapewnienia poufności, integralności, dost</span><span class="s4">ę</span><span class="s3">pności i odporności systemów i usług przetwarzania; ii) </span></li>
</ol>
</ol>
<p class="p4"><span class="s1">zdolność do szybkiego przywrócenia dost</span><span class="s5">ę</span><span class="s1">pności danych osobowych i dost</span><span class="s5">ę</span><span class="s1">pu do nich w razie incydentu fizycznego lub technicznego; iii) regularne </span></p>
<p class="p4"><span class="s1">testowanie, mierzenie i ocenianie skuteczności środków technicznych i organizacyjnych maj</span><span class="s5">ą</span><span class="s1">cych zapewnić bezpieczeństwo przetwarzania. </span></p>
<ol class="ol1">
<ol class="ol1">
<li class="li3"><span class="s3">stosuje środki zabezpieczenia Danych Osobowych na poziomie nie ni</span><span class="s4">ż</span><span class="s3">szym ni</span><span class="s4">ż</span><span class="s3"> stosowany przez Usługodawc</span><span class="s4">ę</span><span class="s3">. </span></li>
</ol>
<li class="li3"><span class="s3">Przetwarzaj</span><span class="s4">ą</span><span class="s3">cy mo</span><span class="s4">ż</span><span class="s3">e zmienić, usun</span><span class="s4">ą</span><span class="s3">ć lub zablokować przetwarzane Dane Osobowe, wył</span><span class="s4">ą</span><span class="s3">cznie na polecenie Administratora danych. Jeśli osoba, której Dane Osobowe dotycz</span><span class="s4">ą</span><span class="s3"> zwróci si</span><span class="s4">ę</span><span class="s3"> bezpośrednio do Przetwarzaj</span><span class="s4">ą</span><span class="s3">cego o zmian</span><span class="s4">ę</span><span class="s3"> lub usuni</span><span class="s4">ę</span><span class="s3">cie jej Danych Osobowych, Przetwarzaj</span><span class="s4">ą</span><span class="s3">cy niezwłocznie, w terminie nie później ni</span><span class="s4">ż</span><span class="s3"> 5 dni robocze, przekazuje tak</span><span class="s4">ą</span><span class="s3"> prośb</span><span class="s4">ę</span><span class="s3"> Usługodawcy. </span></li>
<li class="li3"><span class="s3">Przetwarzaj</span><span class="s4">ą</span><span class="s3">cy nie powinien przetwarzać Danych Osobowych w celu innym ni</span><span class="s4">ż</span><span class="s3"> wykonanie zobowi</span><span class="s4">ą</span><span class="s3">zań wskazanych w Polityce Prywatności. Przetwarzaj</span><span class="s4">ą</span><span class="s3">cy nie mo</span><span class="s4">ż</span><span class="s3">e ujawniać Danych Osobowych osobom trzecim. </span></li>
<li class="li3"><span class="s3">Przetwarzaj</span><span class="s4">ą</span><span class="s3">cy jest odpowiedzialny wobec osoby, której Dane Osobowe dotycz</span><span class="s4">ą</span><span class="s3"> za szkody, które osoba ta mo</span><span class="s4">ż</span><span class="s3">e ponieść w rezultacie działania i zaniechania Przetwarzaj</span><span class="s4">ą</span><span class="s3">cego. </span></li>
</ol>
<p class="p2"><span class="s1"><strong>X Prawa i obowiązki osoby, której Dane Osobowe dotyczą </strong></span></p>
<ol class="ol1">
<li class="li3"><span class="s3">Ka</span><span class="s4">ż</span><span class="s3">dy Klient ma prawo: </span></li>
<ol class="ol1">
<li class="li3"><span class="s3">dost</span><span class="s4">ę</span><span class="s3">pu do swoich Danych Osobowych, prawo ich sprostowania, usuni</span><span class="s4">ę</span><span class="s3">cia oraz prawo </span><span class="s4">żą</span><span class="s3">dania ograniczania przetwarzania. </span></li>
<li class="li3"><span class="s3">wnieść sprzeciw wobec przetwarzania Danych Osobowych, cofn</span><span class="s4">ą</span><span class="s3">ć zgod</span><span class="s4">ę</span><span class="s3"> na przetwarzanie Danych Osobowych w jednym lub wi</span><span class="s4">ę</span><span class="s3">kszej liczbie celów na </span></li>
</ol>
</ol>
<p class="p4"><span class="s1">jaki była udzielona, w dowolnym momencie bez wpływu na zgodność z prawem przetwarzania, którego dokonano na podstawie zgody przed jej cofni</span><span class="s5">ę</span><span class="s1">ciem, a tak</span><span class="s5">ż</span><span class="s1">e prawo przeniesienia swoich Danych Osobowych. </span></p>
<ol class="ol1">
<li class="li3"><span class="s3">W celu realizacji uprawnień, o których mowa w pkt. 32 a) powy</span><span class="s4">ż</span><span class="s3">ej nale</span><span class="s4">ż</span><span class="s3">y wysłać e-mail na adres: support@getnord.com lub skorzystać z funkcjonalności udost</span><span class="s4">ę</span><span class="s3">pnionych w Koncie Klienta. </span></li>
<li class="li3"><span class="s3">W celu realizacji uprawnień, o których mowa w pkt. 32 b) powy</span><span class="s4">ż</span><span class="s3">ej nale</span><span class="s4">ż</span><span class="s3">y wysłać e-mail na adres: support@getnord.com wpisuj</span><span class="s4">ą</span><span class="s3">c w tytule słowo „sprzeciw” lub „cofni</span><span class="s4">ę</span><span class="s3">cie zgody”, klikn</span><span class="s4">ą</span><span class="s3">ć na link powoduj</span><span class="s4">ą</span><span class="s3">cy cofni</span><span class="s4">ę</span><span class="s3">cie zgody umieszczony w treści informacji handlowej lub wysłać pisemn</span><span class="s4">ą</span><span class="s3"> informacj</span><span class="s4">ę</span><span class="s3"> o cofni</span><span class="s4">ę</span><span class="s3">ciu zgody na otrzymywanie informacji handlowej na adres Usługodawcy: Redlainas UAB, Verslo 6, Kumpiai, 54311, Kowno, z dopiskiem DANE OSOBOWE. </span></li>
<li class="li3"><span class="s3">Je</span><span class="s4">ż</span><span class="s3">eli Klient umieszcza w Serwisie jakiekolwiek dane osobowe innych osób (w tym ich imi</span><span class="s4">ę</span><span class="s3"> i nazwisko, adres, numer telefonu lub e-mail), mo</span><span class="s4">ż</span><span class="s3">e to uczynić jedynie pod warunkiem nienaruszania przepisów obowi</span><span class="s4">ą</span><span class="s3">zuj</span><span class="s4">ą</span><span class="s3">cego prawa i dóbr osobistych tych osób. </span></li>
</ol>
<ol class="ol1">
<li class="li3"><span class="s3">Klient uprawniony jest do korzystania z Danych Osobowych i treści udost</span><span class="s4">ę</span><span class="s3">pnionych przez inne osoby w Serwisie wył</span><span class="s4">ą</span><span class="s3">cznie w zwi</span><span class="s4">ą</span><span class="s3">zku z korzystaniem z Serwisu oraz za ich zgod</span><span class="s4">ą</span><span class="s3"> w sposób zgodny z przepisami obowi</span><span class="s4">ą</span><span class="s3">zuj</span><span class="s4">ą</span><span class="s3">cego prawa, chyba </span><span class="s4">ż</span><span class="s3">e uzyska zgod</span><span class="s4">ę</span><span class="s3"> od tych innych osób na przetwarzanie ich Danych Osobowych i ich treści w zakresie lub celu przewidzianymi Polityk</span><span class="s4">ą</span><span class="s3"> Prywatności i wykraczaj</span><span class="s4">ą</span><span class="s3">cym poza korzystanie z Serwisu. </span></li>
<li class="li3"><span class="s3">Ka</span><span class="s4">ż</span><span class="s3">dy Klient ma prawo wnieść skarg</span><span class="s4">ę</span><span class="s3"> do organu nadzoruj</span><span class="s4">ą</span><span class="s3">cego przetwarzanie Danych Osobowych. </span></li>
</ol>
<p class="p2"><span class="s1"><strong>XI Zabezpieczenie Danych Osobowych </strong></span></p>
<ol class="ol1">
<li class="li3"><span class="s3">Usługodawca oświadcza, i</span><span class="s4">ż</span><span class="s3"> dokłada starań, aby zapewnić Klientom wysoki poziom bezpieczeństwa w zakresie korzystania z Serwisu i w tym celu:<br /> a. stosuje wymagane prawem środki techniczne i organizacyjne, w szczególności w zakresie bezpieczeństwa przetwarzania Danych Osobowych;<br /> b. stosuje środki zapewniaj</span><span class="s4">ą</span><span class="s3">ce: i) zdolność do ci</span><span class="s4">ą</span><span class="s3">głego zapewnienia poufności, integralności, dost</span><span class="s4">ę</span><span class="s3">pności i odporności systemów i usług przetwarzania; ii) </span></li>
</ol>
<p class="p5"><span class="s1">zdolność do szybkiego przywrócenia dost</span><span class="s5">ę</span><span class="s1">pności Danych Osobowych i dost</span><span class="s5">ę</span><span class="s1">pu do nich w razie incydentu fizycznego lub technicznego; iii) regularne testowanie, mierzenie i ocenianie skuteczności środków technicznych i organizacyjnych maj</span><span class="s5">ą</span><span class="s1">cych zapewnić bezpieczeństwo przetwarzania. </span></p>
<ol class="ol1">
<li class="li3"><span class="s3">Wszelkie zdarzenia maj</span><span class="s4">ą</span><span class="s3">ce wpływ na bezpieczeństwo przekazu informacji, danych, w tym równie</span><span class="s4">ż</span><span class="s3"> dotycz</span><span class="s4">ą</span><span class="s3">ce podejrzenia udost</span><span class="s4">ę</span><span class="s3">pniania plików zawieraj</span><span class="s4">ą</span><span class="s3">cych wirusy i innych plików o podobnym charakterze lub innych, ani</span><span class="s4">ż</span><span class="s3">eli pliki mechanizmów destrukcyjnych nale</span><span class="s4">ż</span><span class="s3">y zgłaszać Usługodawcy na konto e-mail: support@getnord.com. </span></li>
</ol>
<p class="p2"><span class="s1"><strong>XII Postanowienia końcowe </strong></span></p>
<p class="p1"><span class="s1">40. W sprawach nie uregulowanych w Polityce Prywatności maj</span><span class="s5">ą</span><span class="s1"> zastosowanie przepisy prawa dotycz</span><span class="s5">ą</span><span class="s1">ce przetwarzania Danych Osobowych, w tym RODO. </span></p>
</div>
</div>
</div>
</div> 
</div>
</div>
@endsection