@extends('layouts.app')

@section('content')
<div class="page_content">
    <div class="main_container">
        <p class="p1"><span class="s1"><strong>REGULAMIN SKLEPU INTERNETOWEGO GETNORD.COM</strong></span></p>
<p class="p2"> </p>
<p class="p3"><span class="s1"><strong>I. Definicje</strong></span></p>
<p class="p1"><span class="s1">Użyte w regulaminie pojęcia oznaczają:</span></p>
<p class="p1"><span class="s1">1.<strong>Klient</strong> – osoba fizyczna, osoba prawna lub jednostka organizacyjna nie będącą osobą prawną, której przepisy szczególne przyznają zdolność prawną, która dokonuje zamówienia w ramach sklepu;</span></p>
<p class="p1"><span class="s1"><strong>Konsument</strong> - osoba fizyczna, która dokonuje czynności prawnej niezwiązanej   bezpośrednio z prowadzoną przez siebie działalnością gospodarczą lub zawodową.</span></p>
<p class="p4"><span class="s1">2. <strong>Kodeks Cywilny</strong> – ustawa z dnia 18 lipca 2000 r. (</span><span class="s2">VIII-1864</span><span class="s1">.); </span></p>
<p class="p1"><span class="s1">3. <strong>Ustawa z dnia 10.11.1994</strong> roku o prawach konsumenta (I-675)</span></p>
<p class="p1"><span class="s1">4. <strong>Regulamin</strong> – niniejszy regulamin świadczenia usług drogą elektroniczną w ramach sklepu internetowego getnord.com;</span></p>
<p class="p1"><span class="s1">5. <strong>Sklep internetowy (Sklep)</strong> – serwis internetowy dostępny pod getnord.com, za pośrednictwem którego Klient może w szczególności składać zamówienia; </span></p>
<p class="p1"><span class="s1">6. <strong>Towar</strong> – produkty prezentowane w sklepie internetowym;</span></p>
<p class="p1"><span class="s1">7. <strong>Umowa sprzedaży</strong> – umowa sprzedaży towarów w rozumieniu Kodeksu Cywilnego, zawarta pomiędzy firmą Redlainas UAB a Klientem, zawierana z wykorzystaniem serwisu internetowego sklepu;</span></p>
<p class="p1"><span class="s1">8. <strong>Zamówienie</strong> – oświadczenie woli Klienta, zmierzające bezpośrednio do zawarcia umowy sprzedaży, określające w szczególności rodzaj i liczbę towaru;<br /> </span></p>
<p class="p1"><span class="s1"> </span></p>
<p class="p1"><span class="s1"><strong>II. Postanowienia ogólne </strong></span></p>
<p class="p1"><span class="s1">2.1. Niniejszy regulamin określa zasady korzystania ze sklepu internetowego dostępnego pod  getnord.com. </span></p>
<p class="p1"><span class="s1">2.2. Sklep internetowy, działający pod  nazwą getnord.com, prowadzony jest przez firmę Redlainas UAB, ul. Verslo 6, 54311 Kowno, Litwa</span></p>
<p class="p1"><span class="s1">NIP: 235983690. </span></p>
<p class="p1"><span class="s1">E-mail: support@getnord.com</span></p>
<p class="p1"><span class="s1">2.3. Niniejszy regulamin określa w szczególności :</span></p>
<p class="p1"><span class="s1">a.) zasady dokonywania rejestracji i korzystania z konta w ramach sklepu internetowego;</span></p>
<p class="p1"><span class="s1">b.) warunki i zasady dokonywania elektronicznej rezerwacji produktów dostępnych w ramach sklepu internetowego;</span></p>
<p class="p1"><span class="s1">c.) warunki i zasady składania drogą elektroniczną zamówień w ramach sklepu internetowego;</span></p>
<p class="p1"><span class="s1">d.) zasady zawierania umów sprzedaży z wykorzystaniem usług świadczonych w ramach sklepu internetowego.</span></p>
<p class="p1"><span class="s1">2.4. Zgodnie z obowiązującymi przepisami prawa firma Redlainas UAB zastrzega sobie możliwość ograniczenia świadczenia usług za pośrednictwem sklepu internetowego do osób, które ukończyły wiek 18 lat. W takim przypadku potencjalni Klienci zostaną o powyższym powiadomieni.</span></p>
<p class="p1"><span class="s1">2.5. Informacje o towarach podane na stronach internetowych sklepu, w szczególności ich opisy, parametry techniczne i użytkowe oraz ceny, stanowią zaproszenie do zawarcia umowy, w rozumieniu Kodeksu Cywilnego. Prezentowane opisy i ceny produktów nie stanowią oferty handlowej w rozumieniu Kodeksu Cywilnego, a mają jedynie charakter informacyjny. </span></p>
<p class="p2"> </p>
<p class="p3"><span class="s1"><strong>III. Zasady korzystania ze sklepu internetowego i przetwarzanie danych osobowych ( RODO)</strong></span></p>
<p class="p1"><span class="s1">3.1. Warunkiem rozpoczęcia korzystania ze sklepu internetowego jest rejestracja w jego ramach ( zalecane) bądź złożenie zamówienia bez rejestrowania użytkownika.</span></p>
<p class="p1"><span class="s1">3.2. Rejestracja następuje poprzez wypełnienie i zaakceptowanie formularza rejestracyjnego, udostępnianego na jednej ze stron sklepu.</span></p>
<p class="p1"><span class="s1">3.3. Warunkiem rejestracji lub korzystania ze sklepu bez jej dokonywania jest wyrażenie zgody na treść regulaminu oraz podanie danych osobowych oznaczonych jako obowiązkowe.<br /> Firma Redlainas UAB, jako administrator danych osobowych informuje, że dane osobowe są zbierane i przetwarzane wyłącznie w celach:</span></p>
<p class="p1"><span class="s1">                 - zawarcia umowy kupna-sprzedaży,<br />                 - wykonania ciążących na nas obowiązków prawnych i księgowych,</span></p>
<p class="p1"><span class="s1">                - wykrywania nadużyć i zapobiegania im,</span></p>
<p class="p1"><span class="s1">                - wsparcia obsługi klienta.</span></p>
<p class="p1"><span class="s1">Posiadają Państwo prawo dostępu do treści swoich danych oraz otrzymania ich kopii, ich sprostowania, usunięcia, ograniczenia przetwarzania, prawo do przenoszenia danych, prawo do cofnięcia zgody na ich przetwarzanie.</span></p>
<p class="p1"><span class="s1">Dane osobowe są udostępniane podmiotom zewnętrznym jedynie w celu ich przetwarzania w naszym imieniu. Przykładem takich podmiotów są: biura podatkowe, firmy kurierskie, firmy windykacyjne.</span></p>
<p class="p1"><span class="s1">Państwa dane osobowe będą przetwarzane na podstawie art. 6 ust. 1 pkt Rozporządzenia Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. i zgodnie z treścią ogólnego rozporządzenia o ochronie danych.</span></p>
<p class="p1"><span class="s1">Dane osobowe będą przechowywane przez okres niezbędny do realizacji umowy, bądź do momentu wyrażenia sprzeciwu przez Państwa.</span></p>
<p class="p1"><span class="s1">Mają Państwo prawo wniesienia skargi do organu nadzorczego, gdy uznają Państwo, iż przetwarzanie Państwa danych osobowych narusza przepisy ogólnego Rozporządzenia o ochronie danych osobowych z dnia 27 kwietnia 2016 r.</span></p>
<p class="p1"><span class="s1">Kontakt do Administratora Danych Osobowych: support@getnord.com</span></p>
<p class="p1"><span class="s1">3.4. Firma Redlainas UAB </span><span class="s3"> </span><span class="s1">może pozbawić Klienta prawa do korzystania ze sklepu internetowego, jak również może ograniczyć jego dostęp do części lub całości zasobów sklepu internetowego, ze skutkiem natychmiastowym, w przypadku naruszenia przez Klienta regulaminu, a w szczególności, gdy Klient:</span></p>
<p class="p1"><span class="s1">a.) podał w trakcie rejestracji w sklepie internetowym dane niezgodne z prawdą, niedokładne lub nieaktualne, wprowadzające w błąd lub naruszające prawa osób trzecich,</span></p>
<p class="p1"><span class="s1">b.) dopuścił się za pośrednictwem sklepu internetowego naruszenia dóbr osobistych osób trzecich, w szczególności dóbr osobistych innych Klientów sklepu internetowego,</span></p>
<p class="p1"><span class="s1">c.) dopuści się innych zachowań, które zostaną uznane przez Redlainas UAB<span class="Apple-converted-space">  </span>za zachowania niezgodne z obowiązującymi przepisami prawa lub ogólnymi zasadami korzystania z sieci Internet lub godzące w dobre imię Redlainas UAB .</span></p>
<p class="p2"> </p>
<p class="p3"><span class="s1"><strong>IV. Procedura zawarcia umowy sprzedaży</strong></span></p>
<p class="p1"><span class="s1">4.1 Zamówienia w sklepie można składać we wszystkie dni w roku 24 godziny na dobę, jednakże zamówienia złożone w dni wolne ( tj. soboty, niedziele i święta) oraz po godzinach pracy sklepu przyjmowane będą w pierwszym dniu roboczym następującym po tym dniu.</span></p>
<p class="p1"><span class="s1">4.2. W celu zawarcia umowy sprzedaży za pośrednictwem sklepu internetowego należy wejść na stronę internetową getnord.com, dokonać wyboru towaru, podejmując kolejne czynności techniczne w oparciu o wyświetlane Klientowi komunikaty oraz informacje dostępne na stronie.</span></p>
<p class="p1"><span class="s1">4.3. Wybór zamawianych towarów przez Klienta jest dokonywany poprzez ich dodanie do koszyka.</span></p>
<p class="p1"><span class="s1">4.4. W trakcie składania zamówienia – do momentu naciśnięcia przycisku „Potwierdź zamówienie” – Klient ma możliwość modyfikacji wprowadzonych danych oraz w zakresie wyboru towaru. W tym celu należy kierować się wyświetlanymi Klientowi komunikatami oraz informacjami dostępnymi na stronie. Naciśnięcie przycisku: „Potwierdź zamówienie” nakłada na Klienta obowiązek zapłaty.</span></p>
<p class="p1"><span class="s1">4.5. Po podaniu przez Klienta korzystającego ze sklepu internetowego wszystkich niezbędnych danych, wyświetlone zostanie podsumowanie złożonego zamówienia. Podsumowanie złożonego zamówienia będzie zawierać informacje dotyczące:</span></p>
<p class="p4"><span class="s4">a.) przedmiotu zamówienia,</span></p>
<p class="p1"><span class="s1">b.) jednostkowej oraz łącznej ceny zamawianych produktów lub usług, w tym kosztów dostawy , </span></p>
<p class="p1"><span class="s1">c.) wybranej metody płatności, </span></p>
<p class="p1"><span class="s1">d.) wybranego sposobu dostawy.</span></p>
<p class="p1"><span class="s1">4.6. W celu wysłania zamówienia konieczne jest dokonanie akceptacji treści regulaminu, podanie danych osobowych oznaczonych jako obowiązkowe.</span></p>
<p class="p1"><span class="s1">4.7. Wysłanie przez Klienta zamówienia stanowi oświadczenie woli zawarcia z firmą Redlainas UAB umowy sprzedaży, zgodnie z treścią regulaminu.</span></p>
<p class="p1"><span class="s1">4.8. Po złożeniu zamówienia, Klient otrzymuje wiadomość e-mail  potwierdzającą złożenie zamówienia. Umowę traktuje się za zawartą z momentem otrzymania przez Klienta wiadomości e-mail, o której mowa powyżej.</span></p>
<p class="p1"><span class="s1">4.9. Umowa sprzedaży zawierana jest w języku polskim, o treści zgodnej z regulaminem.   </span></p>
<p class="p1"><span class="s1">4.10. Firma Redlainas UAB   zastrzega sobie prawo do odrzucenia zamówienia w następujących przypadkach:</span></p>
<p class="p1"><span class="s1">a) błędnie lub częściowo wypełniony formularz zamówienia,</span></p>
<p class="p1"><span class="s1">b) brak uiszczenia wymaganej płatności w wyznaczonym terminie.</span></p>
<p class="p1"><span class="s1">4.11. Zamówienie zostanie zrealizowane pod warunkiem dostępności zamówionego towaru. W przypadku braku dostępności zamówionego towaru Zamawiający zostanie o tym fakcie niezwłocznie powiadomiony drogą mailową lub telefoniczną. W takim przypadku Zamawiający ma prawo do podjęcia decyzji o sposobie realizacji zamówienia ( zmiana produktu, wydłużenie czasu oczekiwania, anulowanie zamówienia).</span></p>
<p class="p2"> </p>
<p class="p3"><span class="s1"><strong>V. Dostawa </strong></span></p>
<p class="p1"><span class="s1">5.1. Dostawa towarów jest ograniczona do obszaru Rzeczypospolitej Polskiej i odbywa się pod adres wskazany przez Klienta w trakcie składania zamówienia.</span></p>
<p class="p1"><span class="s1">5.2. Termin realizacji dostawy wynosi od 1 do 7  dni roboczych licząc od dnia złożenia zamówienia lub dnia wpłynięcia zapłaty  na konto</span><span class="s3"> </span><span class="s1">firmy Redlainas UAB<span class="Apple-converted-space">  </span>(w zależności od wybranej formy płatności). Wyjątek stanowią towary przy których podana jest informacja z innym terminem realizacji.</span></p>
<p class="p1"><span class="s1">5.3. Klienci mogą uzyskać dostęp do niniejszego regulaminu w każdym czasie za pośrednictwem odsyłacza zamieszczonego na stronie głównej serwisu getnord.com oraz pobrać go i sporządzić jego wydruk. </span></p>
<p class="p1"><span class="s1">5.4 Przy odbiorze przesyłki od kuriera należy sprawdzić czy opakowanie oraz taśmy nie uległy uszkodzeniu w trakcie transportu. W przypadku zaistnienia takiej sytuacji proszę odmówić przyjęcia przesyłki lub sprawdzić jej zawartość i stan w obecności kuriera. Istotne jest również sporządzenie protokołu szkody.</span></p>
<p class="p2"> </p>
<p class="p2"><strong> VI. Ceny i metody płatności </strong></p>
<p class="p1"><span class="s1">6.1. Ceny towarów podawane są w złotych polskich i zawierają wszystkie składniki, w tym podatek VAT (z wyróżnieniem wysokości stawki).</span></p>
<p class="p1"><span class="s1">6.2. Firma Redlainas UAB</span><span class="s3"> </span><span class="s1">zastrzega sobie prawo do zmiany cen na stronie sklepu internetowego getnord.com bez uprzedzenia. Zmiany cen nie dotyczą zamówień będących w trakcie realizacji. </span></p>
<p class="p5"><span class="s1">6.3 Operatorem kart płatniczych jest Braintree a service of PayPal, </span><span class="s5">222 W Merchandise Mart Plaza, Suite 800, Chicago, IL 60654.</span></p>
<p class="p6"> </p>
<p class="p4"><span class="s4"><strong>VII. Uprawnienie do odstąpienia od umowy</strong></span></p>
<p class="p1"><span class="s1">Wzór pouczenia o odstąpieniu od umowy zgodny z załącznikiem do Ustawy o Prawach Konsumenta z dnia 10.11.1994 roku </span></p>
<p class="p1"><span class="s1">7.1. Konsument ma prawo odstąpić od niniejszej umowy w terminie 14 dni bez podania jakiejkolwiek przyczyny.</span></p>
<p class="p1"><span class="s1">7.2. Termin do odstąpienia od umowy wygasa po upływie 14 dni od dnia w którym weszli Państwo w posiadanie rzeczy lub w którym osoba trzecia inna niż przewoźnik i wskazana przez Państwa weszła w posiadanie rzeczy.<br />  </span></p>
<p class="p1"><span class="s1">7.3. Aby skorzystać z prawa odstąpienia od umowy, muszą Państwo poinformować nas – firmę Redlainas UAB zarejestrowaną przy ul. Verslo 6, Kumpiai, 54311, Kowno, Litwa e-mail: support@getnord.com o swojej decyzji o odstąpieniu od niniejszej umowy w drodze jednoznacznego oświadczenia (na przykład pismo wysłane pocztą, faksem lub pocztą elektroniczną).</span></p>
<p class="p1"><span class="s1">7.4. Mogą Państwo skorzystać z wzoru formularza odstąpienia od umowy, jednak nie jest to obowiązkowe. Wzór formularza można znaleźć na naszej stronie internetowej www.getnord.com w zakładce dokumenty do pobrania. Mogą Państwo również wypełnić i przesłać formularz odstąpienia od umowy lub jakiekolwiek inne jednoznaczne oświadczenie drogą elektroniczną na adres support@getnord.com. Jeżeli skorzystają Państwo z tej możliwości, prześlemy Państwu niezwłocznie potwierdzenie otrzymania informacji o odstąpieniu od umowy na trwałym nośniku (na przykład pocztą elektroniczną).</span></p>
<p class="p1"><span class="s1">7.5. Aby zachować termin do odstąpienia od umowy, wystarczy, aby wysłali Państwo informację dotyczącą wykonania przysługującego Państwu prawa odstąpienia od umowy przed upływem terminu do odstąpienia od umowy.</span></p>
<p class="p1"><span class="s1">7.6. Skutki odstąpienia od umowy</span></p>
<p class="p1"><span class="s1">W przypadku odstąpienia od niniejszej umowy zwracamy Państwu wszystkie otrzymane od Państwa płatności, w tym koszty dostarczenia rzeczy (z wyjątkiem dodatkowych kosztów wynikających z wybranego przez Państwa sposobu dostarczenia innego niż najtańszy zwykły sposób dostarczenia oferowany przez nas), niezwłocznie, a w każdym przypadku nie później niż 14 dni od dnia, w którym zostaliśmy poinformowani o Państwa decyzji o wykonaniu prawa odstąpienia od niniejszej umowy. Zwrotu płatności dokonamy przy użyciu takich samych sposobów płatności, jakie zostały przez Państwa użyte w pierwotnej transakcji, chyba że wyraźnie zgodziliście się Państwo na inne rozwiązanie; w każdym przypadku nie poniosą Państwo żadnych opłat w związku z tym zwrotem. Możemy wstrzymać się ze zwrotem płatności do czasu otrzymania rzeczy lub do czasu dostarczenia nam dowodu jej odesłania, w zależności od tego, które zdarzenie nastąpi wcześniej. </span></p>
<p class="p1"><span class="s1">7.7. Jeżeli konsument otrzymał rzeczy w związku z umową:</span></p>
<p class="p1"><span class="s1">a)  Proszę odesłać lub przekazać nam rzecz niezwłocznie, a w każdym razie nie później niż 14 dni od dnia, w którym poinformowali nas Państwo o odstąpieniu od niniejszej umowy. Termin jest zachowany, jeżeli odeślą Państwo rzecz przed upływem terminu 14 dni. Zakupiony towar należy zwrócić na adres ustalony z pracownikiem sklepu internetowego.</span></p>
<p class="p1"><span class="s1">b)  Będą Państwo musieli ponieść bezpośrednie koszty zwrotu rzeczy.</span></p>
<p class="p1"><span class="s1">c)  Odpowiadają Państwo tylko za zmniejszenie wartości rzeczy wynikające z korzystania z niej w sposób inny niż było to konieczne do stwierdzenia charakteru, cech i funkcjonowania rzeczy.</span></p>
<p class="p1"><span class="s1">7.8. Prawo odstąpienia od umowy zawartej poza lokalem przedsiębiorstwa lub na odległość nie przysługuje konsumentowi w odniesieniu do umów:</span></p>
<p class="p1"><span class="s1">1)   o świadczenie usług, jeżeli przedsiębiorca wykonał w pełni usługę za wyraźną zgodą konsumenta, który został poinformowany przed rozpoczęciem świadczenia, że po spełnieniu świadczenia przez przedsiębiorcę utraci prawo odstąpienia od umowy; </span></p>
<p class="p1"><span class="s1">2)   w której cena lub wynagrodzenie zależy od wahań na rynku finansowym, nad którymi przedsiębiorca nie sprawuje kontroli, i które mogą wystąpić przed upływem terminu do odstąpienia od umowy;</span></p>
<p class="p1"><span class="s1">3)   w której przedmiotem świadczenia jest rzecz nieprefabrykowana, wyprodukowana według specyfikacji konsumenta lub służąca zaspokojeniu jego zindywidualizowanych potrzeb; </span></p>
<p class="p1"><span class="s1">4)   w której przedmiotem świadczenia są rzeczy, które po dostarczeniu, ze względu na swój charakter, zostają nierozłącznie połączone z innymi rzeczami;</span></p>
<p class="p1"><span class="s1">5)   w której konsument wyraźnie żądał, aby przedsiębiorca do niego przyjechał w celu dokonania pilnej naprawy lub konserwacji; jeżeli przedsiębiorca świadczy dodatkowo inne usługi niż te, których wykonania konsument żądał, lub dostarcza rzeczy inne niż części zamienne niezbędne do wykonania naprawy lub konserwacji, prawo odstąpienia od umowy przysługuje konsumentowi w odniesieniu do dodatkowych usług lub rzeczy;</span></p>
<p class="p1"><span class="s1">6)   w której przedmiotem świadczenia są nagrania dźwiękowe lub wizualne albo programy komputerowe dostarczane w zapieczętowanym opakowaniu, jeżeli opakowanie zostało otwarte po dostarczeniu;</span></p>
<p class="p1"><span class="s1">7)    o dostarczanie treści cyfrowych, które nie są zapisane na nośniku materialnym, jeżeli spełnianie świadczenia rozpoczęło się za wyraźną zgodą konsumenta przed upływem terminu do odstąpienia od umowy i po poinformowaniu go przez przedsiębiorcę o utracie prawa odstąpienia od umowy.</span></p>
<p class="p1"><span class="s1">7.9. Zwracany przez Klienta towar powinien zostać opakowany w odpowiedni sposób, zapewniający brak uszkodzeń przesyłki w trakcie transportu.</span></p>
<p class="p2"> </p>
<p class="p4"><span class="s4"><strong>VIII. Reklamacje dotyczące towarów</strong></span></p>
<p class="p1"><span class="s1">8.1.</span><span class="s3"> </span><span class="s1">Firma Redlainas UAB<span class="Apple-converted-space">  </span>jako sprzedawca odpowiada wobec Klienta jeżeli sprzedany Produkt ma wadę fizyczną lub prawną z tytułu rękojmi na podstawie ustawy kodeks cywilny oraz innych powszechnie obowiązujących przepisów prawa. Wada fizyczna polega na niezgodności sprzedanego Produktu z Umową Sprzedaży. Wada prawna oznacza, że produkt stanowi własność osoby trzeciej albo jeżeli jest obciążony prawem osoby trzeciej, a także jeżeli ograniczenie w korzystaniu lub rozporządzaniu Produktem wynika z decyzji lub orzeczenia właściwego organu; w razie sprzedaży prawa sprzedawca jest odpowiedzialny także za istnienie prawa. </span></p>
<p class="p1"><span class="s1">8.2. Zwolnienie Sprzedawcy od odpowiedzialności.</span></p>
<p class="p1"><span class="s1">Sprzedawca jest zwolniony od odpowiedzialności z tytułu rękojmi, jeżeli Klient wiedział o wadzie w chwili zawarcia Umowy Sprzedaży.</span></p>
<p class="p1"><span class="s1">Gdy przedmiotem Umowy Sprzedaży są Produkty oznaczone tylko co do gatunku albo Produkty mające powstać w przyszłości, Sprzedawca jest zwolniony od odpowiedzialności z tytułu rękojmi, jeżeli Klient wiedział o wadzie w chwili wydania rzeczy. Przepisu tego nie stosuje się, gdy Klientem jest konsument.</span></p>
<p class="p1"><span class="s1">Sprzedawca nie jest odpowiedzialny względem Klienta będącego konsumentem za to, że sprzedany Produkt nie ma właściwości wynikających z publicznych zapewnień, o których mowa powyżej, jeżeli zapewnień tych nie znał ani, oceniając rozsądnie, nie mógł znać albo nie mogły one mieć wpływu na decyzję Klienta o zawarciu Umowy Sprzedaży, albo gdy ich treść została sprostowana przed zawarciem Umowy Sprzedaży.</span></p>
<p class="p1"><span class="s1">8.3. Podstawowe uprawnienia Klienta.</span></p>
<p class="p1"><span class="s1">1) Grupa: obniżenie ceny /zwrot pieniędzy</span></p>
<p class="p1"><span class="s1">Jeżeli sprzedany Produkt ma wadę, Klient może złożyć oświadczenie o obniżeniu ceny albo odstąpieniu od Umowy Sprzedaży, chyba że Sprzedawca niezwłocznie i bez nadmiernych niedogodności dla Klienta wymieni wadliwy Produkt na wolny od wad albo wadę usunie. Ograniczenie to nie ma zastosowania, jeżeli Produkt był już wymieniony lub naprawiany przez Sprzedawcę albo Sprzedawca nie uczynił zadość obowiązkowi wymiany Produktu na wolny od wad lub usunięcia wady. Obniżona cena powinna pozostawać w takiej proporcji do ceny wynikającej z Umowy Sprzedaży, w jakiej wartość Produktu z wadą pozostaje do wartości Produktu bez wady. Klient nie może odstąpić od Umowy Sprzedaży, jeżeli wada jest nieistotna.</span></p>
<p class="p1"><span class="s1">Jeżeli Klientem jest konsument, może on zamiast zaproponowanego przez Sprzedawcę zgodnie z postanowieniami powyżej usunięcia wady żądać wymiany Produktu na wolny od wad albo zamiast wymiany Produktu żądać usunięcia wady, chyba że doprowadzenie Produktu do zgodności z Umową Sprzedaży w sposób wybrany przez Klienta jest niemożliwe albo wymagałoby nadmiernych kosztów w porównaniu ze sposobem proponowanym przez Sprzedawcę. Przy ocenie nadmierności kosztów uwzględnia się wartość Produktu wolnego od wad, rodzaj i znaczenie stwierdzonej wady, a także bierze się pod uwagę niedogodności, na jakie narażałby Klienta inny sposób zaspokojenia. </span></p>
<p class="p1"><span class="s1">Jeżeli spośród sprzedanych Produktów tylko niektóre są wadliwe i dają się odłączyć od Produktów wolnych od wad, bez szkody dla stron obu, uprawnienie Klienta do odstąpienia od umowy ograniczone jest do Produktów wadliwych.</span></p>
<p class="p1"><span class="s1">2) Grupa: naprawa/wymiana</span></p>
<p class="p1"><span class="s1">Jeżeli sprzedany Produkt ma wadę, Klient może żądać wymiany Produktu na wolny od wad albo usunięcia wady. Sprzedawca jest obowiązany wymienić Produkt wadliwy na wolny od wad lub usunąć wadę w rozsądnym czasie bez nadmiernych niedogodności dla Klienta. Sprzedawca może odmówić zadośćuczynienia żądaniu Klienta, jeżeli doprowadzenie do zgodności z Umową Sprzedaży Produktu wadliwego w sposób wybrany przez Klienta jest niemożliwe albo w porównaniu z drugim możliwym sposobem doprowadzenia do zgodności z Umową Sprzedaży wymagałoby nadmiernych kosztów. </span></p>
<p class="p1"><span class="s1">8.4. Terminy reklamacyjne</span></p>
<p class="p1"><span class="s1">a.) 1 rok domniemania istnienia wady w chwili wydania Produktu</span></p>
<p class="p1"><span class="s1">Sprzedawca jest odpowiedzialny z tytułu rękojmi za wady fizyczne, które istniały w chwili przejścia niebezpieczeństwa na Klienta lub wynikły z przyczyny tkwiącej w sprzedanym Produkcie w tej samej chwili. Jeżeli Klientem jest konsument, a wada fizyczna została stwierdzona przed upływem roku od dnia wydania sprzedanego Produktu, domniemywa się, że wada lub jej przyczyna istniała w chwili przejścia niebezpieczeństwa na Klienta.</span></p>
<p class="p1"><span class="s1">b.) 2 lata odpowiedzialności Sprzedawcy</span></p>
<p class="p1"><span class="s1">Sprzedawca odpowiada z tytułu rękojmi, jeżeli wada fizyczna zostanie stwierdzona przed upływem dwóch lat od dnia wydania Produktu Klientowi. Do wykonywania uprawnień z tytułu rękojmi za wady prawne sprzedanego Produktu stosuje się przepisy dotyczące wady fizycznej, z tym że bieg terminu do wykonania uprawnień z tytułu rękojmi rozpoczyna się od dnia, w którym Klient dowiedział się o istnieniu wady, a jeżeli Klient dowiedział się o istnieniu wady dopiero na skutek powództwa osoby trzeciej – od dnia, w którym orzeczenie wydane w sporze z osobą trzecią stało się prawomocne.</span></p>
<p class="p1"><span class="s1">8.5. Reklamacje, wynikające z naruszenia praw Klienta gwarantowanych prawnie, lub na podstawie niniejszego regulaminu, należy kierować na adres support@getnord.com.</span><span class="s3"> </span><span class="s1">Firma Redlainas UAB<span class="Apple-converted-space">  </span>zobowiązuje się do rozpatrzenia każdej reklamacji w terminie do 14 dni, a gdyby to nie było możliwe, do poinformowania w tym okresie Klienta, kiedy reklamacja zostanie rozpatrzona.</span></p>
<p class="p1"><span class="s1">8.6. Dostarczenie reklamowanego towaru.</span></p>
<p class="p1"><span class="s1">W przypadku gdy do ustosunkowania się przez Sprzedawcę do reklamacji Klienta lub do wykonania uprawnień Klienta wynikających z niezgodności Produktu z Umową Sprzedaży/rękojmi niezbędne będzie dostarczenie Produktu do Sprzedawcy, Klient może zostać poproszony przez Sprzedawcę o dostarczenie Produktu na koszt Sprzedawcy na wskazany przez niego adres. Jeżeli jednak ze względu na rodzaj niezgodności/wady, rodzaj Produktu lub sposób jego zamontowania dostarczenie Produktu przez Klienta byłoby niemożliwe albo nadmiernie utrudnione, Klient obowiązany jest udostępnić Produkt Sprzedawcy w miejscu, w którym Produkt się znajduje.</span></p>
<p class="p1"><span class="s1">8.7. Termin realizacji żądania reklamacyjnego konsumenta przez sprzedawcę.</span></p>
<p class="p4"><span class="s4">Sprzedawca jest obowiązany wymienić wadliwy Produkt na wolny od wad lub usunąć wadę w rozsądnym czasie bez nadmiernych<strong> </strong>niedogodności dla Klienta.<strong> </strong>W przypadku żądania zwrotu pieniędzy zwrot na rzecz konsumenta powinien nastąpić niezwłocznie. W przypadku żądania obniżenia ceny Klient powinien wyznaczyć Sprzedawcy termin na ich zwrot (np. 7 dni od dnia otrzymania żądania obniżenia ceny).</span></p>
<p class="p1"><span class="s1">8.8. Koszty reklamacyjne.</span></p>
<p class="p1"><span class="s1">Z zastrzeżeniem dwóch wyjątków zamieszczonych poniżej (dotyczących demontażu i ponownego montażu) koszty wymiany lub naprawy ponosi Sprzedawca. W szczególności obejmuje to koszty demontażu i dostarczenia Produktu, robocizny, materiałów oraz ponownego zamontowania i uruchomienia. Jeżeli wadliwy Produkt został zamontowany, Klient może żądać od Sprzedawcy demontażu i ponownego zamontowania po dokonaniu wymiany na wolny od wad lub usunięciu wady. W razie niewykonania tego obowiązku przez Sprzedawcę Klient jest upoważniony do dokonania tych czynności na koszt i niebezpieczeństwo Sprzedawcy. Poniżej prezentujemy dwa wyjątki: </span></p>
<p class="p1"><span class="s1"><br /> 1. Sprzedawca może odmówić demontażu i ponownego zamontowania, jeżeli koszt tych czynności przewyższa cenę sprzedanego produktu.</span></p>
<p class="p1"><span class="s1"><br /> 2. Jeżeli klientem jest konsument, może on żądać od sprzedawcy demontażu i ponownego zamontowania, jest obowiązany jednak ponieść część związanych z tym kosztów przewyższających cenę sprzedanego produktu albo może żadać od sprzedawcy zapłaty cześci kosztów demontażu i ponownego zamontowania, do wysokości ceny sprzedanego produktu.<br /> Klient w razie odstąpienia od umowy albo żądania wymiany produktu na wolny od wad, jest obowiązany na koszt sprzedawcy dostarczyć wadliwy produkt. Jeżeli jednak ze względu na rodzaj produktu lub sposób jego zamontowania dostarczenie produktu przez klienta byłoby nadmiernie utrudnione, klient obowiązany jest udostępnić produkt sprzedawcy w miejscu, w którym produkt się znajduje.<br /> W przypadku innych kosztów poniesionych przez klienta w związaku z reklamacją klient może się ich domagać na zasadach ogólnych. Do odpowiedzialności odszkodowawczej stosuje się przepisy Kodeksu cywilnego o skutkach niewykonania zobowiązań.</span></p>
<p class="p1"><span class="s1"><br /> 8.9. Firma Redlainas UAB<span class="Apple-converted-space">  </span>nie jest producentem towarów. Producent ponosi odpowiedzialność z tytułu gwarancji sprzedanego towaru na warunkach oraz przez okres wskazany w warunkach gwarancji. Jeśli dokument gwarancyjny przewiduje taką możliwość, Klient może zgłaszać swoje roszczenia w ramach gwarancji bezpośrednio w autoryzowanym serwisie, którego adres znajduje się w warunkach gwarancji.</span></p>
<p class="p1"><span class="s1"><br /> 8.10. Do reklamowanego towaru należy dołączyć dowód zakupu, kartę gwarancyjną o ile takowa została dostarczona Kupującemu oraz opis uszkodzenia lub wady towaru.</span></p>
<p class="p1"> </p>
<p class="p1"><span class="s1"> <strong>IX. Postanowienia końcowe</strong></span></p>
<p class="p1"><span class="s1"><br /> 9.1. Rozstrzyganie ewentualnych sporów powstałych pomiędzy firmą Redlainas UAB<span class="Apple-converted-space">  </span>a Klientem zostaje poddane sądom właściwym zgodnie z postanowieniami właściwych przepisów Kodeksu postępowania cywilnego.</span></p>
<p class="p1"><span class="s1"><br /> 9.2. W sprawach nieuregulowanych w niniejszym regulaminie mają zastosowanie przepisy Kodeksu cywilnego, przepisy Ustawy o prawach konsumenta oraz inne właściwe przepisy prawa polskiego.</span></p>
 </div>
</div>
@endsection