@extends('layouts.app')

@section('content')
<div class="page_content">
    <div class="main-container" id="legal-notes">
        <section class="heading">
            <div class="text-container">
                <p>ESTOS TÉRMINOS Y CONDICIONES CONSTITUYEN LA BASE PARA LAS VISITAS Y EL USO DE NUESTRA PÁGINA WEB. LÉELAS DETENIDAMENTE YA QUE CONTIENEN INFORMACIÓN IMPORTANTE.</p>
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>1. General</h1>
            </div>
            <div class="text-container">
                <p> 1.1 LOS PRESENTES TÉRMINOS Y CONDICIONES (LOS «TÉRMINOS») SE APLICAN AL USO QUE HAGAS DE ESTA PÁGINA WEB (LA «PÁGINA WEB»). AL ACCEDER A LA PÁGINA WEB O AL HACER UN PEDIDO ACEPTAS SOMETERTE A LOS PRESENTES TÉRMINOS, QUE INCLUYEN NUESTRA POLÍTICA DE PRIVACIDAD Y NUESTRA POLÍTICA DE COOKIES («POLÍTICAS DE PRIVACIDAD Y DE COOKIES»). SI NO ACEPTAS SOMETERTE A LOS PRESENTES TÉRMINOS NO PODRÁS UTILIZAR O ACCEDER A ESTA PÁGINA WEB.</p>
                <p>1.2 EN LOS PRESENTES TÉRMINOS, SALVO QUE EL CONTEXTO EXIJA LO CONTRARIO:</p>
                <ul>
                    <li>•	«CONTRATO» SIGNIFICA CADA CONTRATO DE SUMINISTRO DE BIENES POR NUESTRA PARTE AL QUE SE INCORPORARÁN LOS PRESENTES TÉRMINOS;</li>
                    <li>•	«TARJETA» SIGNIFICA LA TARJETA DE CRÉDITO O DE DÉBITO QUE UTILICES PARA PAGAR LOS BIENES;</li>
                    <li>•	«BIENES» SIGNIFICA LOS BIENES QUE SUMINISTRAMOS DE ACUERDO CON LOS PRESENTES TÉRMINOS;<li>
                    <li>•	«PEDIDO» SIGNIFICA UNA ORDEN DE COMPRA RESPECTO A LOS BIENES EMITIDA POR TI PARA NOSOTROS.</li>
                </ul>
                <p>1.3 ESTA WEB ES PROPIEDAD DE Y SE ENCUENTRA GESTIONADA POR REDLAINAS. «GETNORD.COM» ES UNA DIVISIÓN DE REDLAINAS. SEDE SOCIAL DE REDLAINAS: VERSLO 6, KUMPIAI, KAUNAS, 54311 LITUANIA. NÚMERO DE REGISTRO 235983690, N.º DE IVA: LT100001855118. SI QUIERES PREGUNTARNOS ALGUNA COSA SOBRE LOS PRESENTES TÉRMINOS O TIENES ALGÚN COMENTARIO O QUEJA SOBRE ESTA PÁGINA WEB, ENVÍANOS UN CORREO ELECTRÓNICO A SUPPORT@GETNORD.COM</p>
                <p>1.4 GETNORD.COMSE RESERVA EL DERECHO A CAMBIAR LOS PRESENTES TÉRMINOS OCASIONALMENTE. CUALQUIER CAMBIO ENTRARÁ EN VIGOR CUANDO SE PUBLIQUE EN LA PÁGINA WEB Y SERÁ RESPONSABILIDAD TUYA LEER LOS TÉRMINOS Y CONDICIONES CADA VEZ QUE UTILICES ESTA PÁGINA WEB. </p>
                <p>1.5 PUEDE HABER AVISOS LEGALES EN OTROS APARTADOS DE LA PÁGINA WEB RELACIONADOS CON EL USO QUE HAGAS DE LA MISMA, COMO NUESTRAS POLÍTICAS DE PRIVACIDAD Y DE COOKIES, LAS CUALES JUNTO CON LOS PRESENTES TÉRMINOS RIGEN EL USO QUE HAGAS DE ESTA PÁGINA WEB.</p>
                <p>1.6 GETNORD.COMPODRÁ HABILITAR PERIÓDICAMENTE SERVICIOS EN LA PÁGINA WEB QUE REQUIERAN REGISTRARSE EN LA MISMA. LA INFORMACIÓN QUE FACILITES EN ESTA PÁGINA WEB DEBERÁ SER COMPLETA Y PRECISA.ACEPTAS NO SUPLANTAR A OTRA PERSONA O ENTIDAD NI USAR UN NOMBRE FALSO O UN NOMBRE DEL QUE NO TENGAS AUTORIZACIÓN PARA USAR.</p>
                <p>1.7 LOS SIGUIENTES ACCESOS A ESOS SERVICIOS REQUERIRÁN LA INTRODUCCIÓN DE DATOS DE CUENTA Y UNA CONTRASEÑA ADECUADOS («DATOS DE INICIO DE SESIÓN»). ERES RESPONSABLE DE MANTENER LA CONFIDENCIALIDAD DE TUS DATOS DE INICIO DE SESIÓN Y DE CUALQUIER ACTIVIDAD QUE SE PRODUZCA CON TU CUENTA. GETNORD.COMNO SERÁ RESPONSABLE FRENTE A NINGUNA PERSONA POR LA PÉRDIDA O EL DAÑO QUE PUDIERA OCURRIR COMO RESULTADO DE UN FALLO EN LA PROTECCIÓN DE TUS DATOS DE INICIO DE SESIÓN. EN CASO DE QUE TENGAS ALGUNA DUDA EN RELACIÓN CON TUS DATOS DE INICIO DE SESIÓN U OBSERVES CUALQUIER USO INDEBIDO, ENTONCES DEBERÁS INFORMARNOS DE INMEDIATO PONIÉNDOTE EN CONTACTO CON EL EQUIPO DE ATENCIÓN AL CLIENTE A TRAVÉS DE CONTACT@GETNORD.COM</p>
                <p>1.8 VENDEMOS PRODUCTOS PARA NIÑOS PARA QUE LOS COMPREN ADULTOS. ES NECESARIO TENER AL MENOS 18 AÑOS PARA PODER REALIZAR COMPRAS EN NUESTRA PÁGINA WEB. CADA VEZ QUE COMPRES UN PRODUCTO EN ESTA PÁGINA WEB, MANIFIESTAS A GETNORD.COMQUE TIENES AL MENOS 18 AÑOS. NO PODEMOS PROHIBIR LA VISITA DE MENORES A ESTA PÁGINA WEB. CONFIAMOS EN LOS PADRES, TUTORES Y RESPONSABLES DE LA SUPERVISIÓN DE LOS MENORES DE 18 AÑOS PARA DECIDIR QUÉ MATERIALES SON ADECUADOS PARA QUE VEAN/COMPREN SUS HIJOS/LOS MENORES. SI TIENES MENOS DE 18 AÑOS, DEBERÁS USAR ESTA PÁGINA WEB ÚNICAMENTE ACOMPAÑADO DE UN PADRE O TUTOR.</p>
         
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>2. ORDER PROCESS</h1>
            </div>
            <div class="text-container">
                <p>2.1 CUANDO EXISTA UNA SOLICITUD DE PEDIDO, SOLICITAREMOS INFORMACIÓN DEL USUARIO CUANDO SEA NECESARIO. AQUÍ UN USUARIO DEBERÁ PROPORCIONAR INFORMACIÓN DE CONTACTO (COMO SU NOMBRE, DIRECCIÓN DE ENTREGA, NÚMERO DE TELÉFONO) E INFORMACIÓN FINANCIERA (COMO SU NÚMERO DE TARJETA DE CRÉDITO, FECHA DE VENCIMIENTO). ESA INFORMACIÓN SE USA PARA FACTURAR Y PARA CUMPLIMENTAR LOS PEDIDOS DE LOS CLIENTES. SI TIENES PROBLEMAS PARA PROCESAR UN PEDIDO, USAREMOS ESA INFORMACIÓN DE CONTACTO PARA PONERNOS EN CONTACTO CON EL USUARIO.</p>
                <p>2.2 CUANDO NOS HAGAS UN PEDIDO DEBERÁS PASAR POR UN PROCESO DE PAGO SEGURO Y HASTA EL PUNTO EN EL QUE HAGAS CLIC EN «REALIZAR PEDIDO» EN LA PÁGINA FINAL DEL PROCESO DE PAGO, PODRÁS AÑADIR/CAMBIAR/ELIMINAR CUALQUIER ARTÍCULO QUE HAYAS COLOCADO EN TU CESTA.</p>
                <p>2.3 CUANDO HAGAS UN PEDIDO POR TELÉFONO, TE PEDIREMOS TU NOMBRE, DIRECCIÓN DE ENVÍO/FACTURACIÓN, NÚMERO DE CONTACTO, DIRECCIÓN DE CORREO ELECTRÓNICO Y DATOS DE PAGO. UNA VEZ QUE HAYAMOS ACEPTADO EL PAGO Y CONFIRMADO EL PEDIDO, NO PODRÁS AÑADIR/CAMBIAR/ELIMINAR NINGÚN ARTÍCULO.</p>
                <p>2.4 TEN EN CUENTA QUE LOS COLORES DE LOS BIENES SON TAN PRECISOS COMO PERMITA LA PÁGINA WEB, YA QUE LOS COLORES REALES QUE ESTÉS VIENDO DEPENDERÁN DE TU MONITOR. NO PODEMOS GARANTIZAR QUE LA VISUALIZACIÓN DE CUALQUIER COLOR DE TU MONITOR REFLEJE CON PRECISIÓN EL COLOR DEL PRODUCTO QUE SE ENTREGARÁ.</p>
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>3. DE RECIBO Y ACEPTACIÓN DE TU PEDIDO</h1>
            </div>
            <div class="text-container">
                <p>3.1 SI NOS HAS PROPORCIONADO UNA DIRECCIÓN DE CORREO ELECTRÓNICO, TE ENVIAREMOS UN ACUSE DE RECIBO DEL CORREO ELECTRÓNICO DE TU PEDIDO UNA VEZ QUE LO HAYAS REALIZADO, Y DESPUÉS TE ENVIAREMOS OTRO CORREO ELECTRÓNICO EN EL MOMENTO DEL ENVÍO DE TUS BIENES. TODOS LOS PEDIDOS, TANTO SI SE EFECTÚAN POR LA PÁGINA WEB COMO POR CUALQUIER OTRO MÉTODO, ESTARÁN SUJETOS A NUESTRA ACEPTACIÓN DE ACUERDO CON LOS PRESENTES TÉRMINOS. NUESTRA ACEPTACIÓN DE TU PEDIDO Y LA FINALIZACIÓN DEL CONTRATO ENTRE TÚ Y NOSOTROS SE PRODUCIRÁ TRAS EL ENVÍO DE LOS BIENES PEDIDOS.</p>
                <p>3.2 PODRÁS DISPONER DE CUALQUIER OFERTA DE BIENES CON PRECIOS REBAJADOS, INCLUIDOS LOS DETALLADOS EN LA PÁGINA WEB, OCASIONALMENTE, PARA QUE LA UTILICES (CON SUJECIÓN A NUESTRA ACEPTACIÓN) POR UN PERIODO DE TIEMPO LIMITADO TAL COMO SE MENCIONE EN DICHA OFERTA.</p>
                <p>3.3 GETNORD.COMHA TENIDO EL MÁXIMO CUIDADO EN LA PREPARACIÓN DEL CONTENIDO DE ESTA PÁGINA WEB, Y EN PARTICULAR PARA GARANTIZAR QUE (I) LOS PRECIOS INDICADOS SEAN CORRECTOS EN EL MOMENTO DE LA PUBLICACIÓN Y (II) LOS BIENES SE HAYAN DESCRITO DE MANERA RAZONABLE. NO OBSTANTE, TEN EN CUENTA QUE SOLO PODREMOS ACEPTAR PEDIDOS SI NO HAY NINGÚN ERROR MATERIAL EN LA DESCRIPCIÓN DE LOS BIENES O DE SUS PRECIOS SEGÚN LO ANUNCIADO EN LA PÁGINA WEB.</p>
                <p>3.4 LA NO ACEPTACIÓN DE UN PEDIDO PODRÍA DEBERSE A UNA DE LAS SIGUIENTES RAZONES:</p>
                <ul>
                    <li>3.4.1 UNO O MÁS DE LOS BIENES QUE HAS PEDIDO NO ESTÁN DISPONIBLES. TE INFORMAREMOS LO ANTES POSIBLE SI LOS BIENES QUE HAS PEDIDO NO ESTÁN DISPONIBLES;</li>
                    <li>3.4.2 LA IMPOSIBILIDAD DE QUE OBTENGAMOS AUTORIZACIÓN PARA TU PAGO. PODEMOS PONERNOS EN CONTACTO CONTIGO PARA COMPROBAR LOS DATOS DE TU TARJETA;</li>
                    <li>3.4.3 LA IDENTIFICACIÓN DE UN ERROR DE PRECIO O EN LA DESCRIPCIÓN DEL PRODUCTO CON ARREGLO A LA DISPOSICIÓN 3.3; </li>
                    <li>3.4.4 NO CUMPLES LOS CRITERIOS DE ELEGIBILIDAD PARA HACER UN PEDIDO DE CONFORMIDAD CON LO DISPUESTO EN LOS PRESENTES TÉRMINOS.</li>
                </ul>
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>4. PRICING</h1>
            </div>
            <div class="text-container">
                <p>4.1 CON SUJECIÓN A LA DISPOSICIÓN 6.7 (GASTOS DE ENTREGA), LOS PRECIOS ESTIPULADOS EN EL MOMENTO DE LA RECEPCIÓN DEL PEDIDO SON LOS PRECIOS QUE PAGARÁS SALVO SI DESCUBRIMOS UN ERROR EN EL PRECIO DE LOS BIENES QUE HAS PEDIDO. EN ESE CASO, TE INFORMAREMOS LO ANTES POSIBLE TRAS RECIBIR TU PEDIDO Y TE DAREMOS LA OPCIÓN DE VOLVER A CONFIRMAR TU PEDIDO CON EL PRECIO CORRECTO, O BIEN CANCELARLO. SI NO PODEMOS PONERNOS EN CONTACTO CONTIGO, CONSIDERAREMOS EL PEDIDO COMO CANCELADO.</p>
                <p>4.2 TODOS LOS PRECIOS SE MUESTRAN EN LA PÁGINA WEB EN EUROS E INCLUYEN EL IVA Y OTROS IMPUESTOS APLICABLES AL TIPO EN VIGOR QUE SE COBRA EN ESPAÑA. COMPRUEBA CON TU BANCO LOS TIPOS DE CAMBIO ACTUALES. </p>
                <p>4.3 PRECIOS Y PROMOCIONES: EN OCASIONES, LOS PRECIOS Y LAS PROMOCIONES OFRECIDOS RESPECTO A LOS BIENES PUBLICITADOS EN LA PÁGINA WEB PUEDEN DIFERIR DE LOS PRECIOS Y LAS PROMOCIONES OFRECIDOS A LA VEZ EN NUESTRAS TIENDAS FÍSICAS DE GETNORD. NO TENEMOS NINGUNA OBLIGACIÓN DE RESPETAR NINGÚN PRECIO O PROMOCIÓN DE TIENDA EN CASO DE QUE DIFIERAN DE LOS DE LA PÁGINA WEB. ASIMISMO, LAS TIENDAS GETNIRD NO TIENEN NINGUNA OBLIGACIÓN DE RESPETAR NINGÚN PRECIO O PROMOCIÓN DE LA PÁGINA WEB EN CASO DE QUE DIFIERAN DE LOS DE LA TIENDA. LOS PRECIOS QUE SE REDUZCAN POR REBAJAS Y LAS PROMOCIONES SON SOLO VÁLIDOS DURANTE EL PERIODO ESPECIFICADO. NOS RESERVAMOS EL DERECHO A AJUSTAR LOS PRECIOS, LAS OFERTAS, LOS BIENES Y LAS ESPECIFICACIONES DE LOS BIENES EN LA PÁGINA WEB A NUESTRA DISCRECIÓN EN CUALQUIER MOMENTO ANTES (PERO NO DESPUÉS) DE QUE ACEPTEMOS TU PEDIDO.</p>
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>5. 5.	MÉTODO DE PAGO</h1>
            </div>
            <div class="text-container">
                <p>5.1 PUEDES PAGAR UTILIZANDO UNA TARJETA DE CRÉDITO O DE DÉBITO YA SEA VISA, MASTER CARD, SWITCH, DELTA O VISA ELECTRON. ES IMPERATIVO QUE NOS INDIQUES EL NOMBRE DEL TITULAR TAL COMO APAREZCA EN LA TARJETA, ASÍ COMO LA DIRECCIÓN EXACTAMENTE COMO APAREZCA EN EL EXTRACTO DE LA TARJETA.</p>
                <p>5.2 PUEDES PAGAR CON PAYPAL.</p>
                <p>5.3 NO PODEMOS ACEPTAR PAGOS CON CHEQUE, TARJETAS DE TIPO AMERICAN EXPRESS, EFECTIVO, GIROS POSTALES O VALES REGALO.</p>
                <p>5.4 EL FRAUDE CON TARJETAS ES ILEGAL Y DARÁ LUGAR A UNA DENUNCIA EN TODOS LOS CASOS.</p>
                <p>5.5 TRATAMOS DE GARANTIZAR QUE LOS BIENES QUE SE MUESTRAN ESTÉN DISPONIBLES PARA PEDIR; NO OBSTANTE, CUANDO CUALQUIERA DE LOS BIENES CONTENIDOS EN UN PEDIDO ESTÉ AGOTADO, NOS PONDREMOS EN CONTACTO CONTIGO PARA EXPLICARTE LA SITUACIÓN Y CONFIRMAR EN CASO DE QUERER CANCELAR TODO EL PEDIDO O SI PREFIERES PROCESAR UN NUEVO PEDIDO CON BIENES DE LOS QUE SÍ TENGAMOS EXISTENCIAS.</p>
                <p>5.6 LA PROPIEDAD DE LOS BIENES QUE PIDAS EN LA PÁGINA WEB PASARÁ A TI EN EL MOMENTO DE LA ENTREGA SIEMPRE QUE HAYAMOS PROCESADO Y RECIBIDO EL PAGO COMPLETO DE LOS MISMOS.</p>
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>6. 6.	ENTREGA</h1>
            </div>
            <div class="text-container">
                <p>6.1 GETNORD.COMPUEDE ENTREGAR TUS BIENES A CUALQUIER DIRECCIÓN DENTRO DE LA PENÍNSULA INCLUIDAS LAS ISLAS BALEARES Y LAS CANARIAS. SIN EMBARGO, EN LA ACTUALIDAD NO PODEMOS HACER ENTREGAS EN LAS CIUDADES DE CEUTA Y MELILLA.</p>
                <p>6.2 </p>
                <ul>
                    <li>Austria</li>
                    <li>Belgium</li>
                    <li>Czech Republic</li>
                    <li>Germany</li>
                    <li>Denmark</li>
                    <li>France</li>
                    <li>Hungary</li>
                    <li>Ireland, Republic of</li>
                    <li>Luxembourg</li>
                    <li>Netherlands</li>
                    <li>Slovenia</li>
                    <li>Slovakia</li>
                    <li>Estonia</li>
                    <li>Spain</li>
                    <li>Finland</li>
                    <li>Italy</li>
                    <li>Latvia</li>
                    <li>Lithuania</li>
                    <li>Poland</li>
                    <li>Portugal</li>
                    <li>Sweden</li>
                    <li>Bulgaria</li>
                    <li>Greece</li>
                    <li>Romania</li>
                </ul>
                <p>6.3 TEN EN CUENTA QUE EN LA ENTREGA NUESTROS TRANSPORTISTAS PUEDEN NECESITAR QUE FIRMES EL ALBARÁN. SI LA FIRMA ES NECESARIA, NUESTROS TRANSPORTISTAS NO PODRÁN ENTREGAR NINGÚN BIEN SIN TENERLA.</p>
                <p>6.4 SELECCIONAR LA DIRECCIÓN DE ENTREGA:</p>
                <ul>
                    <li>6.4.1 ENTREGA A LA DIRECCIÓN DE TU TARJETA (SI ESA OPCIÓN ESTÁ DISPONIBLE EN TU PAÍS Y HAS DADO EL CONSENTIMIENTO NECESARIO A LA ENTIDAD EMISORA DE LA TARJETA): CUANDO HAYAS SELECCIONADO LOS BIENES QUE QUIERES COMPRAR, LA DIRECCIÓN DE ENTREGA SE EXTRAERÁ POR DEFECTO DE LA DIRECCIÓN DE FACTURACIÓN DE TU TARJETA.</li>
                    <li>6.4.2 SELECCIONAR UNA DIRECCIÓN ALTERNATIVA: NO OBSTANTE, SI DESEAS ENVIAR BIENES A UNA DIRECCIÓN ALTERNATIVA, ENTONCES PUEDES INTRODUCIRLA EN EL FORMULARIO DE DIRECCIÓN DE ENTREGA PERSONALIZADA A MEDIDA QUE AVANCES EN EL PROCESO DE PAGO. LA DIRECCIÓN ALTERNATIVA PUEDE SER PERSONAL O DE NEGOCIOS.</li>
                </ul>
                <p>6.5 PARA QUE TE RESULTE MÁS FÁCIL, SI CONFIGURAS UNA CUENTA CON GETNORD.COMPODRÁS ALMACENAR TUS DIRECCIONES FAVORITAS PARA QUE CUANDO VUELVAS A HACER UN PEDIDO SOLO TENGAS QUE SELECCIONARLA DE TU LIBRETA DE DIRECCIONES DE ENTREGA Y AHORRARTE ASÍ EL TIEMPO Y LAS MOLESTIAS DE VOLVER A RELLENAR EL FORMULARIO.</p>
                <p>6.6 NUESTRO SERVICIO DE ENTREGA EN LA UNIÓN EUROPEA ES UN SERVICIO EXPRÉS (PERMITE 3-5 DÍAS LABORABLES). TRATAMOS DE ENVIAR TODOS LOS BIENES DESDE NUESTRO ALMACÉN EL MISMO DÍA SIEMPRE QUE EL PEDIDO SE HAYA RECIBIDO ANTES DE LAS 13 H. TRATAMOS DE ENTREGAR LOS BIENES EN LOS PLAZOS ESTIMADOS, SIN EMBARGO, PUEDE HABER RETRASOS INEVITABLES DEBIDO A FACTORES IMPREVISTOS. GETNORD.COMNO SE HARÁ RESPONSABLE DE NINGÚN RETRASO O FALLO EN LA ENTREGA DE LOS BIENES EN LOS PLAZOS ESTIMADOS.</p>
                <p>6.7 CONSULTA NUESTRA PÁGINA DE ENTREGAS PARA CONOCER LOS GASTOS DE ENVÍO ACTUALES.</p>
                <p>6.8 ASUMIRÁS EL RIESGO DE PÉRDIDA O DE DAÑO DE LOS BIENES EN EL MOMENTO EN QUE SE ENTREGUEN LOS BIENES.</p>
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>7. 7.	SEGUIMIENTO DE TU PEDIDO</h1>
            </div>
            <div class="text-container">
                <p>7.1 UNA VEZ QUE SE HAYAN ENTREGADO TUS BIENES PARA SU ENVÍO RECIBIRÁS UN CORREO ELECTRÓNICO DE CONFIRMACIÓN QUE TE INFORMARÁ DE QUE TUS BIENES ESTÁN DE CAMINO. EL CORREO ELECTRÓNICO TAMBIÉN INCLUIRÁ LOS DETALLES DE CÓMO PUEDES SEGUIR TU PEDIDO CON NUESTRO TRANSPORTISTA ELEGIDO.</p>
                <p>7.2 SI TIENES ALGUNA PREGUNTA RESPECTO A LA RECEPCIÓN DE TU PEDIDO PONTE EN CONTACTO CON NUESTRO EQUIPO DE ATENCIÓN AL SUPPORT@GETNORD.COM</p>
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>8. 	POLÍTICA DE DEVOLUCIÓN DE BIENES</h1>
            </div>
            <div class="text-container">
                <p>ESPERAMOS QUE ESTÉS SATISFECHO CON LOS BIENES QUE HAYAS COMPRADO EN NUESTRA PÁGINA WEB.</p>
                <p>8.1 CON SUJECIÓN A LA DISPOSICIÓN 8.2, SI DESEAS DEVOLVER O CAMBIAR CUALQUIER BIEN:</p>
                <ul>
                    <li>8.1.1 CON RESPECTO AL CUAL HAYAS ENCONTRADO UN DEFECTO EN UN AÑO SIGUIENTE A LA ENTREGA. CON SUJECIÓN A LA CONFIRMACIÓN DEL DEFECTO, TE DEVOLVEREMOS EL DINERO COBRADO Y CUALQUIER GASTO INCURRIDO EN LA DEVOLUCIÓN DEL PRODUCTO CONSIDERADO COMO DEFECTUOSO.</li>
                    <li>8.1.2 PODRÁS HACERLO POR CUALQUIER MOTIVO EN UN PLAZO DE 14 DÍAS DESDE LA FECHA DEL ENVÍO. TE DEVOLVEREMOS EL PRECIO DEL PRODUCTO, SIEMPRE QUE SE ENCUENTRE EN BUENAS CONDICIONES PARA SER VENDIDO Y DENTRO DE SU EMBALAJE ORIGINAL Y SIN DESPERFECTOS. LOS GASTOS DE ENTREGA NO SON REEMBOLSABLES Y SALVO QUE LO ACORDEMOS DE OTRO MODO, DEBERÁS PAGAR DICHOS GASTOS DE DEVOLUCIÓN DE LOS BIENES.
                    ESTO NO AFECTA A TUS DERECHOS LEGALES.
                    </li>
                </ul>
                <p>8.2 EN VIRTUD DE LAS REGULACIONES DE VENTA A DISTANCIA TIENES EL DERECHO LEGAL A CANCELAR TU PEDIDO EN LOS 14 DÍAS LABORABLES SIGUIENTES A LA RECEPCIÓN DE LOS BIENES.</p>
                <p>8.3 SI QUIERES DEVOLVER ALGÚN BIEN PUEDES HACERLO MEDIANTE NUESTRO PROCESO DE DEVOLUCIÓN. EL VALOR DE LOS BIENES DEVUELTOS EN EL MOMENTO DE LA COMPRA SE DEVOLVERÁ POR COMPLETO A LA MISMA TARJETA QUE HAYAS UTILIZADO PARA LA COMPRA DE LOS MISMOS. SI DESEAS RECIBIR DE NUEVO LOS BIENES, PÍDELOS DE LA FORMA HABITUAL A TRAVÉS DE NUESTRA PÁGINA WEB. SENTIMOS NO PODER ATENDER NINGÚN CAMBIO DE BIENES A TRAVÉS DE NUESTRO PROCESO DE DEVOLUCIÓN.</p>
                <p>8.4 LOS PRODUCTOS COMPRADOS ORIGINALMENTE EN UNA DE LAS TIENDAS GETNORD SOLO SE PUEDEN CAMBIAR O DEVOLVER EN UNA TIENDA FÍSICA GETNORD Y NO PODRÁN DEVOLVERSE USANDO EL PROCESO DE DEVOLUCIÓN EN LÍNEA.</p>
                <ul>
                    <li>8.4.1 CUALQUIER PRODUCTO COMPRADO EN LÍNEA O POR TELÉFONO NO PODRÁ DEVOLVERSE EN NINGUNA DE NUESTRAS TIENDAS FÍSICAS GETNORD.</li>
                </ul>
                <p>8.5 PARA DEVOLVER CUALQUIER BIEN A TRAVÉS DEL PROCESO DE DEVOLUCIÓN, VISITA GETNORD.COM Y SIGUE EL ENLACE HASTA NUESTRA PÁGINA DE «DEVOLUCIÓN». SE RECOMIENDA A LOS CLIENTES EUROPEOS USAR EL SERVICIO DE CORREO CERTIFICADO; GETNORD NO SE HACE RESPONSABLE DE LAS DEVOLUCIONES HASTA EL MOMENTO DE SU RECEPCIÓN.</p>
                <p>8.6 PARA NUESTROS REGISTROS, TE PEDIREMOS QUE INDIQUES LA RAZÓN DE LA DEVOLUCIÓN Y, ADEMÁS, TENDRÁS QUE DEVOLVER ESTE FORMULARIO JUNTO CON LOS BIENES PARA QUE PODAMOS IDENTIFICARLOS TRAS SU RECEPCIÓN Y PROCESAR TU DEVOLUCIÓN INMEDIATAMENTE. UNA VEZ QUE HAYAMOS RECIBIDO Y COMPROBADO LOS BIENES DEVUELTOS EN NUESTRO CENTRO DE DEVOLUCIÓN, ABONAREMOS AUTOMÁTICAMENTE EN TU TARJETA EL VALOR DE LOS BIENES DEVUELTOS.</p>
                <p>8.7 SI TIENES ALGUNA DUDA SOBRE LA DEVOLUCIÓN Y TE GUSTARÍA PONERTE EN CONTACTO CON NOSOTROS, ENVÍANOS UN CORREO ELECTRÓNICO A SUPPORT@GETNORD.COM</p>
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>9. 9.	GARANTÍAS Y RESPONSABILIDADES</h1>
            </div>
            <div class="text-container">
                <p>9.1 NINGUNO DE LOS PRESENTES TÉRMINOS EXCLUYE O LIMITA LA RESPONSABILIDAD POR MUERTE O DAÑO PERSONAL CAUSADO POR NEGLIGENCIA O FALSA DECLARACIÓN.</p>
                <p>9.2 </p>
                <p>9.3 9.3 GETNORD.COMHARÁ TODO LO QUE PUEDA PARA ENTREGAR LOS BIENES EN LOS 30 DÍAS SIGUIENTES A LA FECHA DE TU PEDIDO Y PARA CUMPLIR CON NUESTRAS OBLIGACIONES EN VIRTUD DE LOS PRESENTES TÉRMINOS, PERO NO NOS HAREMOS RESPONSABLES DE LOS RETRASOS O FALLOS DEBIDOS A CLIMATOLOGÍA ADVERSA, RETRASOS POR TRÁFICO DENSO, AVERÍAS MECÁNICAS U OTRAS CIRCUNSTANCIAS FUERA DE NUESTRO CONTROL.</p>
                <p>9.4 LA INFORMACIÓN CONTENIDA EN EL MATERIAL DE ESTA PÁGINA WEB TIENE ÚNICAMENTE FINES INFORMATIVOS. GETNORD.COM, AL PERMITIR EL USO DE LA PRESENTE PÁGINA WEB, NO SE CONSIDERA COMO PROVEEDOR DE NINGÚN ASESORAMIENTO LEGAL, FINANCIERO O DE OTRO TIPO. TAMPOCO HACE NINGUNA RECOMENDACIÓN O APROBACIÓN PARA NINGUNA INVERSIÓN, ASESORÍA U OTRO SERVICIO O PRODUCTO O CUALQUIER MATERIAL ENVIADO POR TERCEROS O VINCULADO CON ESTA PÁGINA WEB. EL MATERIAL DE ESTA PÁGINA WEB NO CONSTITUYE UN ASESORAMIENTO Y NO DEBERÍA CONFIARSE EN NINGÚN MATERIAL DE ESTA PÁGINA WEB PARA TOMAR (O DEJAR DE TOMAR) UNA DECISIÓN O PARA TOMAR (O DEJAR DE TOMAR) CUALQUIER MEDIDA.</p>
                <p>9.5 LOS BIENES SE VENDEN DE ACUERDO CON LAS ESPECIFICACIONES DEL FABRICANTE, CON SUJECIÓN A CUALQUIER RESTRICCIÓN O REPRESENTACIÓN QUE FIGURE EN LA PÁGINA WEB. GETNORD.COMNO PROMETE NI GARANTIZA NADA MÁS RESPECTO A LOS BIENES.</p>
                <p>9.6 GETNORD.COMHARÁ TODO LO POSIBLE PARA QUE LA PÁGINA ESTÉ DISPONIBLE, PERO GETNORD.COMNO PUEDE GARANTIZAR QUE LA PÁGINA WEB ESTÉ SIEMPRE DISPONIBLE, SEA FIABLE Y ESTÉ LIBRE DE ERRORES TÉCNICOS Y TIPOGRÁFICOS O DE CUALQUIER OTRO TIPO. ASIMISMO, A MENUDO REVISAMOS EL CONTENIDO DE LA PÁGINA WEB PARA QUE ESTÉ ACTUALIZADA PERO NO PODEMOS GARANTIZAR QUE SIEMPRE LO ESTÉ. GETNORD.COMNO PROMETE NI GARANTIZA NADA MÁS RESPECTO A LA PÁGINA WEB.</p>
                <p>9.7 ESTA PÁGINA WEB CONTIENE MATERIAL ENVIADO Y CREADO POR TERCEROS. CUANDO ASÍ SEA, TE INFORMAREMOS AL RESPECTO. NO HEMOS PODIDO COMPROBAR LA PRECISIÓN DE DICHOS MATERIALES ASÍ QUE TENDRÁS QUE CONFIRMAR SU PRECISIÓN CON EL TERCERO CORRESPONDIENTE.</p>
                <p>9.8 ESTA PÁGINA WEB TAMBIÉN CONTIENE ENLACES A OTRAS PÁGINAS WEB Y RECURSOS QUE NO ESTÁN BAJO NUESTRO CONTROL Y QUE NO MANTIENE GETNORD.COM. GETNORD.COMNO TIENE NINGÚN CONTROL SOBRE DICHAS PÁGINAS WEB Y RECURSOS. GETNORD.COMFACILITA ESOS ENLACES PARA TU COMODIDAD ÚNICAMENTE PERO NO RESPALDA NECESARIAMENTE EL MATERIAL DE DICHAS PÁGINAS WEB. TU VISITA A CUALQUIERA DE ESAS PÁGINAS WEB EXTERNAS A TRAVÉS DE LOS ENLACES DE ESTA WEB SERÁ POR TU CUENTA Y RIESGO. CUANDO PUEDAS HACER TRANSACCIONES A TRAVÉS DE CUALQUIER PÁGINA WEB ENLAZADA CON UN TERCERO, DICHAS TRANSACCIONES SE REALIZARÁN (Y CUALQUIER DERECHO Y OBLIGACIÓN DERIVADOS DE ELLAS) ÚNICAMENTE ENTRE EL TERCERO Y TÚ. POR TANTO, DEBERÁS ASEGURARTE DE HABER LEÍDO DETENIDAMENTE LOS TÉRMINOS Y CONDICIONES DE ACCESO Y USO A DICHAS PÁGINAS WEB Y RECURSOS Y, SI SUFRES ALGUNA PÉRDIDA COMO RESULTADO DEL ACCESO O EL USO A LAS PÁGINAS WEB O LOS RECURSOS DE ESOS TERCEROS, DEBERÁS RECLAMARLES A ELLOS Y NO A NOSOTROS.</p>
                <p>9.9 SALVO ESPECIFICACIÓN EN CONTRARIO, LOS MATERIALES DE ESTA PÁGINA WEB ESTÁN DIRIGIDOS ÚNICAMENTE A AQUELLOS QUE VISITEN LA PÁGINA WEB DESDE LITUANIA. GETNORD.COMNO DECLARA QUE TODOS LOS PRODUCTOS O SERVICIOS MENCIONADOS EN LOS MATERIALES DE ESTA PÁGINA WEB SEAN ADECUADOS PARA SU USO O ESTÉN DISPONIBLES EN OTRAS UBICACIONES. AQUELLOS QUE ELIJAN ACCEDER A ESTA PÁGINA WEB DESDE OTRAS UBICACIONES SERÁN RESPONSABLES DE CUMPLIR LAS LEYES LOCALES SI, Y EN LA MEDIDA EN QUE DICHAS LEYES LOCALES, SON APLICABLES.</p>
                <p>9.10 TOMAREMOS TODAS LAS PRECAUCIONES RAZONABLES PARA CONSERVAR LOS DATOS DE TU PEDIDO Y DEL PAGO SEGURO, PERO, SALVO QUE SEAMOS NEGLIGENTES, NO ASUMIREMOS NINGUNA RESPONSABILIDAD POR CUALQUIER PÉRDIDA CAUSADA COMO RESULTADO DE UN ACCESO NO AUTORIZADO A LA INFORMACIÓN PROPORCIONADA POR TI.</p>
                <p>9.11 EN CASO DE QUE TÚ O NOSOTROS INCUMPLAMOS LAS DISPOSICIONES DE LOS PRESENTES TÉRMINOS, NINGUNO DE LOS DOS SERÁ RESPONSABLE DE LAS PÉRDIDAS QUE SUFRA EL OTRO COMO RESULTADO DE ELLO, SALVO AQUELLAS PÉRDIDAS QUE SEAN UNA CONSECUENCIA PREVISIBLE DEL INCUMPLIMIENTO. LAS PÉRDIDAS SERÁN PREVISIBLES CUANDO PODRÍAN HABER SIDO PREVISTAS POR AMBAS PARTES EN EL MOMENTO EN QUE HICISTE EL PEDIDO.</p>
                <p>9.12 LA RESPONSABILIDAD POR CUALQUIER PÉRDIDA O DAÑO DIRECTO QUE SURJA DEL CONTRATO O EN RELACIÓN CON ÉL SE LIMITARÁ AL VALOR DEL MISMO.</p>
                <p>9.13 GETNORD.COMNO SERÁ RESPONSABLE RESPECTO AL COMPRADOR POR NINGÚN LUCRO CESANTE INDIRECTO, PÉRDIDA COMERCIAL, DETERIORO DEL VALOR DE LA MARCA, DAÑO INDIRECTO O CUALQUIER RECLAMACIÓN DE COMPENSACIÓN INDIRECTA DE NINGÚN TIPO QUE SURJA DEL CONTRATO O EN RELACIÓN CON ÉL</p>
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>10. 10.	PROPIEDAD INTELECTUAL</h1>
            </div>
            <div class="text-container">
                <p>10.1 SALVO ESPECIFICACIÓN EN CONTRARIO, LOS DERECHOS DE AUTOR DEL CONTENIDO DE TODAS LAS PÁGINAS DE ESTA PÁGINA WEB SON PROPIEDAD O SE ENCUENTRAN BAJO LICENCIA DE GETNORD.COM. </p>
                <p>10.2 TODAS LAS MARCAS COMERCIALES, MARCAS DE SERVICIO Y NOMBRES COMERCIALES DE REDLAINASLES O MARCAS COMERCIALES REGISTRADAS DE REDLAINAS O SUS FILIALES Y LICENCIATARIOS TERCEROS, INCLUIDO, ENTRE OTROS: GETNORD, ONYX, LYNX, WALRUS Y LAS CARACTERÍSTICAS DE LA IMAGEN COMERCIAL DE LOS PRODUCTOS QUE INCLUYEN: LOS GRÁFICOS, LOGOTIPOS, ENCABEZADOS, ICONOS DE LOS BOTONES, SCRIPTS Y NOMBRES DE SERVICIOS DE LA PÁGINAS WEB SON LAS MARCAS COMERCIALES O LA IMAGEN COMERCIAL DE GETNORD.COM. LAS MARCAS COMERCIALES Y LA IMAGEN COMERCIAL DE GETNORD NO PODRÁN USARSE EN RELACIÓN CON NINGÚN PRODUCTO O SERVICIO QUE NO SEA GETNORD.COM, DE NINGÚN MODO QUE PUEDA CREAR CONFUSIÓN EN LOS CLIENTES NI DE NINGUNA MANERA QUE DENIGRE O DESACREDITE A GETNORD.COM. TODAS LAS DEMÁS MARCAS COMERCIALES QUE NO SEAN PROPIEDAD DE GETNORD.COMY QUE APAREZCAN EN ESTA PÁGINA WEB SON PROPIEDAD DE SUS RESPECTIVOS PROPIETARIOS, QUE PUEDEN O NO ESTAR AFILIADOS, RELACIONADOS O PATROCINADOS POR GETNORD.COM.</p>
                <p>10.3 SALVO QUE SE ESPECIFIQUE EN LA PRESENTE DISPOSICIÓN 10.3, EL CONTENIDO DE ESTA PÁGINA WEB NO PODRÁ MODIFICARSE, COPIARSE, REPRODUCIRSE, DISTRIBUIRSE, VOLVER A PUBLICARSE, DESCARGARSE, VISUALIZARSE, ENVIARSE, VOLVER A ENVIARSE O TRANSMITIRSE DE NINGÚN MODO O POR NINGÚN MEDIO SIN EL PERMISO EXPRESO PREVIO POR ESCRITO DE GETNORD.COM. NO PODRÁS DISTRIBUIR, VISUALIZAR O COPIAR NINGÚN CONTENIDO DE LAS PÁGINAS CONTENIDAS EN ESTA PÁGINAS WEB A TERCEROS, INCLUIDOS, ENTRE OTROS, EL ALMACENAMIENTO EN CACHÉ DE NINGÚN MATERIAL DE LA PRESENTE PÁGINA WEB PARA EL ACCESO DE TERCEROS NI LA REPLICACIÓN DE NINGÚN MATERIAL DE LA PRESENTE PÁGINA WEB. PODRÁS IMPRIMIR EL CONTENIDO DE UNA PÁGINA INDIVIDUAL DE ESTA PÁGINA WEB PARA FINES DE USO PRIVADO Y PERSONAL, PERO NO COMERCIALES.</p>
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>11.	QUEJAS</h1>
            </div>
            <div class="text-container">
                <p>11.1 NUESTRO OBJETIVO ES TRATAR TODAS LAS QUEJAS DE LA MANERA MÁS EFECTIVA POSIBLE. NUESTRO PROCEDIMIENTO PARA LA TRAMITACIÓN DE LAS QUEJAS ESTÁ DISEÑADO PARA QUE SEA JUSTO, CONFIDENCIAL, FÁCIL DE USAR, RÁPIDO E INFORMATIVO. SI DESEAS PRESENTAR UNA QUEJA, PONTE EN CONTACTO CON NOSOTROS:</p>
                <ul>
                    <li>11.1.1 POR CORREO ELECTRÓNICO EN SUPPORT@GETNORD.COM</li>
                    <li>11.1.2 POR CORREO, HAZNOS LLEGAR TU QUEJA A: <br> GETNORD E-COMMERCE TEAM
                    <br>DEPARTAMENTO DE ATENCIÓN AL CLIENTE
                    <br>REDLAINAS
                    <br>
                    VERSLO 6, KUMPIAI
                    <br>KAUNAS 54311
                    <br>LITUANIA</li>
                </ul>
                <p>DANOS TODOS LOS DETALLES DE LA NATURALEZA DE TU QUEJA, INCLUIDOS LOS PRODUCTOS COMPRADOS, TU NÚMERO DE PEDIDO, TU NOMBRE, DIRECCIÓN, NÚMERO DE TELÉFONO DURANTE EL DÍA, DIRECCIÓN DE CORREO ELECTRÓNICO Y CUALQUIER OTRA INFORMACIÓN QUE CREAS QUE NOS PUEDE AYUDAR A RESOLVER TU PROBLEMA LO MÁS RÁPIDO POSIBLE.</p>
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>12. 12.	VARIOS</h1>
            </div>
            <div class="text-container">
                <p>12.1 UNA PERSONA QUE NO FORME PARTE DEL PRESENTE CONTRATO NO TENDRÁ DERECHO EN VIRTUD DE LA LEY DE CONTRATOS (DERECHOS DE TERCEROS) A IMPONER NINGÚN TÉRMINO DEL PRESENTE CONTRATO. ESTA CLÁUSULA NO AFECTA AL DERECHO O RECURSO DE UNA PERSONA QUE EXISTA O ESTÉ DISPONIBLE DE OTRO MODO QUE NO SEA SEGÚN DICHA LEY.</p>
                <p>12.2 CADA CONTRATO SE REGIRÁ Y SE INTERPRETARÁ EN TODOS SUS ASPECTOS DE ACUERDO CON LA LEGISLACIÓN INGLESA Y LAS PARTES SE SOMETEN POR LA PRESENTE AL FUERO EXCLUSIVO DE LOS TRIBUNALES DE SU DOMICILIO. DONDE LAS AUTORIDADES REGULADORAS NACIONALES TENGAN JURISDICCIÓN SOBRE EL CONTENIDO DE ESTA PÁGINA WEB, GETNORD.COMHA PROCURADO GARANTIZAR EL CUMPLIMIENTO DE LOS REQUISITOS DE DICHO ÓRGANO REGULADOR. NO OBSTANTE, NO SE PODRÁ ACCEDER A ALGUNAS DE LAS INFORMACIONES DE LAS PÁGINAS CONTENIDAS EN ESTA PÁGINA WEB DESDE DETERMINADAS JURISDICCIONES Y NO SE DA REPRESENTACIÓN NI GARANTÍA ALGUNA SOBRE SI DICHA INFORMACIÓN DISPONIBLE EN ESTA PÁGINA WEB CUMPLE CON EL RÉGIMEN REGULADOR DE PAÍSES DESDE LOS CUALES NO SE PUEDA ACCEDER A LA MISMA.</p>
            </div>
        </section>
        
        <section class="theme">
            <div class="section-title">
                <h1>13.	PROTECCIÓN DE DATOS Y POLÍTICA DE PRIVACIDAD</h1>
            </div>
            <div class="text-container">
                <p>13.1 We respect the privacy of all individuals who use this Website. This privacy policy explains what information we gather from you, how we use it and how you may control our use of your personal information. We will ensure that all personal information supplied is held securely, in accordance with the Data Protection Act 1998. This Website contains links to other websites. Please be aware that we are not responsible for the privacy practices of such other websites. We encourage our users to be aware when they leave our Website and to read the privacy statements of each and every website that collects personally identifiable information. This privacy statement applies solely to information collected by this Website.</p>
                <p>13.2 GETNORD.COMES EL ÚNICO RESPONSABLE DE LA INFORMACIÓN RECOPILADA EN ESTA PÁGINA WEB. NO VENDEREMOS, COMPARTIREMOS O ALQUILAREMOS ESTA INFORMACIÓN A OTROS DE FORMA DIFERENTE A LA QUE SE DIVULGA EN LA PRESENTE DECLARACIÓN. GETNORD.COMRECOPILA INFORMACIÓN DE NUESTROS USUARIOS EN VARIOS PUNTOS DIFERENTES EN NUESTRA PÁGINA WEB A MENOS QUE NO ESTEMOS LEGALMENTE OBLIGADOS O SE NOS EXIJA NO HACERLO, O SI CREEMOS QUE DICHA ACCIÓN ES NECESARIA PARA PROTEGER Y/O DEFENDER NUESTROS DERECHOS, PROPIEDAD O SEGURIDAD PERSONAL Y LA DE LOS USUARIOS DE ESTA PÁGINA WEB. TU PRIVACIDAD ES DE SUMA IMPORTANCIA PARA NOSOTROS Y NOS COMPROMETEMOS A NO DIFUNDIR TUS DATOS PERSONALES A NINGUNA EMPRESA EXTERNA PARA FINES DE PUBLICIDAD O MARKETING SIN TU AUTORIZACIÓN EXPRESA.</p>
                <p>13.3 INFORMACIÓN RECOPILADA

                <br> PODEMOS RECOPILAR LOS SIGUIENTES DATOS DE TI:</p>
                <ul>
                    <li>13.3.1 INFORMACIÓN QUE NOS PROPORCIONES AL CONFIGURAR O MODIFICAR UNA CUENTA CON NOSOTROS. POR EJEMPLO: TU NOMBRE, DIRECCIÓN, VARIAS DIRECCIONES DE ENTREGA, DIRECCIÓN DE CORREO ELECTRÓNICO, NÚMEROS DE TELÉFONO DE CONTACTO, CONTRASEÑA, PREGUNTAS Y RESPUESTAS PARA RECUPERAR LA CONTRASEÑA Y DATOS DE LA TARJETA QUE SE PODRÁN UTILIZAR CUANDO HAGAS PEDIDOS POSTERIORES;</li>
                    <li>13.3.2 INFORMACIÓN QUE NOS PROPORCIONES CUANDO HAGAS UN PEDIDO EN LÍNEA O AL CUMPLIMENTAR CUALQUIER FORMULARIO DE REGISTRO EN LÍNEA QUE PONGAMOS A DISPOSICIÓN EN NUESTRA PÁGINA WEB. POR EJEMPLO, TU NOMBRE, DIRECCIÓN DE CORREO ELECTRÓNICO, DIRECCIÓN DE PAGO Y DATOS DE LA TARJETA QUE SEAN ESENCIALES PARA PROCESAR UN PEDIDO;</li>
                    <li>13.3.3 LA INFORMACIÓN QUE NOS DIVULGUES VOLUNTARIAMENTE POR CORREO ELECTRÓNICO U OTROS MEDIOS;</li>
                    <li>13.3.4 INFORMACIÓN SOBRE TU ORDENADOR, INCLUIDO, CUANDO PROCEDA, TU DIRECCIÓN IP, TU SISTEMA OPERATIVO Y EL TIPO DE NAVEGADOR;</li>
                    <li>13.3.5 INFORMACIÓN SOBRE TU USO DE INTERNET OBTENIDA MEDIANTE UN ARCHIVO DE COOKIE QUE SE ALMACENA EN EL DISCO DURO DE TU ORDENADOR. PARA MÁS INFORMACIÓN, CONSULTA NUESTRA POLÍTICA DE «PRIVACIDAD Y COOKIES».</li>
                </ul>
                <p>13.4 ENCUESTAS Y CONCURSOS
                    OCASIONALMENTE NUESTRA PÁGINA WEB SOLICITARÁ INFORMACIÓN DE SUS USUARIOS A TRAVÉS DE ENCUESTAS Y CONCURSOS. LA PARTICIPACIÓN EN ESAS ENCUESTAS O CONCURSOS ES TOTALMENTE VOLUNTARIA Y EL USUARIO TENDRÁ LA OPCIÓN DE REVELAR O NO ESA INFORMACIÓN. LA INFORMACIÓN SOLICITADA PUEDE INCLUIR INFORMACIÓN DE CONTACTO (COMO SU NOMBRE Y DIRECCIÓN DE ENVÍO) E INFORMACIÓN DEMOGRÁFICA (COMO SU CÓDIGO POSTAL O FRANJA DE EDAD). LA INFORMACIÓN DE CONTACTO SE UTILIZARÁ PARA NOTIFICAR A LOS GANADORES Y OTORGAR PREMIOS. LA INFORMACIÓN DE LAS ENCUESTAS SE UTILIZARÁ PARA FINES DE SEGUIMIENTO O MEJORA SOBRE EL USO Y LA SATISFACCIÓN DE ESTA PÁGINA WEB.
                    </p>
                <p>13.5 USO DE LA INFORMACIÓN
                <br>USAREMOS LA INFORMACIÓN QUE TENGAMOS SOBRE TI DE LAS SIGUIENTES MANERAS:</p>
                <ul>
                    <li>13.5.1 PARA FINES DE ANÁLISIS INTERNOS DENTRO DE NUESTRO GRUPO DE 1EMPRESAS;</li>
                    <li>13.5.2 PARA CREAR Y MANTENER TU CUENTA CON NOSOTROS;</li>
                    <li>13.5.3 PARA CUMPLIR CON NUESTRAS OBLIGACIONES TRAS TU PEDIDO TAL COMO SE ESTABLECE EN NUESTROS TÉRMINOS Y CONDICIONES DE VENTA;</li>
                    <li>13.5.4 PARA PROPORCIONAR ACTUALIZACIONES Y BOLETINES DE NOTICIAS ELECTRÓNICOS PERIÓDICOS RESPECTO A NUESTROS PRODUCTOS Y SERVICIOS;</li>
                    <li>13.5.5 PARA GARANTIZAR QUE EL CONTENIDO DE NUESTRA PÁGINA WEB SE PRESENTA DE LA MANERA MÁS EFECTIVA PARA TI Y PARA TU ORDENADOR;</li>
                    <li>13.5.6 PARA ADMINISTRAR Y EJECUTAR NUESTRAS OBLIGACIONES EN RELACIÓN CON LOS BIENES Y/O SERVICIOS QUE HAYAMOS ACEPTADO SUMINISTRARTE. POR EJEMPLO, PODEMOS USAR UNA COMPAÑÍA DE TRANSPORTE EXTERNA PARA ENTREGAR PEDIDOS Y UNA COMPAÑÍA QUE PROCESE LAS TARJETAS DE CRÉDITO PARA QUE TE COBRE LOS BIENES Y LOS SERVICIOS. ESAS EMPRESAS NO RETENDRÁN, COMPARTIRÁN, ALMACENARÁN NI USARÁN INFORMACIÓN PERSONALMENTE IDENTIFICABLE PARA NINGÚN FIN SECUNDARIO;</li>
                    <li>13.5.7 PARA PROPORCIONARTE INFORMACIÓN Y SERVICIOS, INCLUIDA CUALQUIER PUBLICIDAD QUE NOS HAYAS PEDIDO, Y PARA RESPONDER A LAS DUDAS QUE NOS HAYAS ENVIADO;</li>
                    <li>13.5.8 PARA PERMITIRTE QUE PARTICIPES EN FUNCIONES INTERACTIVAS DE NUESTRA PÁGINA WEB CUANDO ELIJAS HACERLO;</li>
                    <li>13.5.9 PARA NOTIFICARTE SOBRE LOS CAMBIOS EN NUESTRA PÁGINA WEB;</li>
                    <li>13.5.10 PARA OFRECERTE LOS PRODUCTOS Y LOS SERVICIOS QUE PRESTAMOS TANTO NOSOTROS COMO CUALQUIER OTRA EMPRESA DENTRO DEL MISMO GRUPO DE EMPRESAS. DEBERÁS TENER EN CUENTA QUE, SI LA POLICÍA O CUALQUIER OTRA AUTORIDAD REGULADORA O GUBERNAMENTAL QUE INVESTIGUE SUPUESTAS ACTIVIDADES ILEGALES NOS EXIGE QUE PROPORCIONEMOS EN RELACIÓN CON LA INFORMACIÓN PERSONAL Y/O INFORMACIÓN SOBRE EL USUARIO, TENDREMOS DERECHO A HACERLO.</li>
                </ul>
                <p>13.6 CORRECCIÓN/ACTUALIZACIÓN DE LA INFORMACIÓN PERSONAL
                <br>SI CAMBIAS LA INFORMACIÓN PERSONALMENTE IDENTIFICABLE DE UN USUARIO (COMO SU CÓDIGO POSTAL) O SI UN USUARIO DESEA PRESCINDIR DE NUESTRO SERVICIO, TRATAREMOS DE OFRECERTE UNA MANERA DE CORREGIR, ACTUALIZAR O ELIMINAR LOS DATOS PERSONALES DEL USUARIO SUMINISTRADOS. ESTO SE PUEDE HACER FÁCILMENTE ENVIANDO UN CORREO ELECTRÓNICO A ATENCIÓN AL CLIENTE A SUPPORT@GETNORD.COM.</p>
                <p>13.7 TERCEROS QUE PODRÍAN USAR LA INFORMACIÓN
                <br>PODEMOS PASAR TUS DATOS A TERCEROS CON EL FIN DE PROCESAR LOS PAGOS CON TARJETA DE CRÉDITO O DE DÉBITO Y PROCESAR TUS PEDIDOS. TAMBIÉN PODEMOS USAR TUS DATOS O PERMITIR QUE TERCEROS SELECCIONADOS USEN TUS DATOS PARA DARTE INFORMACIÓN SOBRE PRODUCTOS O SERVICIOS QUE PUEDAN SER DE INTERÉS O BENEFICIOSOS PARA TI O PARA REALIZAR ESTUDIOS DE MERCADO.</p>
                <p>13.8 TU CONSENTIMIENTO
                <br>DURANTE EL PEDIDO Y/O EL PROCESO DE REGISTRO EN LÍNEA TENDRÁS LA POSIBILIDAD DE RETIRAR TU CONSENTIMIENTO A:</p>
                <ul>
                    <li>(A) QUE TE CONTACTEMOS PARA OFRECERTE BIENES Y SERVICIOS PROMOCIONALES; Y/O</li>
                    <li>(B) QUE PASEMOS INFORMACIÓN SOBRE TI A TERCEROS QUE TE PUEDAN OFRECER BIENES O SERVICIOS QUE CREAN QUE TE PUEDEN INTERESAR.</li>
                </ul>
                <p>PUEDES CAMBIAR TU AUTORIZACIÓN A LOS PUNTOS ANTERIORES EDITANDO TU PERFIL DE CUENTA EN GETNORD.COM. CUANDO RETIRES TU AUTORIZACIÓN PARA USAR TU INFORMACIÓN PERSONAL DEJAREMOS DE USARLA TAN PRONTO COMO SEA POSIBLE. SI DESEAS DEJAR DE RECIBIR OFERTAS PROMOCIONALES DE CUALQUIER TERCERO AL QUE LE HAYAMOS DIVULGADO INFORMACIÓN SOBRE TI DE ACUERDO CON LA PRESENTE POLÍTICA DE PRIVACIDAD, TENDRÁS QUE PONERTE EN CONTACTO CON ESA EMPRESA DIRECTAMENTE USANDO EL PROCEDIMIENTO ELEGIDO POR DICHA EMPRESA PARA SUS COMUNICACIONES CONTIGO.</p>
                <p>13.9 COOKIES</p>
                <ul>
                    <li>13.9.1 USAMOS «COOKIES» Y OBTENEMOS ALGUNOS TIPOS DE INFORMACIÓN CUANDO TU NAVEGADOR WEB ACCEDE A NUESTRA PÁGINA WEB. AUNQUE NO PODAMOS OFRECERTE UNA EXPERIENCIA PERSONALIZADA EN NUESTRA PÁGINA WEB SI NO PODEMOS RECONOCERTE, QUEREMOS QUE SEAS CONSCIENTE DE QUE ESA HERRAMIENTA EXISTE.</li>
                    <li>13.9.2 TENDRÁS QUE ACEPTAR LAS COOKIES EN TU NAVEGADOR PARA USAR LAS FUNCIONES DE NUESTRA PÁGINA WEB. TODA LA INFORMACIÓN ALMACENADA EN LAS COOKIES ES PARA USO EXCLUSIVO DE GETNORD.COM, LA INFORMACIÓN ESTÁ CIFRADA Y NO SERÁ COMPARTIDA CON NINGÚN TERCERO. LAS COOKIES TE PERMITIRÁN APROVECHAR PLENAMENTE LAS FUNCIONES MÁS ÚTILES DE NUESTRA PÁGINA WEB Y TE RECOMENDAMOS QUE LAS DEJES ACTIVADAS. SI DEJAS LAS COOKIES ACTIVADAS, ASEGÚRATE DE CERRAR SESIÓN SI ESTÁS UTILIZANDO UN ORDENADOR COMPARTIDO.</li>
                </ul>
                <p>13.10 SEGURIDAD</p>
                <ul>
                    <li>13.10.1 EN GETNORD.COM, SOMOS CONSCIENTES DE LA IMPORTANCIA QUE TIENE ALMACENAR CUALQUIER INFORMACIÓN QUE NOS PROPORCIONES. NUESTRA WEB (GETNORD.COM) EN LA ACTUALIDAD UTILIZA UNA TECNOLOGÍA DE CIFRADO CON UNA CAPA DE SOCKETS SEGUROS DE ALTO NIVEL (SSL), EL SOFTWARE DE SEGURIDAD MÁS AVANZADO EN LA ACTUALIDAD DISPONIBLE PARA TRANSACCIONES EN LÍNEA. POR TANTO, PUEDES ESTAR SEGURO DE QUE NOS TOMAMOS MUY EN SERIO LA SEGURIDAD DE TU PAGO Y DE TUS DATOS PERSONALES. PODEMOS MODIFICAR ESTO EN EL FUTURO SI CREEMOS QUE PUEDES BENEFICIARTE DE UNA MAYOR SEGURIDAD USANDO NUESTRA PÁGINA WEB.</li>
                    <li>13.10.2 PUEDES SABER SI UNA PÁGINA WEB ES SEGURA PORQUE VERÁS QUE AL INICIO DE LA BARRA DE DIRECCIONES DE TU NAVEGADOR APARECERÁ «HTTPS» EN VEZ DE «HTTP» AL IGUAL QUE UN PEQUEÑO CANDADO.</li>
                    <li>13.10.3 AUNQUE EN LA ACTUALIDAD USEMOS EL CIFRADO SSL PARA PROTEGER LA INFORMACIÓN CONFIDENCIAL EN LÍNEA, TAMBIÉN PROTEGEMOS TU INFORMACIÓN FUERA DE LÍNEA. TODA TU INFORMACIÓN, NO SOLO LA INFORMACIÓN CONFIDENCIAL MENCIONADA ANTES, TIENE EL ACCESO RESTRINGIDO EN NUESTRAS OFICINAS. SOLO LOS EMPLEADOS QUE NECESITEN LA INFORMACIÓN PARA REALIZAR UN TRABAJO ESPECÍFICO (POR EJEMPLO, UN REPRESENTANTE DE ATENCIÓN AL CLIENTE) TENDRÁN DERECHO A ACCEDER A TU INFORMACIÓN PERSONAL. LOS SERVIDORES EN LOS QUE ALMACENAMOS TU INFORMACIÓN PERSONAL SE ENCUENTRAN ALOJADOS EN UN ENTORNO SEGURO.</li>
                </ul>
                <p>13.11 VERIFIED BY VISA Y MASTERCARD® SECURECODE™</p>
                <ul>
                    <li>13.11.1 PARA DARTE AÚN MÁS CONFIANZA EN LA COMPRA EN LÍNEA CON GETNORD.COM, HEMOS IMPLEMENTADO LOS SERVICIOS VERIFIED BY VISA Y MASTERCARD® SECURECODE™. ESTOS SERVICIOS MEJORAN LA SEGURIDAD DE LAS CUENTAS DE TUS TARJETAS DE CRÉDITO/DÉBITO EXISTENTES FRENTE A UN USO NO AUTORIZADO CUANDO COMPRES CON NOSOTROS.</li>
                    <li>13.11.2 PARA USAR ESE SERVICIO, PRIMERO DEBERÁS REGISTRARTE EN EL BANCO O EN LA ORGANIZACIÓN QUE HAYA EMITIDO TU TARJETA.
                    <br><a href="https://www.visa.co.uk/products/protection-benefits/verified-by-visa/" target="_blank">Visit the Verified by Visa website</a>
                    <br><a href="https://www.mastercard.co.uk/en-gb/consumers/features-benefits/securecode.html">Visit the Mastercard® SecureCode™ website</a></li>
                    <li>13.11.3 UNA VEZ QUE TE HAYAS REGISTRADO Y HAYAS CREADO TU PROPIA CONTRASEÑA PRIVADA CON EL EMISOR DE TU TARJETA, TE DIRIGIRÁN AUTOMÁTICAMENTE HACIA EL PAGO CUANDO SE PROCESE LA TARJETA PARA QUE PROPORCIONES LA CONTRASEÑA CADA VEZ QUE HAGAS UNA COMPRA.</li>
                    <li>13.11.4 RECUERDA: TU CONTRASEÑA DE VERIFIED BY VISA Y MASTERCARD® SECURECODE™ ESTÁ VINCULADA CON TUS TARJETAS DE CRÉDITO/DÉBITO Y NO CON LA CONTRASEÑA DE TU CUENTA DE CLIENTE DE GETNORD.COM. GETNORD.COMNO TIENE ACCESO A TU CONTRASEÑA DE VERIFIED BY VISA O MASTERCARD® SECURECODE™.</li>
                </ul>
                <p>13.12 PHISHING</p>
                <ul>
                    <li>13.12.1 PHISHING ES LA PRÁCTICA DE ENGAÑAR A ALGUIEN PARA QUE DÉ INFORMACIÓN CONFIDENCIAL. ALGUNOS EJEMPLOS INCLUYEN AFIRMAR FALSAMENTE SER UNA EMPRESA LEGÍTIMA CUANDO SE ENVÍA UN CORREO ELECTRÓNICO A UN USUARIO PARA INTENTAR QUE ESTE RESPONDA CON INFORMACIÓN PRIVADA QUE PUEDA USARSE PARA EL ROBO DE IDENTIDAD Y FRAUDE.</li>
                    <li>13.12.2 GETNORD.COMNO TE PEDIRÁ NUNCA QUE ENVÍES DATOS PERSONALES POR CORREO ELECTRÓNICO. SI RECIBES UN CORREO ELECTRÓNICO QUE AFIRME SER DE GETNORD.COM, Y QUE TE PIDA ESE TIPO DE INFORMACIÓN, NO CONTESTES A ÉL Y PONTE EN CONTACTO CON NOSOTROS DE INMEDIATO.</li>
                </ul>
                <p>13.13 QUEJAS</p>
                <p>SI CREES QUE GETNORD.COMNO SE ATIENE A SU POLÍTICA DE PRIVACIDAD PUBLICADA, PRIMERO DEBERÁS PONERTE EN CONTACTO CON EL DEPARTAMENTO DE ATENCIÓN AL CLIENTE EN SUPPORT@GETNORD.COM. TAMBIÉN PUEDES ESCRIBIRNOS A:</p>
                <ul>
                    <li>GETNORD</li>
                    <li>DEPARTAMENTO DE ATENCIÓN AL CLIENTE</li>
                    <li>REDLAINAS</li>
                    <li>VERSLO 6, KUMPIAI</li>
                    <li>KAUNAS 54311</li>
                    <li>LITUANIA</li>
                </ul>
                <p>LA LEGISLACIÓN EUROPEA EXIGE QUE TODAS LAS TIENDAS WEB INCLUYAN EL SIGUIENTE ENLACE A LA PLATAFORMA DE RESOLUCIÓN DE LITIGIOS DE LA COMISIÓN EUROPEA <a href="ec.europa.eu/consumers/odr/">http://ec.europa.eu/consumers/odr/.</a></p>
            </div>
        </section>
        
    </div>
</div>
@endsection