@extends('layouts.app')

@section('content')
<div class="page_content">
    <div class="main_container">
        <p class="p1"><strong><span class="s1">Prekių pirkimo – pardavimo GETNORD parduotuvėje internete taisyklės</span></strong></p>
<p class="p2"> </p>
<p class="p1"><strong><span class="s1">1. Bendrosios nuostatos</span></strong></p>
<p class="p1"><span class="s1">1.1. Šios prekių pirkimo – pardavimo taisyklės (toliau – „Taisyklės“) nustato bendrąsias naudojimosi GETNORD parduotuve internete www.getnord.com (toliau – „GETNORD parduotuvė“) sąlygas. Taisyklės yra taikomos, kai Pirkėjas renkasi, užsako ir perka GETNORD parduotuvėje siūlomas prekes ar bet kaip kitaip naudojasi GETNORD parduotuvės teikiamomis paslaugomis.</span></p>
<p class="p1"><span class="s1">1.2. GETNORD parduotuvė yra mažmeninės prekybos parduotuvė internete, orientuota į vartotojus, perkančius prekes asmeniniams, šeimos, namų ūkio poreikiams, nesusijusiems su verslu ar profesija, tenkinti.</span></p>
<p class="p1"><span class="s1">1.3. GETNORD parduotuvėje prekių prekybą organizuoja, vykdo ir su ja susijusias paslaugas Pirkėjui teikia UAB „Redlainas“, buveinės adresas: Verslo g. 6, Kumpiai 54311, Kauno r., juridinio asmens kodas 235983690, PVM mokėtojo kodas (toliau – „Pardavėjas“). GETNORD parduotuvėje parduodamos Pardavėjui nuosavybės teise priklausančios prekės. </span></p>
<p class="p1"><span class="s1">1.4. Pirkėju šiose Taisyklėse yra bet kuris asmuo, perkantis GETNORD parduotuvėje ar besinaudojantis kitomis GETNORD parduotuvės paslaugomis (toliau – „Pirkėjas“). Naudotis GETNORD parduotuve ir joje pirkti turi teisę (a) veiksnūs fiziniai asmenys, t. y. asmenys, sulaukę pilnametystės, kurių veiksnumas nėra apribotas teismo tvarka, ir (b) juridiniai asmenys, veikiantys per įgaliotus atstovus, užsiregistravę GETNORD parduotuvėje Taisyklėse nustatyta tvarka. </span></p>
<p class="p1"><span class="s1">1.5. Užsiregistruodamas arba pateikdamas užsakymą Pirkėjas besąlygiškai patvirtina, jog jis turi teisę pirkti GETNORD parduotuvėje.</span></p>
<p class="p1"><span class="s1">1.6. Kartu su Pirkėjo pateiktu prekių užsakymu šios Taisyklės tampa tarp Pirkėjo ir Pardavėjo sudaryta sutartimi ir yra abiem šalims privalomas teisinis dokumentas. Sutartis laikoma sudaryta, kai Pirkėjas suformuoja ir pateikia GETNORD parduotuvėje prekių užsakymą, Taisyklėse nustatyta tvarka ir terminais atlieka apmokėjimą (kai Pirkėjas yra pasirinkęs, kad už prekes atsiskaitys užsakymo metu) ir Pirkėjo nurodytu elektroniniu paštu Pardavėjas išsiunčia patvirtinimą, kad Pirkėjo užsakymas yra priimtas. Jei pirkėjas GETNORD parduotuvėje pasirenka atsiskaitymą už prekes jų pristatymo metu, sutartis laikoma sudaryta, kai Pirkėjas suformuoja ir pateikia GETNORD parduotuvėje prekių užsakymą ir Pirkėjo nurodytu elektroniniu paštu Pardavėjas išsiunčia patvirtinimą, kad Pirkėjo užsakymas yra priimtas. Jei Lieatuvos Respublikos teisės aktai numato, kad tam tikras prekes gali įsigyti tik tokią teisę turintys asmenys. </span></p>
<p class="p1"><span class="s1">1.7. Pirkėjui nesuteikiama galimybė pateikti prekių užsakymo GETNORD parduotuvėje, jeigu jis nėra susipažinęs su Taisyklėmis ir (ar) su jomis nesutinka. Tais atvejais, kai Pirkėjas nesutinka su Taisyklėmis arba tam tikra jų dalimi, jis neturėtų užsakyti prekių GETNORD parduotuvėje. Pirkėjui užsisakius prekių GETNORD parduotuvėje laikoma, jog Pirkėjas susipažino ir besąlygiškai sutiko su Taisyklėmis.</span></p>
<p class="p1"><span class="s1">1.8. Pardavėjas pasilieka teisę pakeisti, taisyti ar papildyti Taisykles. Pirkėjui apsiperkant GETNORD parduotuvėje taikomos Taisyklės, galiojančios užsakymo pateikimo momentu, todėl Pirkėjui rekomenduojama su Taisyklėmis susipažinti kiekvieno apsipirkimo metu.</span></p>
<p class="p1"><span class="s1">1.9. Pardavėjas neprisiima jokios rizikos ar atsakomybės ir yra nuo jos besąlygiškai atleidžiamas, jei Pirkėjas iš dalies ar visiškai nesusipažino su Taisyklėmis, nors jam tokia galimybė buvo suteikta.</span></p>
<p class="p1"><span class="s1">1.10. Pardavėjas, atsižvelgdamas į GETNORD parduotuvės sistemos techninius pajėgumus, turi teisę riboti registruotų Pirkėjų skaičių.</span></p>
<p class="p1"><span class="s1">1.11. Pardavėjas turi teisę be įspėjimo apriboti Pirkėjo naudojimąsi GETNORD parduotuvės paslaugomis arba panaikinti Pirkėjo registraciją, jeigu Pirkėjas GETNORD parduotuve naudojasi pažeisdamas šias Taisykles, bando pakenkti GETNORD parduotuvės ar Pardavėjo vykdomų užsakymų, darbo stabilumui ir (arba) saugumui.</span></p>
<p class="p1"><span class="s1">1.12. Atsižvelgdamas į Taisyklių 1.2 punktą ir siekdamas pirmiausia patenkinti mažmeninės prekybos vartotojų poreikius, Pardavėjas pasilieka teisę riboti didmeninio pirkimo požymių turinčius pirkimus, t. y. Pardavėjas turi teisę atsisakyti priimti ir (ar) vykdyti Pirkėjo užsakymą (-us), kai Pirkėjas užsako mažmeninėje prekyboje neįprastai didelius prekių kiekius (neatsižvelgiant į tai, ar prekės užsakomos vienu užsakymu, ar keletu per sąlyginai trumpą laiką pateikiamų užsakymų) ir (ar) kai Pirkėjo užsakymas (-ai) turi kitų didmeninio pirkimo požymių.</span></p>
<p class="p1"><span class="s1">1.13. Pardavėjas gali laikinai arba iš viso nutraukti GETNORD parduotuvės veiklą, apie tai iš anksto nepranešęs Pirkėjui. Įvykus nenugalimos jėgos (force majeure) aplinkybėms, Pardavėjas turi teisę sustabdyti sutarties įvykdymą iki nenugalimos jėgos (force majeure) aplinkybių išnykimo, pranešant Pirkėjui apie užsakymo vykdymo sustabdymą. Jeigu pirkėjui nebeaktualus vėlesnis sutarties įvykdymas, tuomet pirkėjas turi teisę atsisakyti sutarties apie tai pranešdamas Pardavėjui. Pardavėjui sustabdžius veiklą, bet esant galimybei įvykdyti patvirtintus užsakymus, visos teisės ir pareigos numatytos šiose taisyklėse ar taikomuose teisės aktuose, susijusios su jau įvykdytais arba vykdomais užsakymais, išlieka galioti.</span></p>
<p class="p1"><span class="s1">1.14. Pardavėjas šiuo informuoja, patvirtina ir garantuoja Pirkėjui, kad jis kaip Pardavėjas yra įgaliotas parduotuvėje GETNORD organizuoti, vykdyti Pardavėjui priklausančių prekių prekybą ir teikti Pirkėjui su tokių prekių prekyba susijusias kitas paslaugas, kaip nurodyta šiose Taisyklėse.</span></p>
<p class="p2"> </p>
<p class="p1"><strong><span class="s1">2. Registracija ir asmens duomenų tvarkymas</span></strong></p>
<p class="p1"><span class="s1">2.1. Pirkėjas, norėdamas naudotis GETNORD parduotuve ir pirkti joje siūlomas prekes, privalo užsiregistruoti GETNORD parduotuvės sistemoje, užpildydamas registracijos anketą. Registracijos anketoje privalu pateikti šiuos Pirkėjo asmeninius duomenis: vardą, pavardę, elektroninį paštą, adresą, kuriuo bus pristatomos prekės, telefono numerį, kitus prekių pristatymui būtinus duomenis. Juridinio asmens įgaliotas atstovas vietoje vardo ir pavardės pateikia juridinio asmens pavadinimą.</span></p>
<p class="p1"><span class="s1">2.2. </span><span class="s2">Pirkėjas yra atsakingas, kad registracijos anketoje pateikti duomenys būtų tikslūs, teisingi ir išsamūs</span><span class="s1">. Jeigu pasikeičia Pirkėjo registracijos formoje pateikti duomenys, jis privalo nedelsdamas juos atnaujinti. Pardavėjas jokiu atveju nebus atsakingas už žalą, atsiradusią Pirkėjui ir (ar) tretiesiems asmenims dėl to, jog Pirkėjas nurodė neteisingus ir (ar) neišsamius asmens duomenis arba nepakeitė ir nepapildė duomenų jiems pasikeitus.</span></p>
<p class="p1"><span class="s1">2.3. Pirkėjas turi teisę bet kuriuo momentu nevaržomai registracijos duomenis keisti, papildyti ar panaikinti savo registraciją. Panaikinęs registraciją, Pirkėjas netenka galimybės naudotis GETNORD parduotuve ir joje pirkti. Pirkėjas vėl įgyja galimybę pirkti tik iš naujo užsiregistravęs GETNORD parduotuvėje. Atkreipiame dėmesį, kad adreso ir (arba) telefono numerio keitimas svarbus atsiskaitymų debetinėmis ar kreditinėmis kortelėmis atveju (žr. 3.3.2 punktą). </span></p>
<p class="p1"><span class="s1">2.4. Registruodamasis Pirkėjas susikuria individualius prisijungimo duomenis (vartotojo vardą ir slaptažodį) ir įsipareigoja juos saugoti paslaptyje bei neatskleisti jokiems tretiesiems asmenims. Siekiant sumažinti neteisėto prisijungimo prie GETNORD parduotuvės Pirkėjo vardu riziką, rekomenduojama susikurti sudėtingą, sunkiai nuspėjamą slaptažodį (rekomenduojama slaptažodį sudaryti iš ne mažiau kaip 8 simbolių, panaudojant didžiąsias ir mažąsias raides, skaičius bei skyrybos ženklus, vengti lengvai nuspėjamų žodžių (Pirkėjo vardo, pavardės ir pan.) ir (arba) skaičių (pvz. gimimo datos) ir pan.) ir keisti jį ne rečiau kaip kas 6 (šešis) mėnesius. </span><span class="s2">Pirkėjas yra atsakingas už jo susikurtų prisijungimo duomenų sudėtingumą bei jų išsaugojimą, o taip pat už bet kuriuos veiksmus (duomenų perdavimą, pateiktus prekių užsakymus, vartotojo komentarus ar kt.), kurie GETNORD parduotuvėje atliekami prisijungus individualiu Pirkėjo vardu ir slaptažodžiu</span><span class="s1">. Jei GETNORD teikiamomis paslaugomis naudojasi trečiasis asmuo, prisijungęs prie parduotuvės internete naudodamasis Pirkėjo prisijungimo duomenimis, Pardavėjas šį asmenį laiko Pirkėju. Jei Pirkėjas praranda prisijungimo duomenis, jis privalo nedelsiant informuoti apie tai Pardavėją paštu, telefonu ar el. laišku arba pasikeisti prisijungimo duomenis prisijungdamas prie GETNORD parduotuvės sistemos skiltyje „Mano duomenys“. Pardavėjas negali būti ir nebus laikomas atsakingu už žalą, padarytą Pirkėjui, tretiesiems asmenims prisijungus prie GETNORD parduotuvės pasinaudojant Pirkėjo prisijungimo duomenimis. Prisijungimo duomenų saugumas itin svarbus atsiskaitymų debetinėmis ar kreditinėmis kortelėms atveju (žr. 3.3.2 punktą).</span></p>
<p class="p1"><span class="s1">2.5. Pirkėjo asmens duomenys bus tvarkomi pagal </span><span class="s3">Privatumo politiką</span><span class="s2">. </span><span class="s1">Jei Pirkėjas naudojasi GETNORD parduotuvės paslaugomis, laikoma, kad jis sutinka su Pirkėjo asmens duomenų tvarkymu ir patvirtina, kad visa pateikta informacija ir asmens duomenys yra teisingi ir atitinka tikrovę.</span></p>
<p class="p1"><span class="s1">2.6. Pirkėjo asmens duomenys bus naudojami identifikuojant Pirkėją, nustatant, ar Pirkėjas ir asmuo, kuriam pristatomos prekės, yra pilnametis (Lietuvos Respublikos įstatymų nustatytais atvejais), vykdant prekių pardavimą ir pristatymą, išrašant apskaitos dokumentus, grąžinant permokas ir (ar) pinigus už Pirkėjo grąžintas prekes, administruojant įsiskolinimus, vykdant kitus iš pirkimo-pardavimo sutarties kylančius įsipareigojimus bei užtikrinant Pirkėjui galimybę naudotis kitomis GETNORD parduotuvės paslaugomis.</span></p>
<p class="p1"><span class="s1">2.7. Pirkėjo asmens duomenys bus tvarkomi tiesioginės rinkodaros tikslais tik gavus Pirkėjo sutikimą. Pirkėjo sutikimas išreiškiamas užpildant registracijos anketą ir šiose Taisyklėse nustatyta tvarka anketoje pažymint atitinkamus laukus.</span></p>
<p class="p1"><strong><span class="s1">3. Prekių kainos, apmokėjimo tvarka ir terminai</span></strong></p>
<p class="p1"><span class="s1">3.1. Prekių kainos GETNORD parduotuvėje ir suformuotame užsakyme Eurais su PVM. Prekės Pirkėjui parduodamos kainomis, galiojančiomis GETNORD parduotuvėje užsakymo pateikimo momentu.</span></p>
<p class="p1"><span class="s1">3.3. Pirkėjas atsiskaito už prekes vienu iš šių būdų:</span></p>
<p class="p1"><span class="s1">3.3.1. Apmokėjimas naudojantis elektronine bankininkyste – tai išankstinis apmokėjimas pasinaudojant Pirkėjo naudojama elektroninės bankininkystės sistema. Pirkėjas, norėdamas pasinaudoti šia apmokėjimo forma, turi būti pasirašęs elektroninės bankininkystės sutartį su vienu iš žemiau nurodytų bankų: „Swedbank“, AB, „Nordea Bank Finland Plc“ Lietuvos skyrius; AB SEB bankas, AB DNB bankas ar Danske Bank A/S Lietuvos filialas. Mokant už prekes šiuo būdu, Pirkėjui elektroninės bankininkystės sistemoje sugeneruojamas mokėjimas pagal jo apmokamą užsakymą. Pinigus Pirkėjas perveda į Pardavėjo sąskaitą. Atsakomybė už Pirkėjo mokėjimo metu duomenų saugumą šiuo atveju tenka atitinkamam bankui, kadangi visos piniginės operacijos vyksta banko elektroninės bankininkystės sistemoje.</span></p>
<p class="p1"><span class="s1">3.3.2. Apmokėjimas užsakymo metu naudojantis mokėjimo kortelėmis – tai išankstinis apmokėjimas pasinaudojant Pirkėjo naudojama MasterCard, VISA ar VISA Electron debetine ar kreditine kortele, kurios yra išduotos Europos Ekonominės Erdvės šalyse; kitose šalyse išduotos mokėjimo kortelės GETNORD parduotuvėje, atsiskaitant šiuo būdu, nėra aptarnaujamos. Mokant už prekes Pirkėjo kreditine ar debetine kortele pirmą kartą, Pirkėjas turi suvesti savo kortelės duomenis. </span><span class="s2">Kitais atsiskaitymo už prekes kreditine ar debetine kortele, kuria Pirkėjas buvo atsiskaitęs GETNORD parduotuvėje, kartais GETNORD parduotuvės sistema pasiūlys atsiskaityti kreditine ar debetine kortele, kuria Pirkėjas bent kartą buvo atsiskaitęs už prekes GETNORD parduotuvėje, nereikalaujant iš naujo suvesti kortelės duomenų. Tokiu atveju pirkimui užbaigti pasinaudojant Pirkėjo kreditine ar debetine kortele, kuria Pirkėjas bent kartą buvo atsiskaitęs už prekes GETNORD parduotuvėje (t. y. bet kuria iš kortelių), pakaks pakartotinai įvesti Pirkėjo prisijungimo prie GETNORD parduotuvės sistemos slaptažodį</span><span class="s1">. Pažymėtina, kad, Pirkėjui pakeitus GETNORD parduotuvės sistemoje (skiltyje „Mano duomenys“) Pirkėjo užregistruotą prekių pristatymo adresą ir (arba) Pirkėjo telefono numerį, siekiant apsaugoti Pirkėjo interesus nuo galimų piktnaudžiavimo atvejų, GETNORD parduotuvės sistema panaikins mokėjimo kortelių, kuriomis jau buvo atlikti atsiskaitymai GETNORD parduotuvėje, sąrašą ir reikalaus kortelės duomenis suvesti iš naujo, t. y. lyg atsiskaitant atitinkama kortele pirmą kartą. Be to, Pirkėjas, bet kuriuo metu prisijungęs prie GETNORD parduotuvės sistemos (skiltyje „Mano duomenys“), gali ištrinti mokėjimo kortelių, kuriomis jau buvo atlikti atsiskaitymai GETNORD parduotuvėje, sąrašą. Tiek suvesdamas kreditinės ar debetinės kortelės duomenis, tiek ir atsiskaitydamas kreditine ar debetine kortele, Klientas GETNORD parduotuvės sistemoje nepalieka duomenų, kadangi mokėjimo operacijos atlikimui Pirkėjas nukreipiamas į sertifikuoto paslaugos teikėjo saugų serverį. Iš šio serverio GETNORD parduotuvės sistemai yra grąžinama tik dalinė informacija apie mokėjimo kortelės numerį.</span></p>
<p class="p1"><span class="s1">3.3.3. Apmokėjimas grynaisiais pinigais – tai atsiskaitymas už prekes jų pristatymo metu. Pageidautina, kad Pirkėjas, pasirinkęs atsiskaitymą už prekes grynaisiais pinigais prekių pristatymo metu, turėtų tikslią pinigų sumą, tačiau prekes pristatantis kurjeris gali duoti grąžą. Pirkėjas privalo patikrinti ir suskaičiuoti kurjerio duotą grąžą kartu su kurjeriu jos davimo metu. Pirkėjui raštu patvirtinus grynųjų pinigų perdavimo faktą, Pirkėjas vėliau nebegali reikšti pretenzijų dėl grąžos dydžio.</span></p>
<p class="p1"><span class="s1">3.3.4. Apmokėjimas naudojantis mokėjimo kortelėmis – tai atsiskaitymas už prekes jų pristatymo metu pasinaudojant Pirkėjo naudojama MasterCard, Maestro, VISA ar VISA Electron debetine ar kreditine kortele.</span></p>
<p class="p1"><span class="s1">3.4. Pirkėjui pasirinkus atsiskaitymą už prekes jų užsakymo metu, Pirkėjas už užsakytas prekes įsipareigoja sumokėti nedelsiant, tačiau ne vėliau kaip per 1 (vieną) valandą nuo užsakymo pateikimo momento. Tik Pardavėjui iš jo pasirinkto mokėjimų sistemos operatoriaus gavus atitinkamą Pirkėjo mokėjimo už prekes bei jų pristatymą (transportavimą) atlikimo patvirtinimą (atsiskaitant Sutarties 3.3.1 ar 3.3.2 punktuose nustatytu būdu) pradedamas vykdyti užsakymas ir skaičiuojamas prekių pristatymo terminas. Prekių ir jų pristatymo kainos sąskaitai apmokėti yra paskaičiuotos įskaitant PVM mokestį. Pirkėjui pasirinkus atsiskaitymą už prekes jų pristatymo metu, Pirkėjo užsakymas pradedamas vykdyti ir pradedamas skaičiuoti prekių pristatymo terminas nedelsiant, Pardavėjui apie tai patvirtinant Pirkėjui nurodytu elektroniniu paštu.</span></p>
<p class="p1"><span class="s1">3.5. Pirkėjui pasirinkus atsiskaitymą už prekes jų užsakymo metu, Pardavėjas turi teisę iš anksto nepranešęs Pirkėjui anuliuoti jo užsakymą, jeigu Pirkėjas nesumoka už prekes per 1 (vieną) valandą nuo užsakymo pateikimo momento.</span></p>
<p class="p1"><span class="s1">3.6. PVM sąskaitą-faktūrą Pardavėjas išrašo ir Pirkėjui pateikia Pirkėjo Registracijos anketoje nurodytu elektroniniu paštu per 3 (tris) darbo dienas po prekių pristatymo.</span></p>
<p class="p1"><span class="s1">3.7. Pirkėjas, jei jis yra juridinis asmuo, turi teisę atsiskaityti už prekes apmokant pateiktą išankstinę sąskaitą (pasirenkant tokį apmokėjimo būdą). Gavęs išankstinę sąskaitą Pirkėjas mokėjimą atlieka pasinaudodamas išankstinėje sąskaitoje nurodoma internetine nuoroda, kuri nukreipia į elektroninės bankininkystės sistemą. Pirkėjui elektroninės bankininkystės sistemoje sugeneruojamas mokėjimas pagal jo apmokamą užsakymą. Pinigus Pirkėjas perveda į Pardavėjo sąskaitą išankstinėje sąskaitoje nurodytu terminu. Pirkėjui neapmokėjus išankstinės sąskaitos joje nurodytu terminu arba apmokėjus išankstinę sąskaitą ne pagal sąskaitoje nurodomą internetinę nuorodą, prekių užsakymas nėra vykdomas. Atsakomybė už Pirkėjo mokėjimo metu duomenų saugumą šiuo atveju tenka atitinkamam bankui, kadangi visos piniginės operacijos vyksta banko elektroninės bankininkystės sistemoje.</span></p>
<p class="p1"><span class="s1">3.8. Pardavėjas turi teisę laisvai taikyti arba atsisakyti bet kurių mokėjimo būdų iš anksto nepranešęs Pirkėjui</span></p>
<p class="p2"> </p>
<p class="p1"><strong><span class="s1">4. Prekių komplektavimas ir pristatymas</span></strong></p>
<p class="p1"><span class="s1">4.1. GETNORD parduotuvės prekyba vykdoma ir prekės pristatomos Lietuvos reritorijoje. Prekybos teritorija yra nustatyta vienašaliu Pardavėjo sprendimu. Prekes pristato Pardavėjas arba jo įgaliotas atstovas.</span></p>
<p class="p1"><span class="s1">4.2. Už prekių pristatymo paslaugą taikomas mokestis, nurodytas GETNORD parduotuvės puslapyje „Prekių Pristatymas“ ir taikomas prekių užsakymo pateikimo momentu. Prekių pristatymo mokestis gali būti tiek fiksuotas, tiek priklausantis nuo Pirkėjo užsakytų prekių vertės ir (arba) pristatymo termino. Pirkėjui po užsakymo patvirtinimo papildžius pirkinių krepšelį, užsakymo patvirtinimo metu nurodytas pristatymo mokestis nesikeičia (t.y. Jei pateikiant užsakymą Jums buvo paskaičiuotas pristatymo mokestis jis išliks toks pat net ir papildžius pirkinių krepšelį).</span></p>
<p class="p1"><span class="s1">4.3. Pardavėjas turi teisę vienašališkai savo nuožiūra nustatyti minimalią pirkinių krepšelio sumą, t. y. minimalią sumą, už kurią Pirkėjas turėtų išsirinkti ir užsisakyti prekių GETNORD parduotuvėje, norėdamas jas įsigyti. Minimali pirkinių krepšelio suma nurodoma GETNORD parduotuvės skiltyje „Prekių pristatymas“. Į minimalią pirkinių krepšelio sumą nėra įskaitomas prekių pristatymo mokestis.</span></p>
<p class="p1"><span class="s1">4.4. Pirkėjo užsakytos prekės pristatomos GETNORD parduotuvės sistemoje Pirkėjo užregistruotu adresu. Pirkėjas užsakymo suformavimo metu pasirinkto laiko lango ribose įsipareigoja prekes priimti pats.</span></p>
<p class="p1"><span class="s1">4.5. Tuo atveju, kai Pirkėjo GETNORD parduotuvės sistemoje nurodytu pristatymo adresu Pirkėjas ar gavėjas nerandamas, Pardavėjas turi teisę prekes išduoti bet kuriam kitam nurodytu adresu esančiam pilnamečiui asmeniui arba 20 m. sulaukusiam asmeniui, o Pirkėjas neturi teisės reikšti Pardavėjui bet kokių pretenzijų dėl prekių pristatymo netinkamam subjektui.</span></p>
<p class="p1"><span class="s1">4.6. Jeigu prekės pristatymas yra neįmanomas dėl Pirkėjo kaltės arba dėl nuo Pirkėjo priklausančių aplinkybių (Pirkėjas registruodamasis GETNORD parduotuvės sistemoje nurodė neteisingą adresą, nurodytu adresu Pirkėjas ar gavėjas nerandamas, prekes priimantis asmuo yra nepilnametis, pateikė negaliojantį asmens dokumentą ar atsisakė pateikti asmens dokumentą (kai Pardavėjas turi įsitikinti prekes priimančio asmens amžiumi pagal taikytinus teisės aktus ar šias Taisykles), Pirkėjas neturi pakankamo grynųjų pinigų kiekio, nurodyto užsakyme, Pirkėjas negali atsiskaityti mokėjimo kortele ne dėl Pardavėjo kaltės ar kt.), pakartotinai prekės nėra siunčiamos (išskyrus atvejus, kai Pirkėjas papildomai sumoka už pakartotinį prekės pristatymą), o iš anksto už prekes sumokėti pinigai grąžinami išskaičiavus prekių pristatymo mokestį. Tuo atveju, jei užsakymo pateikimo metu Pirkėjui buvo taikyta pristatymo mokesčio nuolaida, tačiau prekių pristatymas nėra įmanomas dėl Pirkėjo kaltės arba dėl nuo Pirkėjo priklausančių aplinkybių, Pardavėjas pasilieka teisę išskaičiuoti iš Pirkėjui grąžintinos pinigų sumos visą prekių pristatymo mokestį (galiojusį prekių užsakymo pateikimo momentu), neatsižvelgiant į užsakymo pateikimo metu taikytas nuolaidas. Jei Pirkėjas buvo pasirinkęs atsiskaitymą už prekes jų pristatymo metu, Pirkėjas privalo padengti Pardavėjo patirtas pristatymo išlaidas, kurių dydis nurodytas Taisyklių 1.6 punkte.</span></p>
<p class="p1"><span class="s1">4.7. Pardavėjas pristato prekes Pirkėjui jo užsakymo suformavimo metu pasirinkto laiko lango ribose. Pirkėjas sutinka, jog išimtiniais atvejais prekių pristatymas gali vėluoti dėl nenumatytų ir nuo Pardavėjo nepriklausančių aplinkybių. </span></p>
<p class="p1"><span class="s1">4.8. Visais atvejais Pardavėjas atleidžiamas nuo atsakomybės už prekių pristatymo terminų pažeidimą, jeigu prekės Pirkėjui nėra pristatomos arba pristatomos ne laiku dėl Pirkėjo kaltės arba dėl nuo Pirkėjo priklausančių aplinkybių.</span></p>
<p class="p1"><span class="s1">4.9. Prekių pristatymo metu Pirkėjui pageidaujant, vairuotojas privalo suteikti galimybę kartu su Pardavėju arba jo įgaliotu atstovu patikrinti siuntos būklę, pristatytų prekių komplektiškumą (asortimentą). Pirkėjui nepatikrinus siuntos būklės, pristatytų prekių komplektiškumo ir (ar) šiame punkte nustatyta tvarka neužfiksavus duomenų apie siuntos pažeidimus, siunta yra laikoma pristatyta tinkama ir nepažeista.</span></p>
<p class="p1"><span class="s1">4.10. Prekės po siuntos patikrinimo (4.15. punktas) Pirkėjui perduodamos tik tada, kai Pirkėjas pasirašo važtaraštyje, prekių lydraštyje ar kitame siuntos perdavimo – priėmimo dokumente (dokumentu gali būti laikomi ir elektroniniai įrenginiai). Jei Pirkėjas dėl fizinio trūkumo, ligos ar kitokių priežasčių negali pats pasirašyti elektroniniuose ar kituose dokumentuose, jo pavedimu už jį pasirašo kitas asmuo arba Pardavėjas (ar jo įgaliotas asmuo), Pirkėjui patvirtinus pasirašymo galimybę. Pirkėjui nepasirašius prekių važtaraštyje, prekių lydraštyje ar kitame siuntos perdavimo – priėmimo dokumente (įskaitant ir elektroniniame dokumente), prekės Pirkėjui neperduodamos ir pakartotinai prekės nėra siunčiamos (išskyrus atvejus, kai Pirkėjas papildomai sumoka už pakartotinį prekės pristatymą), o iš anksto už prekes sumokėti pinigai grąžinami išskaičiavus prekių pristatymo mokestį. Tuo atveju, jei užsakymo pateikimo metu Pirkėjui buvo taikyta pristatymo mokesčio nuolaida, Pardavėjas pasilieka teisę išskaičiuoti iš Pirkėjui grąžintinos pinigų sumos visą prekių pristatymo mokestį (galiojusį prekių užsakymo pateikimo momentu), neatsižvelgiant į užsakymo pateikimo metu taikytas nuolaidas. Jei Pirkėjas buvo pasirinkęs atsiskaitymą už prekes jų pristatymo metu, Pirkėjas privalo padengti Pardavėjo patirtas pristatymo išlaidas, kurių dydis nurodytas Taisyklių 1.6. punkte.</span></p>
<p class="p1"><span class="s1">4.11. Tais atvejais, kai prekių priėmimo metu Pirkėjas pastebi, jog siuntoje nėra tinkamo prekių kiekio arba pateiktos prekės neatitinka jo užsakytų prekių ir tai nėra nurodyta sąskaitoje-faktūroje, važtaraštyje, prekių lydraštyje ar kitame siuntos perdavimo – priėmimo dokumente, Pirkėjas privalo nedelsiant (prekių pristatymo metu) informuoti apie tai Pardavėją. Kai Pirkėjas nustato, kad pristatytos prekės yra netinkamos kokybės, jis nekokybiškų prekių nepriima ir turi jas grąžinti kurjeriui, o prekių grąžinimo faktą bei priežastį pažymėti sąskaitoje-faktūroje, važtaraštyje ar kitame siuntos perdavimo – priėmimo ar prekių grąžinimo dokumente.</span></p>
<p class="p2"> </p>
<p class="p1"><strong><span class="s1">5. Prekių kokybės garantija ir tinkamumo naudoti terminas</span></strong></p>
<p class="p1"><span class="s1">5.1. Visų GETNORD parduotuvėje internete parduodamų prekių savybės bendrai nurodomos prie kiekvienos prekės esančiame prekės aprašyme. Už informaciją apie prekių savybes (jos teisingumą) atsako prekių gamintojai ir (arba) importuotojai, o Pardavėjas yra atsakingas tik už tinkamą šios informacijos pateikimą (perdavimą) vartotojams, nebent įstatymai numatytų kitaip.</span></p>
<p class="p1"><span class="s1">5.2. Pardavėjas neatsako už tai, kad GETNORD parduotuvėje internete esančios prekės savo spalva, forma ar kitais parametrais gali neatitikti realaus prekių dydžio, formų ir spalvos dėl Pirkėjo naudojamo vaizduoklio (monitoriaus) ypatybių ar kitų techninių priežasčių, taip pat atsižvelgiant į protingai galimus išvaizdos neatitikimus. Jeigu prekės spalvos, dydžio ar formos neatitikimas sąlygotas dėl Pardavėjo ar su juo susijusių trečiųjų asmenų veiksmų, tuomet Pardavėjas atsako už prekės galimus išvaizdos neatitikimus.</span></p>
<p class="p1"><span class="s1">5.3. Pardavėjas patvirtina, kad yra atsakingas už GETNORD internetinėje parduotuvėje užsakytų prekių pardavimą ir įsigytų prekių tinkamą pristatymą, prekių kokybę, grąžinimo sąlygų tinkamą įvykdymą bei kitų teisės aktuose numatytų pardavėjo teisių ir pareigų įgyvendinimą.</span></p>
<p class="p1"><span class="s1">5.4. Tuo atveju, kai Pardavėjas tam tikroms prekių rūšims daiktų kokybės garantijos nesuteikia, galioja garantija, numatyta atitinkamų teisės aktų.</span></p>
<p class="p1"><span class="s1">5.5. Tais atvejais, kai remiantis teisės aktais konkrečių prekių atžvilgiu nustatomas tam tikras tinkamumo naudoti terminas, Pardavėjas įsipareigoja tokias prekes parduoti Pirkėjui taip, kad jam būtų suteikta reali galimybė tokiomis prekėmis pasinaudoti iki tinkamumo naudoti termino pabaigos.</span></p>
<p class="p2"> </p>
<p class="p1"><strong><span class="s1">6. Sutarties atsisakymas. Prekių keitimas ir grąžinimas</span></strong></p>
<p class="p1"><span class="s1">6.1. Pirkėjas turi teisę atsisakyti GETNORD parduotuvėje sudarytos prekių pirkimo – pardavimo sutarties, pranešdamas apie tai Pardavėjui raštu ne vėliau kaip per 14 (keturiolika) kalendorinių dienų nuo prekės pristatymo dienos. Laisvos formos pranešimą apie sutarties atsisakymą ir kitą Pardavėjo nurodytą informaciją Pirkėjas privalo pateikti Pardavėjui el. paštu: support@GETNORD.lt.</span></p>
<p class="p1"><span class="s1">6.2. Pateikęs raštišką pranešimą apie sutarties atsisakymą ir kitą Pardavėjo nurodytą informaciją, Pirkėjas privalo ne vėliau kaip per 15 (penkiolika) kalendorinių dienų grąžinti prekę (jeigu ji buvo pristatyta) šių Taisyklių 6.6 punkte nustatyta prekių keitimo ir grąžinimo tvarka.</span></p>
<p class="p1"><span class="s1">6.3. Taisyklių 6.1 punkte numatyta teise gali pasinaudoti tik Pirkėjas, kuris pagal LR Vartotojų teisių apsaugos įstatymo nuostatas pripažintinas vartotoju, t. y. fizinis asmuo, su savo verslu, prekyba, amatu ar profesija nesusijusiais tikslais (vartojimo tikslais) siekiantis sudaryti ar sudarantis sutartis.</span></p>
<p class="p1"><span class="s1">6.4. Netinkamos kokybės ne greitai gendančių prekių ar kokybiškų prekių, kurių Pirkėjui nepatinka forma, dydis, spalva, modelis ar komplektiškumas, keičiamos ar grąžinamos vadovaujantis 2001 m. birželio 11 d. Lietuvos Respublikos Vyriausybės nutarimu Nr. 697 patvirtintomis Mažmeninės prekybos taisyklėmis, Lietuvos Respublikos civiliniu kodeksu ir kitais galiojančiais Lietuvos Respublikos teisės aktais.<br /> 6.5. Prekės keičiamos ar grąžinamos Pardavėjui iš anksto suderinus prekių atsiėmimo laiką ir adresą. </span></p>
<p class="p1"><span class="s1">6.6. Grąžinant ar keičiant GETNORD parduotuvėje įsigytas prekes, Pardavėjas turi teisę reikalauti užpildyti Pardavėjo pateiktą prekių grąžinimo ar keitimo formą.</span></p>
<p class="p1"><span class="s1">6.7. Grąžinamos ar keičiamos kokybiškos prekės privalo būti nesugadintos, nepraradusios prekinės išvaizdos (nenuimtos ir nepažeistos etiketės, nenuplėštos apsauginės plėvelės ir kt.), vartojamųjų savybių ir negali būti naudotos. Prekė turi būti grąžinama originalioje pakuotėje, tos pačios komplektacijos, kokios buvo Pirkėjo gauta, būtinai pateikiant prekės įsigijimo dokumentą, garantinę kortelę (jei ji buvo išduota), naudojimo instrukcijas ir kitus prekės priklausinius. Jeigu prekė nėra pilnai sukomplektuota, yra sugadinta, netvarkinga arba nėra tinkamai supakuota, Pardavėjas turi teisę nepriimti prekės, jos nekeisti ir negrąžinti už prekę Pirkėjo sumokėtų pinigų.</span></p>
<p class="p1"><span class="s1">6.9. Už Pirkėjo priimtas, bet vėliau atsisakytas prekes sumokėti pinigai sumokami į Pirkėjo sąskaitą ne vėliau kaip per 14 (keturiolika) dienų nuo Pirkėjo pranešimo apie Sutarties atsisakymą gavimo dienos, nebent Pardavėjas ir Pirkėjas susitaria kitaip.</span></p>
<p class="p1"><span class="s1">6.10. Grąžinant ar keičiant kokybiškas ir Pirkėjo užsakymą atitinkančias prekes, Pirkėjui grąžinamas jo sumokėtas prekių pristatymo mokestis tik tuo atveju, jei grąžinamos visos tuo pačiu apsipirkimu Pirkėjo įsigytos prekės. Pristatymo mokestis grąžinamas kartu su kitomis už grąžinamas prekes Pardavėjo Pirkėjui mokamomis sumomis.</span></p>
<p class="p2"> </p>
<p class="p1"><strong><span class="s1">7. Apsikeitimas informacija</span></strong></p>
<p class="p1"><span class="s1">7.1. Pardavėjas visus pranešimus siunčia ir kitaip kontaktuoja Pirkėjo registracijos formoje pateiktu elektroninio pašto adresu ar telefonu.</span></p>
<p class="p1"><span class="s1">7.2. Pirkėjas visus pranešimus ir klausimus siunčia ir kitaip kontaktuoja el. paštu (suppoer@GETNORD.lt) ar telefonu (8 37 268896).</span></p>
<p class="p2"> </p>
<p class="p3"><strong><span class="s1">8. Nuolaidų kuponai</span></strong></p>
<p class="p4"><span class="s1">8.1. Nuolaidų kuponą gali panaudoti tik registruoti elektroninės parduotuvės GETNORD vartotojai.</span></p>
<p class="p4"><span class="s1">8.2. Nuolaidų kupono kodas gali būti atsiunčiamas spausdintoje skrajutėje, elektroniniu laišku ar nurodant nuolaidų kupono kodą telefonu.</span></p>
<p class="p4"><span class="s1">8.3. Nuolaidų kupone esantis kodas gali būti panaudojamas tik vieną kartą ir tik perkant elektroninėje parduotuvėje GETNORD.</span></p>
<p class="p4"><span class="s1">8.4. Nuolaidos kupone nurodyta nuolaida nėra taikoma minimaliam prekių krepšeliui.</span></p>
<p class="p4"><span class="s1">8.5. Nuolaidų kuponai į pinigus nekeičiami.</span></p>
<p class="p4"><span class="s1">8.6. Nuolaidų kuponus draudžiama parduoti..</span></p>
<p class="p4"><span class="s1">8.7. Nuolaidų kuponai galioja iki ant jų nurodytos datos. Nuolaidų kuponai, kurių galiojimo data jau pasibaigusi, į elektroninėje parduotuvėje GETNORD parduodamas prekes nekeičiami, jų galiojimas nepratęsiamas ir jie nekompensuojami.</span></p>
<p class="p4"><span class="s1">8.8. Už informacijos saugumą atsako nuolaidų kuponą turintis asmuo.</span></p>
<p class="p4"><span class="s1">8.9. Visi nuolaidų kuponai gali būti panaudoti tik elektroninėje parduotuvėje GETNORD įsigytų prekių krepšelio sumai sumažinti. Nuolaidų kuponai nėra sumuojami, taip pat nuolaidų kuponams nėra taikomos kitos elektroninės parduotuvės GETNORD nuolaidos.</span></p>
<p class="p4"><span class="s1">8.10. Panaudoti nuolaidų kuponai nekompensuojami.</span></p>
<p class="p4"><span class="s1">8.11. Negaliojantys, pamesti ar kitaip sugadinti (pvz., pažeistas kupono kodas, kurio neįmanoma identifikuoti) nuolaidų kuponai nekompensuojami, jų galiojimas nepratęsiamas.</span></p>
<p class="p4"><span class="s1">8.12. Nuolaidų kuponai į kitus kuponus nekeičiami ir negrąžinami.</span></p>
<p class="p5"> </p>
<p class="p1"><strong><span class="s1">9. Baigiamosios nuostatos</span></strong></p>
<p class="p1"><span class="s1">9.1. Šios Taisyklės sudarytos vadovaujantis Lietuvos Respublikos teisės aktais.</span></p>
<p class="p1"><span class="s1">9.2. Šių Taisyklių pagrindu kylantiems santykiams taikoma Lietuvos Respublikos teisė.</span></p>
<p class="p1"><span class="s1">9.3. Atsiradus žalai, kaltoji šalis atlygina kitai šaliai tiesioginius nuostolius Lietuvos Respublikos įstatymų nustatyta tvarka ir pagrindais.</span></p>
<p class="p1"><span class="s1">9.4. Visi nesutarimai, kilę dėl šių Taisyklių vykdymo, sprendžiami derybų būdu. Nepavykus susitarti, ginčai sprendžiami Lietuvos Respublikos įstatymų nustatyta tvarka.</span></p>
<p class="p1"><span class="s1">9.5. Kiekvienas vartotojas turi galimybę spręsti su Pardavėju iškilusius ginčus ir elektroniniu būdu, nesikreipdamas į teismą. Pirmiausia vartotojas raštu turi kreiptis į Pardavėją bei per 14 dienų nuo pretenzijos gavimo, Pardavėjui neatsakius į vartotojo pretenziją, arba nepatenkinus vartotojo pretenzijos, vartotojas gali kreiptis į ne teismo tvarka vartojimo ginčus nagrinėjantį subjektą, t.y. Valstybinę vartotojų teisių apsaugos tarnybą (Vilniaus g.25, 01402 Vilnius, el. p. <a href="mailto:tarnyba@vvtat.lt"><span class="s3">tarnyba@vvtat.lt</span></a>, tel. 852626751, interneto svetainė <a href="http://www.vvtat.lt/"><span class="s3">www.vvtat.lt</span></a>), arba į jos teritorinius padalinius apskrityse ar užpildyti prašymo formą EGS platformoje <a href="http://ec.europa.eu/ods/"><span class="s3">http://ec.europa.eu/ods/</span></a>).</span></p> 
</div>
</div>
@endsection