@extends('layouts.informational')

@section('content')
<div class="page_content">
    <div class="main_container">
        <p class="p1"><span class="s1">ALGEMENE VERKOOPVOORWAARDEN</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 1. DEFINITIES</strong></span></p>
<p class="p1"><span class="s1">1.1. IN DEZE ALGEMENE VERKOOPVOORWAARDEN WORDEN DE HIERNA VOLGENDE TERMEN IN DE NAVOLGENDE BETEKENIS GEBRUIKT, TENZIJ UITDRUKKELIJK ANDERS IS AANGEGEVEN OF UIT DE CONTEXT ANDERS BLIJKT:</span></p>
<p class="p1"><span class="s1">    A. GETNORD.COM: DE GEBRUIKER VAN DEZE ALGEMENE VERKOOPVOORWAARDEN:</span></p>
<p class="p1"><span class="s1">      REDLAINAS</span></p>
<p class="p1"><span class="s1">      Verslo 6, Kumpiai, 54311 Kaunas</span></p>
<p class="p1"><span class="s1">      Litouwen</span></p>
<p class="p1"><span class="s1">    B. KLANT: DE NATUURLIJKE PERSOON DIE VIA DE WEBSITE BIJ GETNORD.COM EEN BESTELLING PLAATST;</span></p>
<p class="p1"><span class="s1">    C. OVEREENKOMST: DE OVEREENKOMST TUSSEN GETNORD.COM EN DE KLANT;</span></p>
<p class="p1"><span class="s1">    D. PRODUCT: HET PRODUCT DAT VIA DE WEBSITE VERKOCHT WORDT;:</span></p>
<p class="p1"><span class="s1">    E. WEBSITE: DE WEBSITE WWW.GETNORD.COM</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 2. ALGEMEEN</strong></span></p>
<p class="p1"><span class="s1">2.1 DEZE ALGEMENE VERKOOPVOORWAARDEN ZIJN VAN TOEPASSING OP ALLE OVEREENKOMSTEN DIE VIA DE WEBSITE TUSSEN GETNORD.COM EN DE KLANT TOT STAND KOMEN.</span></p>
<p class="p1"><span class="s1">2.2 VAN DEZE ALGEMENE VERKOOPVOORWAARDEN AFWIJKENDE BEDINGEN ZIJN SLECHTS VAN KRACHT INDIEN EN VOOR ZOVER PARTIJEN DIE UITDRUKKELIJK SCHRIFTELIJK OF VIA DE E-MAIL ZIJN OVEREENGEKOMEN.</span></p>
<p class="p1"><span class="s1">2.3 INDIEN ÉÉN OF MEERDERE BEPALINGEN IN DEZE ALGEMENE VERKOOPVOORWAARDEN OP ENIG MOMENT GEHEEL OF GEDEELTELIJK NIETIG ZIJN OF VERNIETIGD MOCHTEN WORDEN, DAN BLIJFT HET OVERIGE IN DEZE ALGEMENE VERKOOPVOORWAARDEN BEPAALDE VOLLEDIG VAN TOEPASSING. DE NIETIGE OF VERNIETIGDE BEPALINGEN ZULLEN DOOR GETNORD.COM VERVANGEN WORDEN, WAARBIJ VOOR ZOVEEL MOGELIJK HET DOEL EN DE STREKKING VAN DE OORSPRONKELIJKE BEPALING(EN) IN ACHT WORDT GENOMEN.</span></p>
<p class="p1"><span class="s1">2.4 INDIEN GETNORD.COM NIET STEEDS STRIKTE NALEVING VAN DEZE ALGEMENE VERKOOPVOORWAARDEN VERLANGT, BETEKENT DIT NIET DAT DE BEPALINGEN DAARVAN NIET VAN TOEPASSING ZIJN OF DAT GETNORD.COM IN ENIGERLEI MATE HET RECHT ZOU VERLIEZEN OM IN ANDERE GEVALLEN DE STIPTE NALEVING VAN DE BEPALINGEN VAN DEZE ALGEMENE VERKOOPVOORWAARDEN TE VERLANGEN.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 3. HET AANBOD</strong></span></p>
<p class="p1"><span class="s1">3.1 AANBIEDINGEN ZIJN VRIJBLIJVEND.</span></p>
<p class="p1"><span class="s1">3.2 AANBIEDINGEN GELDEN NIET AUTOMATISCH VOOR TOEKOMSTIGE OVEREENKOMSTEN.</span></p>
<p class="p1"><span class="s1">3.3 GETNORD.COM IS NIET GEBONDEN AAN HAAR AANBOD INDIEN SPRAKE IS VAN DRUK-, ZET- OF PROGRAMMEERFOUTEN IN HAAR E-MAILBERICHTEN OF OP DE WEBSITE.</span></p>
<p class="p1"><span class="s1">3.4 HET ASSORTIMENT DAT OP DE WEBSITE WORDT AANGEBODEN KAN WORDEN GEWIJZIGD.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 4. TOTSTANDKOMING VAN DE OVEREENKOMST</strong></span></p>
<p class="p1"><span class="s1">4.1 DE OVEREENKOMST KOMT TOT STAND NADAT DE KLANT DE BESTELPROCEDURE VIA DE WEBSITE HEEFT DOORLOPEN.</span></p>
<p class="p1"><span class="s1">4.2 NADAT DE OVEREENKOMST VIA DE WEBSITE TOT STAND IS GEKOMEN, STUURT GETNORD.COM DE KLANT VIA DE E-MAIL EEN BEVESTIGING DAT GETNORD.COM DE BESTELLING HEEFT ONTVANGEN. IN DEZE BEVESTIGINGSE-MAIL ZIJN HET BESTELNUMMER EN DE OVERIGE GEGEVENS VAN DE BESTELLING VAN DE KLANT OPGENOMEN. INDIEN DE KLANT NIET ONVERWIJLD NA DE PLAATSING VAN DE BESTELLING EEN BEVESTIGINGSE-MAIL VAN GETNORD.COM HEEFT ONTVANGEN, DAN DIENT DE KLANT CONTACT OP TE NEMEN MET DE KLANTENSERVICE VAN GETNORD.COM, VOOR DE CONTACTGEGEVENS VAN DE KLANTENSERVICE VAN GETNORD.COM ZIE ARTIKEL 13.1.</span></p>
<p class="p1"><span class="s1">4.3 DE BESTELLING KAN PAS VIA DE WEBSITE GEPLAATST WORDEN NADAT DE KLANT HEEFT AANGEKLIKT DAT HIJ AKKOORD GAAT MET DEZE ALGEMENE VERKOOPVOORWAARDEN.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 5. ACCOUNT</strong></span></p>
<p class="p1"><span class="s1">5.1 DE KLANT KAN EEN ACCOUNT AANMAKEN OP DE WEBSITE, ZODAT DE KLANT NIET IEDERE KEER DAT HIJ EEN BESTELLING PLAATST ZIJN GEGEVENS OPNIEUW DIENT IN TE VULLEN.</span></p>
<p class="p1"><span class="s1">5.2 NADAT DE KLANT EEN ACCOUNT HEEFT AANGEMAAKT OP DE WEBSITE, ONTVANGT HIJ DAARVAN EEN BEVESTIGING VIA DE E-MAIL.</span></p>
<p class="p1"><span class="s1">5.3 DE KLANT IS ZELF VERANTWOORDELIJK VOOR HET GEBRUIK VAN ZIJN INLOGGEGEVENS. GETNORD.COM KAN OP GEEN ENKELE WIJZE AANSPRAKELIJK WORDEN GESTELD VOOR HET VERLIES VAN DOOR DE KLANT TOEGEPASTE INLOGCODES. GETNORD.COM KAN ER DAN OOK NIET VERANTWOORDELIJK VOOR WORDEN GESTELD INDIEN ONGEAUTORISEERDE DERDEN GEBRUIK MAKEN VAN DE INLOGCODES VAN DE KLANT.INDIEN ONGEAUTORISEERDE DERDEN GEBRUIK MAKEN VAN DE INLOGGEGEVENS VAN DE KLANT, DAN DIENT DE KLANT GETNORD.COM DAARVAN ONVERWIJLD IN KENNIS TE STELLEN.</span></p>
<p class="p1"><span class="s1">5.4 DE KLANT KAN ZIJN ACCOUNT TE ALLEN TIJDE SLUITEN.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 6. VERPLICHTINGEN VAN DE KLANT</strong></span></p>
<p class="p1"><span class="s1">6.1 ALLE GEGEVENS DIE DE KLANT BIJ HET TOT STAND KOMEN VAN DE OVEREENKOMST OF BIJ HET AANMAKEN VAN EEN ACCOUNT OP DE WEBSITE AAN GETNORD.COM VERSTREKT, DIENEN JUIST EN VOLLEDIG TE ZIJN.</span></p>
<p class="p1"><span class="s1">6.2 HET IS NIET TOEGESTAAN OM VAN DE WEBSITE GEBRUIK TE MAKEN OP EEN MANIER DIE ANDERE GEBRUIKERS ZOU KUNNEN HINDEREN OF ANDERSZINS HET GOEDE FUNCTIONEREN VAN DE WEBSITE ZOU KUNNEN AANTASTEN. HET IS VOORTS NIET TOEGESTAAN OM DOOR HET OMZEILEN VAN BEVEILIGINGSMAATREGELEN OF MET GEBRUIKMAKING VAN ANDERE DAN DE EIGEN PERSOONLIJKE INLOGGEGEVENS VAN AFGESLOTEN ONDERDELEN VAN DE WEBSITE GEBRUIK TE MAKEN.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 7. PRIJZEN</strong></span></p>
<p class="p1"><span class="s1">7.1 DE OP DE WEBSITE VERMELDE PRIJZEN VOOR DE PRODUCTEN ZIJN IN EURO’S EN INCLUSIEF BTW.</span></p>
<p class="p1"><span class="s1">7.2 GETNORD.COM HEEFT HET RECHT HAAR PRIJZEN VAN TIJD TOT TIJD AAN TE PASSEN.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 8. ERZENDKOSTEN</strong></span></p>
<p class="p1"><span class="s1">8.1 DE OP DE WEBSITE VERMELDE PRIJZEN ZIJN EXCLUSIEF VERZENDKOSTEN.</span></p>
<p class="p1"><span class="s1">8.2 DE HOOGTE VAN DE VERZENDKOSTEN WORDT VOORDAT DE KLANT ZIJN BESTELLING KAN BEVESTIGEN OP DE WEBSITE AAN DE KLANT KENBAAR GEMAAKT.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 9. LEVERING EN LEVERINGSTERMIJN</strong></span></p>
<p class="p1"><span class="s1">9.1 DE BESTELLING WORDT OPGESTUURD NAAR HET DOOR DE KLANT OPGEGEVEN ADRES.</span></p>
<p class="p1"><span class="s1">9.2 DE VERMELDE LEVERINGSTERMIJN IS NIET ALS EEN FATALE TERMIJN TE BESCHOUWEN.</span></p>
<p class="p1"><span class="s1">9.3 INDIEN GETNORD.COM DE VIA DE WEBSITE BESTELDE PRODUCTEN NIET BINNEN 30 DAGEN NA DE BESTELLING KAN LEVEREN, DAN STELT GETNORD.COM DE KLANT DAARVAN VIA DE E-MAIL OP DE HOOGTE EN DAN HEEFT DE KLANT HET RECHT DE OVEREENKOMST KOSTELOOS TE ONTBINDEN, TENZIJ PARTIJEN UITDRUKKELIJK EEN LANGERE LEVERINGSTERMIJN ZIJN OVEREENGEKOMEN. INDIEN DE KLANT DE OVEREENKOMST ONTBINDT, DAN BETAALT GETNORD.COM EVENTUEEL REEDS BETAALDE BEDRAGEN TERUG BINNEN 14 DAGEN NA DE ONTBINDING.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 10. ONTBINDINGSRECHT</strong></span></p>
<p class="p1"><span class="s1">10.1 DE KLANT HEEFT HET RECHT GEDURENDE 14 KALENDERDAGEN NA ONTVANGST VAN DE GEHELE BESTELLING DE OVEREENKOMST ZONDER OPGAVE VAN REDENEN TE ONTBINDEN. DE KLANT ONTVANGT VIA DE E-MAIL OF BIJ DE LEVERING EEN FORMULIER DAT DE KLANT KAN GEBRUIKEN INDIEN HIJ DE OVEREENKOMST WIL ONTBINDEN. VIA DE E-MAIL VOOR DE LEVERING OF SCHRIFTELIJK BIJ DE AFLEVERING VAN DE BESTELDE PRODUCTEN WORDT DE KLANT GEWEZEN OP DIT ONTBINDINGSRECHT.</span></p>
<p class="p1"><span class="s1">10.2 DE KLANT DIENT BINNEN 14 DAGEN NA DE ONTBINDING VAN DE OVEREENKOMST DE PRODUCTEN TE RETOURNEREN, MITS ONGEBRUIKT, ONBESCHADIGD EN ONVERANDERD EN, INDIEN REDELIJKERWIJS MOGELIJK, IN DE ORIGINELE VERPAKKING. DE KLANT MAG HET PRODUCT WEL GEPAST HEBBEN.</span></p>
<p class="p1"><span class="s1">10.3 DE KLANT DIENT HET PAKKET DAT HIJ TERUGSTUURT VOLDOENDE TE FRANKEREN.</span></p>
<p class="p1"><span class="s1">10.4 ZIJN DE GERETOURNEERDE PRODUCTEN BESCHADIGD, INCOMPLEET OF GEBRUIKT, DAN WORDT DEZE SCHADE IN MINDERING GEBRACHT OP HET BEDRAG DAT GETNORD.COM OVEREENKOMSTIG ARTIKEL 10.6 AAN DE KLANT BETAALT.</span></p>
<p class="p1"><span class="s1">10.5 INDIEN DE KLANT DE OVEREENKOMST OVEREENKOMSTIG DIT ARTIKEL ONTBINDT, DAN ZIJN DE VERZENDKOSTEN IN VERBAND MET HET RETOURNEREN VAN HET PRODUCT VOOR REKENING VAN DE KLANT.</span></p>
<p class="p1"><span class="s1">10.6 GETNORD.COM ZAL BIJ EEN ONTBINDING ZOALS OMSCHREVEN IN DIT ARTIKEL BINNEN 30 DAGEN NA ONTVANGST VAN DE GERETOURNEERDE PRODUCTEN REEDS BETAALDE GELDEN (AANKOOPPRIJS + DE VERZENDKOSTEN VOOR HET LEVEREN VAN DE PRODUCTEN) RESTITUEREN. DE VERZENDKOSTEN WORDEN NIET AAN DE KLANT TERUGBETAALD INDIEN DE KLANT EEN DEEL VAN DE BESTELLING WEL HOUDT.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 11. RETOURADRES</strong></span></p>
<p class="p1"><span class="s1">11.1 DE PRODUCTEN DIENEN GERETOURNEERD TE WORDEN NAAR HET VOLGENDE ADRES:</span></p>
<p class="p1"><span class="s1">   Online Returns Department</span></p>
<p class="p1"><span class="s1">   Redlainas UAB   </span></p>
<p class="p1"><span class="s1">   Verslo str. 6, Kumpiai, 54311, Kaunas</span></p>
<p class="p1"><span class="s1">   Litouwen</span></p>
<p class="p2"> </p>
<p class="p1"><span class="s1"><strong>ARTIKEL 12. BETALING</strong></span></p>
<p class="p1"><span class="s1">12.1 DE KLANT KAN DE VIA DE WEBSITE BESTELDE PRODUCTEN OP DE VOLGENDE WIJZEN BETALEN:</span></p>
<p class="p1"><span class="s1">    A. MET EEN CREDITCARD (VISA EN MASTERCARD);</span></p>
<p class="p1"><span class="s1">    B. VIA PAYPAL.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 13. KLANTENSERVICE</strong></span></p>
<p class="p1"><span class="s1">13.1 VOOR VRAGEN OVER DE BESTELLING OF HET INDIENEN VAN EEN KLACHT, KAN DE KLANT CONTACT OPNEMEN MET DE KLANTENSERVICE VAN GETNORD.COM. DE KLANTENSERVICE VAN GETNORD.COM IS OP DE VOLGENDE WIJZEN BEREIKBAAR:</span></p>
<p class="p1"><span class="s1">       VIA HET E-MAILADRES: support@getnord.com</span></p>
<p class="p1"><span class="s1">13.2 NDIEN MOGELIJK, WORDEN TELEFONISCHE VRAGEN DIRECT BEANTWOORD. IS DAT NIET MOGELIJK, DAN WORDT AAN DE KLANT KENBAAR GEMAAKT BINNEN WELKE TERMIJN DE KLANT EEN ANTWOORD KAN VERWACHTEN.</span></p>
<p class="p1"><span class="s1">13.3 VAN EEN VRAAG EN/OF KLACHT DIE VIA DE E-MAIL IS INGEDIEND EN DIE NIET DIRECT BEANTWOORD KAN WORDEN, WORDT EEN ONTVANGSTBEVESTIGING NAAR DE KLANT GESTUURD WAARIN WORDT OPGENOMEN BINNEN WELKE TERMIJN DE KLANT EEN ANTWOORD KAN VERWACHTEN EN/OF DE KLACHT AFGEHANDELD WORDT.</span></p>
<p class="p1"><span class="s1">13.4 KLACHTEN WORDEN DOOR GETNORD.COM IN IEDER GEVAL BINNEN 30 DAGEN AFGEHANDELD.</span></p>
<p class="p1"><span class="s1">13.5 DE KLANT DIENT GETNORD.COM DE MOGELIJKHEID TE GEVEN OM DE KLACHT TE ONDERZOEKEN.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 14. MELDEN VAN GEBREKEN EN SCHADE AAN PAKKET</strong></span></p>
<p class="p1"><span class="s1">14.1. ZICHTBARE GEBREKEN AAN DE GELEVERDE PRODUCTEN DIENEN ZO SPOEDIG MOGELIJK NA DE LEVERING AAN GETNORD.COM GEMELD TE WORDEN.</span></p>
<p class="p1"><span class="s1">4.2. INDIEN HET PAKKET MET DAARIN DE BESTELLING DOOR DE POSTBEZORGER AAN DE KLANT WORDT AANGEBODEN EN HET PAKKET IS BESCHADIGD, DAN DIENT DE KLANT HET PAKKET NIET TE ACCEPTEREN EN HET PAKKET NIET IN ONTVANGST TE NEMEN. DE KLANT HEEFT GEEN RECHT OP COMPENSATIE OF SCHADEVERGOEDING INDIEN ER SPRAKE IS VAN TRANSPORTSCHADE EN DE KLANT HET PAKKET WEL HEEFT GEACCEPTEERD EN IN ONTVANGST HEEFT GENOMEN.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 15. GARANTIE</strong></span></p>
<p class="p1"><span class="s1">15.1. OP DE PRODUCTEN VAN GETNORD.COM WORDT EEN GARANTIE VERLEEND.</span></p>
<p class="p1"><span class="s1">15.2. DE GARANTIEVOORWAARDEN STAAN OP DE WEBSITE ZIE WWW.GETNORD.COM</span></p>
<p class="p1"><span class="s1">15.3. DE GARANTIE KOMT DE KLANT TOE ONVERMINDERD DE RECHTEN DIE DE WET DE KLANT TOEKENT.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 16. AANSPRAKELIJKHEID</strong></span></p>
<p class="p1"><span class="s1">16.1. GETNORD.COM KAN NIET GEHOUDEN WORDEN TOT HET VERGOEDEN VAN ENIGE SCHADE DIE EEN DIRECT OF INDIRECT GEVOLG IS VAN:</span></p>
<p class="p1"><span class="s1">    A. EEN GEBEURTENIS DIE IN FEITE BUITEN HAAR MACHT LIGT EN ALDUS NIET AAN HAAR DOEN EN/OF LATEN KAN WORDEN TOEGESCHREVEN, ZOALS O.A. OMSCHREVEN IN ARTIKEL 17 VAN DEZE ALGEMENE VERKOOPVOORWAARDEN;</span></p>
<p class="p1"><span class="s1">    B. ENIGE DAAD OF NALATIGHEID VAN DE KLANT.</span></p>
<p class="p1"><span class="s1">16.2. GETNORD.COM IS NIET AANSPRAKELIJK VOOR EVENTUELE SCHADE VEROORZAAKT DOOR AL DAN NIET TIJDELIJKE ONBESCHIKBAARHEID VAN DE BESTELMOGELIJKHEID, ONBEREIKBAARHEID OF VERWIJDERING VAN HAAR WEBSITE WEGENS ONDERHOUD OF ANDERSZINS.</span></p>
<p class="p1"><span class="s1">16.3. DE KLEUREN DIE TE ZIEN ZIJN OP HET BEELDSCHERM VAN DE KLANT KUNNEN AFWIJKEN VAN DE KLEUREN DIE HET PRODUCT WERKELIJK HEEFT. GETNORD.COM IS NIET AANSPRAKELIJK VOOR DERGELIJKE KLEURAFWIJKINGEN.</span></p>
<p class="p1"><span class="s1">16.4. GETNORD.COM IS NIET AANSPRAKELIJK VOOR SCHADE, VAN WELKE AARD OOK, DOORDAT GETNORD.COM IS UITGEGAAN VAN DOOR DE KLANT VERSTREKTE ONJUISTE EN/OF ONVOLLEDIGE GEGEVENS, ZOALS HET DOOR DE KLANT VERKEERD OPGEVEN VAN EEN LEVERINGSADRES.</span></p>
<p class="p1"><span class="s1">16.5. GETNORD.COM IS NIET AANSPRAKELIJK VOOR VERMINKING OF VERLIES VAN GEGEVENS ALS GEVOLG VAN VERZENDING VAN DE GEGEVENS MET BEHULP VAN TELECOMMUNICATIEFACILITEITEN.</span></p>
<p class="p1"><span class="s1">16.6. INDIEN GETNORD.COM AANSPRAKELIJK MOCHT ZIJN VOOR ENIGERLEI SCHADE, DAN IS DE AANSPRAKELIJKHEID VAN GETNORD.COM BEPERKT TOT HET BEDRAG VAN DE DOOR DE VERZEKERAAR VAN GETNORD.COM GEDANE UITKERING. INDIEN DE VERZEKERAAR IN ENIG GEVAL NIET TOT UITKERING OVERGAAT OF DE SCHADE NIET DOOR DE VERZEKERING WORDT GEDEKT, IS DE AANSPRAKELIJKHEID VAN GETNORD.COM BEPERKT TOT HET FACTUURBEDRAG, ALTHANS TOT DAT GEDEELTE VAN DE OVEREENKOMST WAAROP DE AANSPRAKELIJKHEID BETREKKING HEEFT.</span></p>
<p class="p1"><span class="s1">16.7. DE IN DEZE ALGEMENE VERKOOPVOORWAARDEN OPGENOMEN BEPERKINGEN VAN DE AANSPRAKELIJKHEID GELDEN NIET INDIEN DE SCHADE TE WIJTEN IS AAN OPZET OF BEWUSTE ROEKELOOSHEID VAN GETNORD.COM OF HAAR ONDERGESCHIKTEN.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 17. OVERMACHT</strong></span></p>
<p class="p1"><span class="s1">17.1. GETNORD.COM IS NIET GEHOUDEN TOT HET NAKOMEN VAN ENIGE VERPLICHTING INDIEN ZIJ DAARTOE VERHINDERD WORDT ALS GEVOLG VAN OVERMACHT. ALS GEBEURTENISSEN DIE IN FEITE BUITEN DE MACHT VAN GETNORD.COM LIGGEN, DAN WEL NIET AAN HAAR DOEN EN/OF LATEN KUNNEN WORDEN TOEGESCHREVEN, WORDEN IN ELK GEVAL BESCHOUWD: NIET, NIET VOLLEDIGE EN/OF VERTRAAGDE LEVERING DOOR DE TOELEVERANCIERS VAN GETNORD.COM; OORLOG EN OORLOGSGEVAAR; IN - EN UITVOERVERBODEN; MAATREGELEN VAN NEDERLANDSE EN/OF INTERNATIONALE EN/OF BUITENLANDSE OVERHEIDSORGANEN DIE DE UITVOERING VAN DE OVEREENKOMST BEZWAARLIJKER EN/OF KOSTBAARDER MAKEN DAN BIJ HET AFSLUITEN VAN DE OVEREENKOMST TE VOORZIEN WAS; WERKSTAKINGEN EN/OF BEDRIJFSBEZETTINGEN; EPIDEMIEËN; VERKEERSSTORINGEN; WEERSINVLOEDEN; VERLIES OF BESCHADIGING BIJ TRANSPORT; BRAND; DIEFSTAL; STORINGEN IN LEVERING VAN ENERGIE; INTERNETSTORING.</span></p>
<p class="p1"><span class="s1">17.2. INDIEN GETNORD.COM WEET OF HET VERMOEDEN HEEFT DAT ZIJ DE BESTELLING (DEELS) NIET TIJDIG KAN LEVEREN DOOR OVERMACHT, DAN STELT GETNORD.COM DE KLANT DAARVAN ZO SPOEDIG MOGELIJK VIA DE E-MAIL OP DE HOOGTE. IN EEN DERGELIJK GEVAL IS TEVENS ARTIKEL 9.3 VAN TOEPASSING.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 18. GEHEIMHOUDING</strong></span></p>
<p class="p1"><span class="s1">18.1. BEIDE PARTIJEN ZIJN VERPLICHT TOT GEHEIMHOUDING VAN ALLE VERTROUWELIJKE INFORMATIE DIE ZIJ IN HET KADER VAN HUN OVEREENKOMST VAN ELKAAR OF UIT ANDERE BRON HEBBEN VERKREGEN. INFORMATIE GELDT ALS VERTROUWELIJK ALS DIT DOOR DE ANDERE PARTIJ IS MEDEGEDEELD OF ALS DIT VOORTVLOEIT UIT DE AARD VAN DE INFORMATIE. DE PARTIJ DIE VERTROUWELIJKE INFORMATIE ONTVANGT, ZAL DEZE SLECHTS GEBRUIKEN VOOR HET DOEL WAARVOOR DEZE VERSTREKT IS.</span></p>
<p class="p1"><span class="s1">18.2. GETNORD.COM VERWERKT PERSOONSGEGEVENS IN OVEREENSTEMMING MET HAAR PRIVACY STATEMENT. DE PRIVACY STATEMENT VAN GETNORD.COM STAAT OP DE WEBSITE ZIE WWW.GETNORD.COM</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 19. INTELLECTUELE EIGENDOMSRECHTEN</strong></span></p>
<p class="p1"><span class="s1">19.1. DE KLANT DIENT ALLE INTELLECTUELE EIGENDOMSRECHTEN WELKE RUSTEN OP DE DOOR GETNORD.COM GELEVERDE PRODUCTEN EN OP DE WEBSITE GEHEEL EN ONVOORWAARDELIJK TE RESPECTEREN.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 20. BEVEILIGING EN INTERNET</strong></span></p>
<p class="p1"><span class="s1">20.1. GETNORD.COM ZAL PASSENDE BEVEILIGINGSMAATREGELEN NEMEN OM DE WEBSITE TE BESCHERMEN TEGEN DE RISICO'S VAN ONBEVOEGDE TOEGANG TOT OF WIJZIGING, VERNIETIGING OF VERLIES VAN DE DOOR DE KLANT VIA DE WEBSITE INGEVOERDE GEGEVENS.</span></p>
<p class="p1"><span class="s1"><strong>ARTIKEL 21. GEBRUIK VAN PROMOTIECODES</strong></span></p>
<p class="p1"><span class="s1">20.1. OFFICIËLE GETNORD.COM PROMOTIECODES ZIJN UITSLUITEND ONLINE TE GEBRUIKEN BIJ BESTELLINGEN OP DE SITE WWW.GETNORD.COM. OM VAN DE PROMOTIECODE DE GEBRUIK TE MAKEN KUNNEN DE INTERNETGEBRUIKERS DEZE CODE INVULLEN OP DE PAGINA VAN HET WINKELMANDJE IN HET DAARVOOR BESTEMDE HOKJE BIJ DE VRAAG "HEEFT U EEN KORTINGSCODE ?" SLECHTS ÉÉN PROMOTIE CODE KAN GEBRUIKT WORDEN PER BESTELLING. DE PROMOTIECODES KUNNEN NIET SAMEN MET ANDERE PROMOTIES OF AANBIEDINGEN GEBRUIKT WORDEN. DE PROMOTIE CODES ZIJN LANDELIJK. DEZE CODE WORDT NIET IN GELD UITBETAALD. DE PROMOTIE CODES EN DAARBIJ BEHORENDE AANBIEDINGEN ZIJN NIET TOEGANKELIJK VOOR WERKNEMERS VAN GETNORD.COM WELKE ALLE RECHTEN VOORBEHOUDT OM ZE IN TE TREKKEN EN/OF TE WEIGEREN EN/OF THE BEPERKEN OP ELK MOMENT. PROMOTIECODES ZIJN ALLEEN GELDIG IN HET LAND WAAR ZE GECREËERD ZIJN EN HEBBEN UITSLUITEND BETREKKING OP BETALINGEN IN DE VALUTA VAN HET LAND. BIJVOORBEELD PROMOTIE CODES GELDIG IN NEDERLAND KUNNEN ALLEEN BIJ BETALINGEN IN EUROS OP DE NEDERLANDSE GETNORD.COM SITE GEBRUIKT WORDEN. GELIEVE DE VOORWAARDEN VAN ELKE PROMOTIE CODE TE CONTROLEREN OM TE WETEN IN WELK LAND DE PROMOTIECODE GEBRUIKT KAN WORDEN.</span></p>
<p class="p1"><span class="s1">FORMULIER VOOR HERROEPING</span></p>
<p class="p1"><span class="s1">E EUROPESE WETGEVING VERPLICHT ALLE WEBWINKELS OM DE VOLGENDE LINK OP TE NEMEN TER VERWIJZING NAAR HET ONLINE DISPUTE RESOLUTION (ODR) PLATFORM VAN DE EUROPESE COMMISSIE: <a href="http://ec.europa.eu/consumers/odr/"><span class="s2">HTTP://EC.EUROPA.EU/CONSUMERS/ODR/</span> </a>.</span></p>
</div>
</div>
@endsection