@extends('layouts.informational')

@section('content')
<div class="main_container">
    <div class="page" title="Page 1">
<div class="section">
<div class="layoutArea">
<div class="column">
<p class="p1"> </p>
<p class="p2"><span class="s1"><strong>CONDIZIONI DI VENDITA</strong></span></p>
<p class="p1"> </p>
<p class="p2"><span class="s1"><strong>1. Oggetto</strong></span></p>
<p class="p2"><span class="s1">1.1. Le presenti condizioni generali di vendita si applicano all’acquisto dei prodotti a marchio “Getnord” (di seguito “<strong>Prodotti</strong>”) eseguito attraverso il sito di e-commerce getnord.cpm (di seguito il “<strong>Sito</strong>”) da parte di utenti qualificabili come “Consumatori” ai sensi del successivo articolo 1.2. Il Sito, di titolarità di Redlainas, con sede legale in Lituania, Kaunas via Verslo 6 , partita IVA LT100001855118 e numero d’iscrizione al Registro delle Imprese di Kunas N° 235983690 (di seguito “<strong>Titolare</strong>”).</span></p>
<p class="p2"><span class="s1"> generali di vendita, ma titolare dei diritti sul nome a dominio del Sito, dei loghi e dei marchi, relativi ai prodotti presentati sul Sito, nonché del diritto d’autore sui contenuti del Sito.</span></p>
<p class="p2"><span class="s1">1.2. Qualsivoglia comunicazione del Consumatore connessa e/o correlata all’acquisto dei Prodotti - ivi incluse eventuali segnalazioni, reclami, richieste concernenti l’acquisto e/o la consegna dei Prodotti, l’esercizio del diritto di recesso, etc. - dovrà essere inviata al Venditore ai recapiti e secondo le modalità indicate sul Sito e all’indirizzo e-mail support@getnord.com </span></p>
<p class="p2"><span class="s1">1.3. Ogni acquisto è regolato dalle condizioni generali di vendita nella versione che risulterà pubblicata sul Sito al momento della trasmissione dell’ordine da parte del Consumatore.</span></p>
<p class="p2"><span class="s1">1.4. Il Sito è dedicato alla vendita al dettaglio e come tale è inteso ad uso esclusivo dei Consumatori.  Sono invitati a non eseguire ordini di acquisto i soggetti che non siano Consumatori. Qualora una o più vendite siano eseguite nei confronti di un soggetto non qualificabile Consumatore, troveranno applicazione le presenti condizioni generali di vendita ma, in deroga a quanto previsto nelle stesse:</span></p>
<p class="p2"><span class="s1">a)       all’acquirente non sarà riconosciuto il diritto di recesso di cui all’articolo 10;</span></p>
<p class="p2"><span class="s1">b)      l’acquirente non potrà beneficiare della garanzia sui Prodotti indicata all’articolo 8;</span></p>
<p class="p2"><span class="s1">c)       all’acquirente non saranno riconosciute altre eventuali tutele, qui previste in favore del Consumatore, che riflettono o sono conformi a previsioni inderogabili di legge;</span></p>
<p class="p2"><span class="s1">d)      il contratto di vendita concluso tra il Venditore e l’acquirente sarà regolato dalla legge italiana, con esclusione della United Nations Convention on Contracts for the International Sale of Goods - Convenzione di Vienna del 1980.</span><span class="s1"> </span></p>
<p class="p2"><span class="s1">1.5. Contestualmente alla trasmissione dell’ordine di acquisto, il Consumatore accetta che la conferma delle informazioni relative all’ordine effettuato e le presenti condizioni generali di vendita gli siano inviate via e-mail all’indirizzo dallo stesso dichiarato durante la registrazione al Sito ovvero durante il processo di acquisto.</span></p>
<p class="p2"><span class="s1">1.6. Per poter effettuare acquisti tramite il Sito, il Consumatore deve possedere la maggiore età (18 anni) e la capacità di agire, che il Consumatore dichiara di possedere.</span></p>
<p class="p2"><span class="s1">1.7. Sono ad esclusivo carico del Consumatore le eventuali spese per la connessione via Internet al Sito, ivi incluse quelle telefoniche, secondo le tariffe applicate dall’operatore selezionato dal Consumatore stesso.</span></p>
<p class="p2"><span class="s1"><strong>2. Caratteristiche dei Prodotti e loro disponibilità nelle diverse aree geografiche</strong></span></p>
<p class="p2"><span class="s1">2.1. I Prodotti sono venduti con le caratteristiche descritte sul Sito e secondo le condizioni generali di vendita pubblicate sul Sito al momento dell’invio dell’ordine da parte del Consumatore, con l’esclusione di ogni altra condizione o termine.</span></p>
<p class="p2"><span class="s1">2.2. Il Venditore si riserva il diritto di modificare le presenti condizioni generali di vendita in qualsiasi momento, a propria discrezione, senza necessità di fornire alcun preavviso agli utenti del Sito. Eventuali modifiche apportate saranno efficaci dalla data di pubblicazione sul Sito e si applicheranno unicamente alle vendite concluse a partire da tale data.</span></p>
<p class="p2"><span class="s1">2.3. I prezzi, i Prodotti in vendita sul Sito e/o le caratteristiche degli stessi, sono soggetti a variazioni senza preavviso. Prima di inviare l’ordine di acquisto ai sensi del successivo punto 3, il Consumatore è  invitato a verificare il prezzo finale di vendita.</span></p>
<p class="p2"><span class="s1">2.4 Al Sito si può accedere da tutto il mondo. Tuttavia, i Prodotti disponibili sul Sito sono acquistabili esclusivamente da parte di utenti che ne richiedano la consegna in uno degli Stati che sono indicati sul Sito.</span></p>
<p class="p2"><span class="s1"><strong>3. Modalità di acquisto dei Prodotti - Perfezionamento di ogni singolo contratto di acquisto</strong></span></p>
<p class="p2"><span class="s1">3.1. La presentazione dei Prodotti sul Sito, non vincolante per il Venditore, rappresenta un mero invito rivolto al Consumatore a formulare una proposta contrattuale d’acquisto e non un’offerta al pubblico.</span></p>
<p class="p2"><span class="s1">3.2. L’ordine d’acquisto trasmesso dal Consumatore al Venditore mediante il Sito ha valore di proposta contrattuale ed è regolato dalle presenti condizioni generali di vendita, che costituiscono parte integrante dell’ordine stesso e che il Consumatore, mediante la trasmissione dell’ordine al Venditore, è tenuto ad accettare integralmente e senza riserva alcuna. Prima di procedere all’acquisto dei Prodotti, tramite invio dell’ordine di acquisto, sarà chiesto al Consumatore di leggere attentamente le presenti condizioni generali di vendita e l’informativa sul diritto di recesso, di stamparne una copia attraverso il comando di stampa e di memorizzarne o di riprodurne una copia per i propri usi personali. Inoltre, sarà chiesto al Consumatore di individuare e di correggere eventuali errori di inserimento dei propri dati.</span></p>
<p class="p2"><span class="s1">3.3. L’ordine d’acquisto del Consumatore è accettato dal Venditore con l’invio al Consumatore, all’indirizzo di posta elettronica da questi dichiarato al Venditore al momento della registrazione al Sito ovvero della trasmissione dell’ordine qualora il Consumatore non sia registrato al Sito, di una e-mail di conferma dell’ordine stesso, la quale riporterà il link al testo delle presenti condizioni generali di vendita, il riepilogo dell’ordine effettuato e la descrizione delle caratteristiche del Prodotto ordinato. L’ordine del Consumatore, la conferma dell’ordine del Venditore e le condizioni generali di vendita applicabili al rapporto fra le Parti saranno archiviati elettronicamente dal Venditore nei propri sistemi informatici e il Consumatore potrà richiederne copia inviando una comunicazione via e-mail al Venditore all’indirizzo support@getnord.com </span></p>
<p class="p2"><span class="s1">3.4. Ogni contratto di acquisto dei Prodotti si intende concluso nel momento in cui il Consumatore riceve la conferma dell’ordine dal Venditore via posta elettronica.</span><span class="s1"> </span></p>
<p class="p2"><span class="s1"><strong>4. Procedura di selezione e acquisto dei Prodotti</strong></span></p>
<p class="p2"><span class="s1">4.1. I Prodotti presentati sul Sito potranno essere acquistati mediante la selezione dei Prodotti d’interesse del Consumatore e il loro inserimento nell’apposito carrello virtuale di acquisto. Terminata la selezione dei Prodotti, per eseguire l’acquisto dei inseriti nel carrello, il Consumatore sarà invitato a <em>(i)</em> registrarsi al Sito, fornendo i dati richiesti, ovvero <em>(ii)</em> ad eseguire il login, qualora il Consumatore sia già registrato ovvero <em>(iii)</em> a fornire i propri dati al fine di completare l’ordine e consentire il perfezionamento del contratto. Qualora i dati indicati nell’ordine siano diversi da quelli forniti in fase di registrazione al Sito, sarà richiesto al Consumatore di confermare i propri dati (a titolo esemplificativo ma non esaustivo: nome, cognome, etc.), nonché l’indirizzo ove consegnare i Prodotti selezionati, l’indirizzo di fatturazione e, facoltativamente, un numero telefonico ove poterlo contattare per eventuali comunicazioni relative all’acquisto effettuato. Il Consumatore visualizzerà un riepilogo dell’ordine da eseguire, di cui potrà modificare i contenuti: quindi, il Consumatore, previa attenta lettura, dovrà approvare espressamente le presenti condizioni generali di vendita, attraverso l’apposito segno di spunta (check-box) presente sul Sito ed infine, attraverso il tasto “Inserisci ordine”, sarà richiesto al Consumatore di confermare il suo ordine, che sarà così definitivamente inviato al Venditore e produrrà gli effetti descritti al precedente par. 3.2. del presente contratto. Al Consumatore sarà altresì chiesto di scegliere la modalità di spedizione e il metodo di pagamento, fra quelli disponibili. Qualora il Consumatore decidesse per la modalità di pagamento immediato (contestuale all’acquisto) a mezzo carta di credito, PayPal, sarà tenuto a comunicare i relativi dati rilevanti tramite connessione protetta. Per esigenze contabili ed amministrative, il Venditore si riserva il diritto di verificare le generalità indicate dal Consumatore. Qualora il pagamento sia eseguito mediante carta di credito, l’importo di acquisto sarà addebitato esclusivamente al momento della trasmissione della conferma dell’ordine dal Venditore al Consumatore.</span></p>
<p class="p2"><span class="s1">4.2. Qualora nel corso della procedura di selezione dei Prodotti sul Sito di cui al precedente punto 4.1, il Consumatore rilevi che il prezzo di uno o più dei Prodotti che intende selezionare per il successivo acquisto sia palesemente inferiore a quello normalmente applicato, al netto di eventuali sconti e/o promozioni a quel tempo in vigore, a causa di un evidente problema tecnico verificatosi sul Sito, è pregato di non completare il proprio ordine di acquisto e di segnalare il suddetto errore tecnico al Servizio alla Clientela del Venditore, inviando una e-mail all’indirizzo di posta elettronica support@getnord.com </span></p>
<p class="p2"><span class="s1">4.3. Nei casi in cui il Consumatore abbia completato il proprio ordine di acquisto e sia in quest’ultimo incluso un Prodotto il cui prezzo sia palesemente inferiore a quello normalmente applicato, al netto di eventuali sconti e/o promozioni a quel tempo in vigore, a causa di un evidente problema tecnico verificatosi sul Sito:</span></p>
<p class="p2"><span class="s1">(a) se il Consumatore medesimo non ha ancora ricevuto il Prodotto, il Venditore provvederà a (i) annullare l’ordine, la cui consegna non verrà quindi eseguita, inviando contestualmente una comunicazione a tal riguardo via e-mail, all’indirizzo di posta elettronica indicato dal Consumatore in fase di trasmissione dell’ordine e (ii) rimborsare al Consumatore i pagamenti dal medesimo effettuati in relazione all’ordine annullato, comprensivi dei costi di consegna, senza indebito ritardo e, in ogni caso, non oltre 14 giorni dall’annullamento dell’ordine, utilizzando lo stesso mezzo di pagamento usato dal Consumatore per la transazione iniziale;</span></p>
<p class="p2"><span class="s1">(b) se il Consumatore ha ricevuto il Prodotto, il Venditore informerà tempestivamente via e-mail il Consumatore dell’errore verificatosi nel processo di completamento del proprio ordine, offrendo al medesimo, in alternativa, di (i) versare a favore del Venditore, entro e non oltre i successivi 5 (cinque) giorni, mediante uno dei metodi di pagamento disponibili sul Sito, l’importo corrispondente alla differenza tra il prezzo corretto del Prodotto e il prezzo errato risultante dall’ordine di acquisto, o (ii) annullare il proprio ordine, seguendo le istruzioni contenute nella medesima comunicazione e restituendo il Prodotto al Venditore, a spese di quest’ultimo, entro e non oltre i successivi 14 (quattordici) giorni, inviandolo a Redlainas, Via Verslo 6 - 54311 -Kumpiai, Kaunas, Lituania, privo di danni, completo di tutti i suoi elementi ed accessori (ivi incluse le etichette e i cartellini inalterati ed attaccati al prodotto), corredato dalle istruzioni/note/manuali allegati, dalle confezioni e imballaggi originali e dal certificato di garanzia e accompagnato dal modulo di reso, idoneamente compilato, che troverà allegato alla e-mail trasmessa dal Venditore. Nel caso in cui il Consumatore abbia scelto l’opzione di cui al precedente punto (b) (ii), il Venditore provvederà a rimborsare al Consumatore i pagamenti dal medesimo effettuati in relazione all’ordine annullato, comprensivi dei costi di consegna, senza indebito ritardo e, in ogni caso, non oltre 14 giorni dall’annullamento dell’ordine, utilizzando lo stesso mezzo di pagamento usato dal Consumatore per la transazione iniziale</span></p>
<p class="p2"><span class="s1"><strong>5. Consegna della merce ed accettazione</strong></span></p>
<p class="p2"><span class="s1">5.1. Il Sito indica la disponibilità dei Prodotti e i tempi di consegna degli stessi, tuttavia, tali informazioni sono da considerarsi puramente indicative e non vincolanti per il Venditore.</span></p>
<p class="p2"><span class="s1">5.2 Il Venditore si impegna a fare quanto nelle proprie facoltà al fine di rispettare i tempi di consegna indicati sul Sito e, in ogni caso, ad eseguire la consegna in un tempo massimo di 30 (trenta) giorni a decorrere dal giorno successivo a quello in cui il Consumatore ha trasmesso l’ordine. In caso di mancata esecuzione dell’ordine da parte del Venditore, dovuta alla indisponibilità, anche temporanea, del Prodotto, il Venditore fornirà comunicazione scritta al Consumatore e provvederà al rimborso delle somme eventualmente già corrisposte dal Consumatore per il pagamento del Prodotto ai sensi del successivo par. 5.3. Qualora il Consumatore abbia scelto il bonifico bancario quale modalità di pagamento il termine di consegna decorrerà dalla ricezione del corrispettivo da parte del Venditore.</span></p>
<p class="p2"><span class="s1">5.3. La spedizione dei Prodotti ordinati dal Consumatore avverrà nella modalità selezionata dal Consumatore, fra quelle disponibili ed indicate sul Sito al momento dell’invio dell’ordine. Il Consumatore si impegna a controllare tempestivamente e nel più breve periodo possibile che la consegna comprenda tutti e soli i prodotti acquistati e ad informare tempestivamente il Venditore di qualsiasi eventuale difetto dei prodotti ricevuti o di loro difformità rispetto all’ordine effettuato, secondo la procedura di cui al successivo art. 8 delle presenti condizioni generali di vendita, in mancanza i prodotti si intenderanno accettati. Qualora la confezione o l’involucro dei prodotti ordinati dal Consumatore dovessero giungere a destinazione palesemente danneggiati, il Consumatore è invitato a rifiutare la consegna da parte del vettore/spedizioniere o ad accettarne la consegna “con riserva”.</span></p>
<p class="p2"><span class="s1"><strong>6. Prezzi, costi di spedizione, imposte e tasse</strong></span></p>
<p class="p2"><span class="s1">6.1. Il prezzo dei Prodotti è quello indicato sul Sito contestualmente all’invio dell’ordine da parte del Consumatore. I prezzi sono comprensivi dei costi di imballaggio standard, IVA (qualora applicabile) e di eventuali imposte indirette (qualora applicabili), mentre non comprendono le spese di spedizione che sono calcolati prima della conferma dell’ordine trasmessa dal Venditore al Consumatore e che lo stesso Consumatore si impegna a versare al Venditore in aggiunta al prezzo indicato sul Sito.</span></p>
<p class="p2"><span class="s1">6.2. Il Consumatore dovrà versare al Venditore il prezzo totale, come riportato nell’ordine e nella conferma dell’ordine inviata via e-mail dal Venditore al Consumatore.</span></p>
<p class="p2"><span class="s1">6.3. Qualora i Prodotti debbano essere consegnati in un paese non appartenente all’Unione Europea, il prezzo totale indicato nell’ordine e ribadito nella conferma dell’ordine, comprensivo di  imposte indirette (qualora applicabili) è al netto di eventuali dazi doganali e di qualsiasi altra imposta sulle vendite, che il Consumatore si impegna sin d’ora a versare, se dovute, in aggiunta al prezzo indicato nell’ordine e confermato nella conferma d’ordine, secondo quanto previsto dalle disposizioni di legge del paese in cui i prodotti saranno consegnati. Il Consumatore è invitato ad informarsi presso gli organi competenti del proprio paese di residenza o di destinazione dei prodotti, al fine di ottenere informazioni su eventuali dazi o tasse applicati nel proprio paese di residenza o di destinazione dei prodotti.</span></p>
<p class="p2"><span class="s1">6.4. Sono ad esclusivo carico del Consumatore, qualsivoglia eventuale ulteriore costo, onere, tassa e/o imposta che un dato paese dovesse applicare, a qualsivoglia titolo ai Prodotti ordinati in base alle presenti condizioni generali di vendita.</span></p>
<p class="p2"><span class="s1">6.5. Il Consumatore dichiara che la mancata conoscenza dei costi, oneri, dazi, tasse e/o imposte di cui ai precedenti parr. 6.3. e6.4., al momento dell’invio di un ordine al Venditore, non potrà costituire causa di risoluzione del presente contratto e che non potrà in alcun modo addebitare i suddetti oneri al Venditore.</span></p>
<p class="p2"><span class="s1"> </span><span class="s1"><strong>7. Pagamenti</strong></span></p>
<p class="p2"><span class="s1">7.1. Il pagamento del prezzo dei Prodotti acquistati attraverso il Sito dovrà essere effettuato entro il termine essenziale di 10 (dieci) giorni decorrenti dalla data di trasmissione della conferma d’ordine dal Venditore al Consumatore. Il Consumatore accetta espressamente che l’esecuzione del contratto da parte del Venditore avrà inizio al momento dell’accredito del prezzo del/i Prodotto/i acquistato/i sul conto corrente del Venditore stesso.</span></p>
<p class="p2"><span class="s1">7.2. Il pagamento potrà essere eseguito con carta di credito o tramite PayPal, alle condizioni di seguito descritte. Il Venditore potrà consentire ulteriori metodi di pagamento, indicandoli nella sezione pagamenti del Sito.</span></p>
<p class="p3"><span class="s2">7.3. Qualora il pagamento sia eseguito tramite carta di credito, il Consumatore sarà trasferito su un sito protetto e i dati della carta di credito verranno comunicati direttamente a Braintree, a division of PayPal</span><span class="s1">, operatore che si occupa dei pagamenti per conto del Venditore. I dati trasmessi saranno inviati in modalità protetta, mediante il trasferimento crittografato dei dati con sistema SSL (SecureSocketLayer) a 128 bit. Tali dati non sono  accessibili nemmeno per il Venditore.</span></p>
<p class="p2"><span class="s1">7.4. Qualora il pagamento sia eseguito tramite bonifico bancario a favore del Venditore, il Consumatore dovrà indicare i codici “Swift” e “IBAN” riportati nella conferma dell’ordine, nonché il numero d’ordine.</span></p>
<p class="p2"><span class="s1">7.5. Il Venditore trasmetterà tempestivamente al Consumatore, qualora previsto dalla legge applicabile, in formato elettronico via e-mail all’indirizzo dichiarato dallo stesso, la ricevuta fiscale relativa all’acquisto eseguito, se i Prodotti acquistati sono destinati ad essere consegnati nel territorio italiano, oppure allegata in formato cartaceo ai Prodotti acquistati, in tutti gli altri casi.</span></p>
<p class="p2"><span class="s1"> </span><span class="s1"><strong>8. Garanzia legale di conformità del Venditore, segnalazione dei difetti di conformità e interventi in garanzia</strong></span></p>
<p class="p2"><span class="s1">8.1. Ai sensi e per gli effetti della Direttiva europea 44/99/CE e del Decreto legislativo italiano n. 206/2005 (Codice del consumo), il Venditore garantisce al Consumatore che i Prodotti saranno privi di difetti di progettazione e di materiale nonché conformi alle descrizioni pubblicate sul Sito per un periodo di 2 (due) anni dalla data di consegna dei Prodotti al Consumatore. È esclusa l’applicazione di qualsiasi garanzia in caso di utilizzo o lavaggio del Prodotto non conforme a quello proprio del Prodotto e alle istruzioni/avvertenze in merito fornite dal Venditore e/o dal Titolare, ovvero riportate nella documentazione illustrativa di riferimento, nei cartellini o nelle etichette.</span></p>
<p class="p2"><span class="s1">8.2. A pena di decadenza dalla presente garanzia, il Consumatore ha l’onere di denunciare eventuali difetti e non conformità entro e non oltre 2 (due) mesi dalla scoperta, trasmettendo al Customer Service all’indirizzo– Servizio alla Clientela del Venditore, a mezzo e-mail all’indirizzo support@getnord.com, l’apposito modulo correttamente compilato, con indicazione del difetto e/o della non conformità riscontrati, nonché la relativa documentazione indicata nel modulo di reso medesimo (almeno n. 1 (una) fotografia del Prodotto, la conferma dell’ordine trasmessa dal Venditore e/o la ricevuta fiscale).</span></p>
<p class="p2"><span class="s1">8.3. A seguito del ricevimento del modulo e della relativa documentazione, il Venditore valuterà i difetti e le non conformità denunciati dal Consumatore tramite il servizio di assistenza del Titolare e, dopo avere effettuato i controlli qualitativi atti a verificare l’effettiva non conformità del Prodotto, deciderà se autorizzare la restituzione dei Prodotti fornendo al Consumatore un riscontro, contenente il “Codice di reso”, via posta elettronica all’indirizzo fornito da quest’ultimo nel corso del processo di registrazione al Sito o in fase di trasmissione dell’ordine. L’autorizzazione a restituire i Prodotti non costituirà in alcun modo riconoscimento di difetti o non conformità, la cui esistenza dovrà essere accertata successivamente alla restituzione. I Prodotti di cui il Venditore abbia autorizzato la restituzione dovranno essere resi dal Consumatore, unitamente a copia della comunicazione di autorizzazione alla restituzione recante il “Codice di reso”, entro 30 (trenta) giorni dalla denuncia del difetto o della non conformità, al seguente indirizzo: Redlainas, Via Verslo 6 - 54311 -Kumpiai, Kaunas, Lituania.</span></p>
<p class="p2"><span class="s1">8.4. Qualora il Venditore sia tenuto a rimborsare al Consumatore il prezzo pagato, il rimborso verrà effettuato, ove possibile, mediante il medesimo mezzo di pagamento utilizzato dal Consumatore all’atto di acquisto del Prodotto o mediante bonifico bancario . Sarà onere del Consumatore comunicare al Venditore, sempre via posta e-mail all’indirizzo support@getnord.com , gli estremi bancari per effettuare il bonifico a suo favore e per far sì che il Venditore sia messo nella condizione di poter restituire la somma dovuta.</span></p>
<p class="p2"><span class="s1"><strong>9. Responsabilità per danno da prodotti difettosi</strong></span></p>
<p class="p2"><span class="s1">9.1. Per quanto riguarda eventuali danni provocati da difetti dei Prodotti, si applicano le disposizioni di cui alla direttiva europea 85/374/CEE e al Decreto legislativo italiano n. 206/2005 (Codice del consumo). Il Venditore, nella qualità di distributore dei prodotti tramite il Sito, si libera da qualsivoglia responsabilità, nessuna esclusa e/o eccettuata, indicando il nome del relativo produttore del prodotto.</span></p>
<p class="p2"><span class="s1"><strong>10. Diritto di recesso</strong></span></p>
<p class="p2"><span class="s1">10.1 Al Consumatore è riconosciuto il diritto di recedere da qualsiasi contratto concluso ai sensi delle presenti condizioni generali di vendita, senza alcuna penalità, entro il termine di 14 (quattordici) giorni da quando (i) è stato consegnato il prodotto o (ii) nel caso di acquisto di più prodotti consegnati separatamente con un solo ordine, è stato consegnato l’ultimo prodotto.</span></p>
<p class="p2"><span class="s1">10.2 Per esercitare il diritto di recesso, il Consumatore deve informare Redlainas, prima del decorso del termine di cui al precedente punto 10.1, della propria decisione accedendo alla pagina “I miei resi” dal Mio Account o, se non è registrato al sito, accedendo alla pagina dedicata e inserendo il numero dell’ordine e l’e-mail con cui ha effettuato l’acquisto. In alternativa, il Consumatore può inviare una dichiarazione esplicita a Redlainas tramite il form di contatto o all’indirizzo e-mail support@getnord.com della propria decisione di recedere utilizzando il modulo tipo di recesso allegato.</span></p>
<p class="p2"><span class="s1">10.3 A seguito di quanto previsto al precedente punto 10.2 il Consumatore riceverà una mail di conferma di esercizio del recesso, contenente il modulo di reso da inserire nel pacco, e le istruzioni per procedere alla restituzione del prodotto, da trasmettere entro e non oltre i successivi 14 giorni a</span></p>
<p class="p2"><span class="s1">Redlainas </span></p>
<p class="p2"><span class="s1">Verslo 6, Kumpiai</span></p>
<p class="p2"><span class="s1">Kaunas 54311 - Lituania</span></p>
<p class="p2"><span class="s1">10.4 Se il Consumatore ha ricevuto il prodotto, è tenuto a restituirlo a Redlainas senza indebiti ritardi e, in ogni caso, entro 14 giorni dal giorno in cui hai comunicato il recesso. Il termine è rispettato se rispedisci i beni prima della scadenza del periodo di 14 giorni. I rischi e i costi diretti della restituzione dei beni saranno a carico del Consumatore. Se eserciti il recesso mediante il sito, prima di confermare la richiesta di recesso ti sarà indicato il costo per la restituzione dei beni, qualora tu voglia utilizzare il servizio di restituzione offerto dal sito.</span></p>
<p class="p2"><span class="s1">10.5 Se recedi ti saranno rimborsati i pagamenti che hai effettuato, comprensivi dei costi di consegna (ad eccezione dei costi supplementari derivanti dalla eventuale scelta di un tipo di consegna diverso dal tipo meno costoso di consegna standard offerta), senza indebito ritardo e, in ogni caso, non oltre 14 giorni dall’esercizio del recesso. Detti rimborsi saranno effettuati utilizzando lo stesso mezzo di pagamento usato dal Consumatore per la transazione iniziale, salvo che il Consumatore non richieda il rimborso su diverso mezzo di pagamento, in tale caso saranno a carico del Consumatore eventuali costi aggiuntivi derivanti dal diverso mezzo di pagamento. Il rimborso può essere sospeso fino al ricevimento dei beni oppure fino all’avvenuta dimostrazione da parte del Consumatore di aver rispedito i beni, se precedente.</span></p>
<p class="p2"><span class="s1">10.6 Il Consumatore è responsabile della diminuzione del valore dei beni risultante da una manipolazione diversa da quella necessaria per stabilire la natura, le caratteristiche e il funzionamento dei beni. Pertanto, qualora i beni restituiti risultino danneggiati (ad esempio con segno di usura, abrasione, scalfittura, graffio, deformazioni, ecc.), non completi di tutti i loro elementi ed accessori (ivi incluse le etichette e i cartellini inalterati ed attaccati al prodotto), non corredati dalle istruzioni/note/manuali allegati, dalle confezioni e imballaggi originali e dal certificato di garanzia, ove presente, il Consumatore risponderà della diminuzione patrimoniale del valore del bene, ed avrà diritto al rimborso dell’importo pari al valore residuo del Prodotto. A tale fine, pertanto, il Consumatore è invitato a non manipolare il bene oltre quanto strettamente necessario a stabilire la natura, le caratteristiche e il funzionamento degli stessi e rivestire l’involucro originale dei Prodotti con altro imballo protettivo che ne conservi l’integrità e lo protegga durante il trasporto anche da scritte o da etichette.</span></p>
<p class="p2"><span class="s1"> </span><span class="s1"><strong>11. Diritti di proprietà intellettuale</strong></span></p>
<p class="p2"><span class="s1">11.1. Il Consumatore dichiara di essere informato che tutti i marchi, i nomi, così come pure ogni segno distintivo, denominazione, immagine, fotografia, testo scritto o grafico utilizzato sul Sito o relativo ai Prodotti sono e restano di esclusiva proprietà di Redlainas e/o dei suoi aventi causa, senza che dall’accesso al Sito e/o dall’acquisto dei Prodotti possa derivare al Consumatore alcun diritto sui medesimi.</span></p>
<p class="p2"><span class="s1">11.2. I contenuti del Sito non possono essere riprodotti, né integralmente né parzialmente, trasferiti con mezzi elettronici o convenzionali, modificati, o utilizzati a qualunque fine senza il previo consenso scritto di Redlainas</span></p>
<p class="p2"><span class="s1"><strong>12. Dati del Consumatore e tutela della privacy</strong></span></p>
<p class="p2"><span class="s1">12.1. Per poter procedere alla registrazione, all’inoltro dell’ordine e quindi alla conclusione del presente contratto sono richiesti attraverso il Sito alcuni dati personali al Consumatore. Il Consumatore prende atto che i dati personali forniti saranno registrati e utilizzati dal Venditore e da Redlainas, in conformità e nel rispetto della normativa di cui alla legge lituana - Codice Privacy, per dare esecuzione a ciascun acquisto eseguito tramite il Sito e, previo suo consenso, per le eventuali ulteriori attività così come indicate nell’apposita informativa sulla privacy fornita al Consumatore attraverso il Sito al momento della registrazione.</span></p>
<p class="p2"><span class="s1">12.2. Il Consumatore dichiara e garantisce che i dati forniti al Venditore durante il processo di registrazione e acquisto sono corretti e veritieri.</span></p>
<p class="p2"><span class="s1">12.3. Il Consumatore potrà in ogni momento aggiornare e/o modificare i propri dati personali forniti al Venditore attraverso l’apposita sezione del Sito “Mio Account” accessibile previa autenticazione.</span></p>
<p class="p2"><span class="s1">12.4. Per qualsivoglia ulteriore informazione sulle modalità di trattamento dei dati personali del Consumatore, preghiamo di accedere alla sezione </span><span class="s3">Privacy Policy</span><span class="s1"> nonché di leggere attentamente le </span><span class="s3">Condizioni Generali d’Uso.</span></p>
<p class="p2"><span class="s1"><strong>13. Sicurezza</strong></span></p>
<p class="p2"><span class="s1">13.1. Sebbene il Venditore adotti misure volte a proteggere i dati personali contro la loro eventuale perdita, falsificazione, manipolazione e utilizzo improprio da parte di terzi, a motivo delle caratteristiche e delle limitazioni tecniche relative alla protezione delle comunicazioni elettroniche via Internet, il Venditore non può garantire che le informazioni o i dati visualizzati dal Consumatore sul Sito, anche dopo che il Consumatore abbia provveduto all’autenticazione (login), non siano accessibili o visionabili da terze parti non autorizzate.</span></p>
<p class="p2"><span class="s1">13.2. Il Venditore, in merito ai dati relativi ai pagamenti con carta di credito si avvale dei servizi della società Global Collect Service BV che adotta sistemi tecnologici atti a garantire i massimi livelli di affidabilità, sicurezza, protezione e riservatezza nella trasmissione di informazioni via web.</span></p>
<p class="p2"><span class="s1"><strong>14. Legge applicabile, tentativo di conciliazione e foro competente</strong></span></p>
<p class="p2"><span class="s1">14.1. Le Condizioni Generali di Vendita Ogni contratto di vendita concluso tra il Venditore e i Consumatori ai sensi delle presenti condizioni generali di vendita sarà disciplinato ed interpretato in conformità alle leggi italiane ed in particolare dal decreto legislativo 6 settembre 2005 n. 206, sul codice al consumo, con specifico riferimento alla normativa in materia di contratti a distanza e dal decreto legislativo 9 aprile 2003 n. 70 su taluni aspetti concernenti il commercio elettronico. In ogni caso, saranno fatti salvi i diritti eventualmente attribuiti ai Consumatori da disposizioni inderogabili di legge vigenti nello Stato di questi ultimi.</span></p>
<p class="p2"><span class="s1">14.3 In alternativa al tentativo di conciliazione di cui al precedente punto 14.2, il Consumatore ha altresì la facoltà di accedere alla piattaforma Online Dispute Resolution europea (la Piattaforma ODR Europea) per la risoluzione di qualsivoglia controversia tra Venditore e Consumatore. La Piattaforma ODR Europea è sviluppata e gestita dalla Commissione Europa, in ottemperanza alla Direttiva 2013/11/EU e al Regolamento UE n. 524/2013, al fine di agevolare la risoluzione extragiudiziale indipendente, imparziale, trasparente, efficace, rapida ed equa delle controversie concernenti obbligazioni contrattuali derivanti da contratti di vendita o di servizi online tra un consumatore residente nell'Unione e un professionista stabilito nell'Unione attraverso l'intervento di un organismo ADR (alternative dispute resolution) che vi abbia aderito, selezionabile da un apposito elenco ivi disponibile. Per maggiori informazioni sulla Piattaforma ODR Europea o per avviare, tramite quest’ultima, una procedura di risoluzione alternativa di una controversia relativa al presente contratto, accedi al seguente link: <a href="http://ec.europa.eu/odr"><span class="s4">http://ec.europa.eu/odr</span></a>. L’indirizzo di posta elettronica del Venditore da indicare nella Piattaforma ODR Europea è il seguente: <a href="mailto:customercare@sergiotacchini.com"><span class="s4">customercare@sergiotacchini.com</span></a>.</span></p>
<p class="p2"><span class="s1">14.4. Qualora non si aderisca al tentativo di conciliazione di cui al precedente punto 14.2 o 14.3 ovvero tale tentativo dovesse avere esito negativo, la controversia sarà devoluta al giudice del luogo di residenza o domicilio del Consumatore.</span></p>
</div>
</div>
</div>
</div>
</div>
@endsection